weaveworks/scope

- probe/kubernetes/kubelet.go
- probe/kubernetes/kubelet_test.go
- probe/kubernetes/reporter.go
- probe/kubernetes/reporter_test.go
- prog/main.go
- prog/probe.go
Fixes #2258 (problem introduced by https://github.com/weaveworks/scope/pull/2132 ) and adds a new flag to configure kubelet's port (`--probe.kubernetes.kubelet-port`)
@errordeveloper Can you please test this in Openshift in these two scenarios?
1. Without setting the kubelet port appropriately (to make sure the fallback works)
2. Setting the kubelet port appropriately
> Fix kubelet failure fallback and make port configurable

- client/app/scripts/charts/node.js
- client/app/styles/_base.scss
Resolves #2255 trivially (and also decreases the opacity transition constant for the graph nodes).
I first tried a couple of different approaches to fix the bug, but all of them that worked were introducing a lot of overhead on the animations:
* Since the issue was coming from reordering the nodes, I thought React [Keyed Fragments](https://facebook.github.io/react/docs/create-fragment.html) were tailor made for cases like ours but turns out that using it instead of our sorting slowed down things a lot (pressumably because it only takes rendered stuff as input, so the caching only happens later on).
* Since the animation is happening with pure SVG elements, I thought of trying out [SVG animations](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateTransform), but I got the …
> Remove the throb animation for graph view search matches

- client/.babelrc
- client/app/scripts/actions.js
- client/app/scripts/actions/app-actions.js
- client/app/scripts/component.js
- client/app/scripts/components/app.js
- client/app/scripts/index.js
- client/app/scripts/reducer.js
- client/app/scripts/utils/router-utils.js
- client/app/scripts/utils/web-api-utils.js
- client/package.json
Needed for https://github.com/weaveworks/service-ui/pull/184.
When navigating to another page in Weave Cloud, Scope will be unmounted by `react-router`. This change will turn off topology polling and websocket connections when Scope dismounts.
> Add logic to turn off network requests when Scope dismounts

- integration/300_internet_edge_test.sh
- integration/301_internet_edge_with_ebpf_test.sh
They are currently flaky.
See https://github.com/weaveworks/scope/issues/2308
/cc @2opremio
> integration: disable tests with internet edge

- probe/process/walker_linux.go
when `proc/<pid>/cmdline` is empty, which is the case for some system and defunct processes.
Fixes #2315
> fall back to /proc/<pid>/comm for process name

- scope
`launch` first does a `scope --dry-run` to parse and validate Scope
cmdline arguments before starting the main Scope container and
processes. Use the same Docker args for the dry run to make sure the
container has the same privileges and mount points. Otherwise valid
`$WEAVESCOPE_DOCKER_ARGS` might fail here.
> scope: use same Docker args for early dry run

- integration/313_container_to_container_edge_with_ebpf_proc_fallback_test.sh
- probe/endpoint/connection_tracker.go
- probe/endpoint/ebpf.go
- probe/endpoint/reporter.go
- prog/probe.go
Not ready for merge yet, requires
> eBPF proc fallback

- app/api_topologies.go
- render/filters.go
To facilitate this, we replace the existing functionality of updateFilters which
sets k8s topologies to have the filters [namespace, managed], to instead append the namespace filter
to any existing. This lets it apply to both k8s and container topologies without overwriting existing
container filters. We instead set the managed filter in the static definition.
This however has the side effect that the ordering of the namespace filter and the managed filter
in k8s topologies has been reversed, so it reads:
```
Show Unmanaged | Hide Unmanaged
foo | bar | default | baz | All Namespaces
```
instead of:
```
foo | bar | default | baz | All Namespaces
Show Unmanaged | Hide Unmanaged
```
Fixes #1504
> When k8s present, allow filtering of containers by namespace

- client/app/scripts/utils/router-utils.js
Fix for https://github.com/weaveworks/scope/issues/2337
Reverted changes made here: https://github.com/weaveworks/scope/commit/d77502079466624caff88fa1c60431f4e7bfcdcc#diff-7dc7875cc44ad2eec50c55c6932e6ec2
> Fixed url state copy/paste bug

- app/api_topologies.go
- render/filters.go
This reverts commit 76ddc75fb8180011202ab1494e722758b43d2a86, reversing
changes made to 3ade2933eb7722ef4c8f2fe66eab9a58802daea9.
We are rolling this back for now because it's causing a bug where sub-topologies
would have ~3000 repeated cases of the k8s filters, causing performance issues clientside.
> Revert "Merge pull request #2285 from weaveworks/mike/k8s-ns-in-container-view"

- client/app/scripts/charts/__tests__/node-layout-test.js
- client/app/scripts/constants/naming.js
- client/app/scripts/reducers/__tests__/root-test.js
- client/app/scripts/reducers/root.js
- client/app/scripts/utils/__tests__/layouter-utils-test.js
- client/app/scripts/utils/layouter-utils.js
Fix for #2341 
Fixes a bug where bi-drectional arrows don't show up when mousing over the edge. Mousing over the node has always worked, but edge mouseover did not because only one edge is hover-able.
@fbarl Could you review please?
> Fix for inaccurate bidrectional edges on edge hover

- scope
Fix for #2357 
Moves the `--dry-run` to after OSX setup is completed.
> Changed --dry-run command to execute after OSX setup

- probe/endpoint/connection_tracker.go
- probe/endpoint/ebpf.go
- probe/endpoint/ebpf_test.go
- probe/endpoint/procspy/reader_linux.go
> Fallback to proc when ebpf timestamps are wrong

- integration/311_container_to_container_edge_with_ebpf_test.sh
- integration/312_container_to_container_edge_same_netns_with_ebpf_test.sh
- integration/config.sh
Integration test "311_container_to_container_edge_with_ebpf_test.sh" sometimes fails with the following error:
```
>>> Test ./311_container_to_container_edge_with_ebpf_test.sh finished after 125.0 secs with error: exit status 1
host1-weaveworks-scope-6767-1.us-central1-a.scope-integration-tests> weave
Test short lived connections between containers, with ebpf connection tracking enabled
8c6e4b72edf6fb359e084b061611aa3259071ee5cedefc2198575b741be0426e
Scope probe started
Weave Scope is reachable at the following URL(s):
* http://10.128.0.12:4040/
4c715954314eaf6194fe9de4a528c6591340e7fe07c5702ff72cae82c0bf7e29
d8d88a8786aab13141d6b6a16f748552c7f4c43b0b0568654d6f456a7bd26b46
Found 2 nodes after 4 secs
Found edge client -> nginx after 7 secs
Only 0 endpoints of 23 have ebpf enabled, should …
```
> integration tests: list containers for debugging

- common/weave/client.go
- prog/app.go
- vendor/github.com/weaveworks/common/errors/error.go
- vendor/github.com/weaveworks/common/httpgrpc/httpgrpc.go
- vendor/github.com/weaveworks/common/instrument/instrument.go
- vendor/github.com/weaveworks/common/middleware/grpc_auth.go
- vendor/github.com/weaveworks/common/middleware/grpc_logging.go
- vendor/github.com/weaveworks/common/middleware/http_auth.go
- vendor/github.com/weaveworks/common/middleware/instrument.go
- vendor/github.com/weaveworks/common/middleware/logging.go
- vendor/github.com/weaveworks/common/server/server.go
- vendor/github.com/weaveworks/common/signals/signals.go
- vendor/github.com/weaveworks/common/test/exec/exec.go
- vendor/github.com/weaveworks/common/user/grpc.go
- vendor/github.com/weaveworks/common/user/http.go
- vendor/github.com/weaveworks/common/user/id.go
- vendor/manifest
> Improve error reporting when invoking weave script

- client/app/scripts/components/troubleshooting-menu.js
> Hide 'Save canvas as SVG' button in Table View

- app/multitenant/billing_emitter.go
- prog/app.go
- prog/main.go
- vendor/github.com/weaveworks/billing-client/client.go
- vendor/github.com/weaveworks/billing-client/config.go
- vendor/github.com/weaveworks/billing-client/event.go
- vendor/manifest
Ignore the commits, they're to be squashed.
* Adds a billing-client package (to be extracted, probably), and `app/multitenant/billing_emitter`, which emit json to a fluentd instance running on `localhost:24225`
> Fluent Billing Emitter

- client/app/styles/_base.scss
> Fix help panel fields max height

- client/app/scripts/actions/app-actions.js
- client/app/scripts/components/app.js
- client/app/scripts/constants/action-types.js
- client/app/scripts/reducers/root.js
- client/app/scripts/utils/web-api-utils.js
Needed for https://github.com/weaveworks/service-ui/pull/358
Prevents additional polling when Scope is dismounted while running as a component. Also cleans up old nodes to show the correct loading screen when mounted.
> Clear client polling and nodes state on dismount 

- Makefile
- circle.yml
Needed for https://github.com/weaveworks/service-ui/pull/358
Does a `curl` to trigger a `service-ui` build. API token was added via CircleCI env variable.
> Add job to trigger service-ui build

- app/api_topologies.go
- render/filters.go
Re-applies https://github.com/weaveworks/scope/pull/2285 (reverted in https://github.com/weaveworks/scope/pull/2348)
and fixes the bug(s) that prompted the revert, which turned out to be a matter of accidentially mutating
objects in a variety of ways, some of which were introduced by https://github.com/weaveworks/scope/pull/2285 but
others that weren't, but were exposed as a problem due to changing the operation from a set to an append.
Fixes https://github.com/weaveworks/scope/issues/1504
> When k8s present, allow filtering of containers by namespace (take 2)

- render/pod.go
> Exclude pause containers when rendering k8s topologies

- client/app/scripts/actions/app-actions.js
- client/app/scripts/utils/web-api-utils.js
No calls for the relevant topologies in the resource view were being made because `getResourceViewNodesSnapshot` would be called before we'd get the response from `api/topology` with all the topologies' urls.
Timeout of `1200ms` made it work locally, but wasn't a proper solution for the dev. Hopefully this fixes #2391.
> Fetch resource view topologies on first topologies load

- client/app/scripts/utils/web-api-utils.js
It seems to make #2393 work (at least with the local UI servers that proxy to the dev); also let's see if it does anything to #2391.
> Using `doRequest` when fetching nodes of multiple topologies

- Makefile
Adds the Scope short commit hash to the path to module path on S3. This will require the `service-ui` app to explicitly declare which version of Scope should be installed. This introduces a (currently) manual step of changing the Scope version in `service-ui` and committing. The upside is an easy-to-understand commit log and predictable rollbacks.
> Add version to Scope UI module S3 path

- app/api_topologies.go
- app/api_topologies_test.go
- client/app/scripts/actions/app-actions.js
- client/app/scripts/components/topology-option-action.js
- client/app/scripts/components/topology-options.js
- client/app/scripts/reducers/__tests__/root-test.js
- client/app/scripts/reducers/root.js
- client/app/scripts/utils/web-api-utils.js
- render/filters.go
Implements #1421 
Exposes a new Topology option field: `selectType`. A `selectType` value of `'union'` will allow for a group of topology options to be selected at once. The use case for this was allowing users to see multiple Kubernetes namespaces on the same topology:
Topology options with `selectType: 'union'` must also provide a `noneLabel` field. In the example above the `noneLabel` value is 'All Namespaces';
> Allow the user to view multiple Kubernetes namespaces at once

- client/app/scripts/components/troubleshooting-menu.js
Fix for #2402 
If the `WEAVE_CLOUD` env variable is present, serve the JSON from the `/api` path.
> Fix for incorrect report.json URL in cloud

- client/app/scripts/charts/edge-container.js
Fixes #2378 
Adds default values to ensure that `<path />` edge elements don't receive a `NaN`.
> Add default values for edge waypoints

- CHANGELOG.md
- client/app/scripts/components/metric-selector.js
- client/app/scripts/components/troubleshooting-menu.js
- client/package.json
- site/installing.md
@davkal @foot @ekimekim @bowenli @jpellizzari @tomwilkie @abuehrle @pidster @errordeveloper @rade Please chip in by testing this release branch in the scenarios below and tick off what you tested afterwards (including your name at the end). Have a look at the CHANGELOG to prioritize your testing.
To make things easier to test I have pushed the image `weaveworks/scope:release-1.3-3721fbe`
Thanks!
- ECS Integration
> Release 1.3.0

- client/app/scripts/actions/app-actions.js
- client/app/scripts/components/search.js
Fixes #2235 (the last comment).
> Hide the opened help panel when clicking on the search bar icon

- client/app/scripts/utils/router-utils.js
Needed another serialization to avoid "[Object object]" in the url.
Fixes #2408
> Fixes loading of viewState from localStorage into URL

- site/AMI.md
- site/how-it-works.md
- site/installing.md
@2opremio I've added the AMI doc to the main docs.  
Place the doc after installing.md and also changed the title, so we'll need to update the guide as well. 
Let me know if there is anything else we need to add in here. 
(Also modified an instance of the weave token. )
> Add AMI docs into main docs, modified weave token instructions in one place

- site/installing.md
> Update install docs

- client/app/scripts/charts/nodes-grid.js
- client/app/scripts/components/node-details/node-details-table-row.js
Fixes #1754.
The click event target is now used instead of the row DOM element.
> Fix the click origin of the details panel in the table mode

- vendor/github.com/iovisor/gobpf/elf/elf.go
- vendor/github.com/iovisor/gobpf/elf/include/bpf.h
- vendor/github.com/iovisor/gobpf/elf/module.go
- vendor/github.com/iovisor/gobpf/elf/module_unsupported.go
- vendor/github.com/weaveworks/tcptracer-bpf/pkg/tracer/tracer.go
- vendor/manifest
It will help to get missing kretprobe events during the ebpf tracker
initialization and missing connect & accept events, specially visible on
single-cores:
- https://github.com/weaveworks/tcptracer-bpf/pull/36
- https://github.com/iovisor/gobpf/pull/39
It makes use of a Linux patch that should be in Linux >= 4.12
(unreleased yet): https://github.com/iovisor/bcc/issues/1072#issuecomment-289777787
It falls back gracefully on current/older Linux kernels.
The new gobpf vendoring also includes other small fixes such as error
handling.
> vendor: update gobpf and tcptracer-bpf

- app/multitenant/consul_client.go
- probe/endpoint/procspy/spy.go
- report/topology.go
Anonymous fields make any methods on the inner object visible on the outer, so they should only be used when the outer is-a inner.
I wanted to make this change after spending several hours puzzled why the code ended up in a particular method that didn't have anything to do with what it was being called upon.
To create this PR I looked at every `struct` in the Scope codebase, apart from unit tests.  There are very few anonymous fields overall, with some such as `Mutex` correctly used.  In a couple of cases I gave the benefit of the doubt.
> Make various anonymous fields named

- site/ami.md
@2opremio missed creating your own AMI anchor tag
> missed an anchor

- client/app/scripts/components/view-mode-selector.js
- client/app/styles/_base.scss
Fixes #2396.
* Made a bunch of selector components `white-space: nowrap` to prevent ugly wrapping
* Added a *@media* query to hide view mode selector labels when viewport is shrunk, showing only icons
* Added a tooltip info to the view mode selector, which is especially important when the labels are gone
> Made view mode selector responsive

- client/app/scripts/charts/node-shape-stack.js
- client/app/scripts/charts/node-shapes.js
- client/app/styles/_base.scss
- client/app/styles/_contrast-overrides.scss
- client/app/styles/_variables.scss
Fixes #2429.
Instead of drawing one shape with both fill and stroke for the highlight, the same shape is rendered twice with slightly different radii, no fill and a very thick stroke which ensures uniform highlight thickness around the shape. It's a slightly hacky solution (especially with adjusting the colors & opacities), but it seems to work well. Thanks @foot for the idea!
~~Instead of a stretched highlight shape, a regular highlight is drawn around the bottommost layer of the stack. On top of that, the whole stack is slightly skewed to the left for a more 3D feel - not sure if we want that change though, my initial motivation was to make the highlight look better, but now I think the whole stack looks better when skewed (even when not highlighted).~~
Turns out that using the border …
> Fix node highlight for all shapes

- app/multitenant/s3_client.go
We do exactly this in https://github.com/weaveworks/cortex/blob/master/chunk/aws_storage_client.go#L335
Fixes #2018.
> close s3 response body to prevent leaks

- probe/appclient/app_client_internal_test.go
- probe/awsecs/reporter.go
- probe/probe_internal_test.go
- probe/topology_tagger.go
- render/detailed/node.go
- render/detailed/parents.go
- render/detailed/summary.go
- render/ecs.go
- render/pod.go
- report/report.go
This is a series of changes meant to make it easier to modify the list of topologies
by inferring information or using iterative APIs instead of explicitly referencing each
topology by name, as well as some misc other refactoring. A short list:
* Explicitly list topology fields in report.Report methods less often
* Refactor how information is looked up in render/detailed so that common functionality to all topologies is not repeated
* Refactor Map2Parent, MapContainer2Pod and MapContainer2Task into one function
Much more could be done, but this is a reasonable first pass.
As a side note, I found it very confusing
that the codebase refers to both report topologies (Process, Container, etc) and in-UI topologies (aka views,
eg. container, container by image, container by dns name) as …
> Reduce the number of places topologies are explicitly listed

- prog/app.go
- prog/main.go
- prog/probe.go
...while keeping other weave integrations, by setting `--weave.hostname=`
Addresses a suggestion in #1550.
> allow disabling of weaveDNS advertising/lookup

- scope
when `--app.http.address` is specified. Instead just tell the user that scope is reachable where they said.
Also, complain when the address is specified on D4M since there are a bunch of hard-coded port 4040 in place for that.
Fixes #1190.
I did consider a) extracting the address argument and constructing a more precise "reachable at" message, and b) respecting the address on D4M, but decided against both on cost/benefit grounds.
> don't lie about reachable address

- app/api_topologies.go
- app/api_topologies_test.go
- probe/docker/reporter.go
- probe/docker/tagger.go
- render/detailed/parents.go
- render/detailed/summary.go
- render/selectors.go
- render/swarm.go
- report/id.go
- report/report.go
This is done in a very hacky way - we look at the container labels to identify the parent service,
and that's it. We can't see services that aren't running on that machine, and the only service info
we have is the name.
> Add very basic Docker Swarm service topology

- scope
This allows alternate scope images to be used, and mirrors the option available for weave net.
> scope script: Allow 'user' part of image name to be given by DOCKERHUB_USER env var

- app/router.go
- probe/appclient/report_publisher.go
- report/marshal_test.go
We want the middle ground between a small compression size, a fast
compression time and a fast decompression time.
Tests suggest that the default compression level is better than the
maximum compression level: although the reports are 4% bigger and
decompress slower, they compress 33% faster.
See discussion on https://github.com/weaveworks/scope/issues/1457#issuecomment-293288682
> gzip: change compression level to the default

- client/app/scripts/components/zoom-wrapper.js
This was confusing in demos at KubeCon and DockerCon this year, as
clicking on nodes kept the UI zooming in.
Plus, when asked, users had no idea that double-click meant zoom in.
Fixes weaveworks/service-ui#453
> Remove zoom on double-click

- app/api_topologies_test.go
- common/xfer/plugin_spec.go
- extras/generate_latest_map
- report/counters.go
- report/counters_internal_test.go
- report/edge_metadatas.go
- report/edge_metadatas_internal_test.go
- report/latest_map_generated.go
- report/map_helpers.go
- report/marshal.go
- report/node_set.go
- report/sets.go
There is a big performance improvement from sending the data directly rather than creating an intermediate data structure.
Before:
```
vagrant-ubuntu-wily-64:~/.../weaveworks/scope/report$ go test -cpu=1 -run=EncodeSpeed
ok  	github.com/weaveworks/scope/report	3.978s
ok  	github.com/weaveworks/scope/report	4.035s
ok  	github.com/weaveworks/scope/report	3.945s
ok  	github.com/weaveworks/scope/report	4.184s
```
After:
```
ok  	github.com/weaveworks/scope/report	1.951s
ok  	github.com/weaveworks/scope/report	1.934s
ok  	github.com/weaveworks/scope/report	1.971s
ok  	github.com/weaveworks/scope/report	1.970s
```
1.934/3.945=49%
Test program:
```
func TestEncodeSpeed(t *testing.T) {
b, _ := ioutil.ReadFile("fixed.msgpack")
r := Report{}
d := codec.NewDecoderBytes(b, &codec.MsgpackHandle{}) …
```
> Msgpack perf: write psMap out directly

- app/api_topologies.go
- probe/docker/reporter.go
- probe/docker/tagger.go
- render/filters.go
We have to introduce the kinda hacky concept of a 'No Stack' stack
to reconcile it with the idea of a 'default' k8s namespace. This is important
because swarm services without a stack don't have the same docker labels as ones that do.
Curiously, they still have what appears to be a stack name 'prefix' on their names,
but I can't isolate that name anywhere easily so they'll just have to make do.
I basically copy-pasted updateFilters to make this work, todo go back and refactor
to not duplicate 90% of the code.
> Add docker swarm Stack selector ala k8s namespace selector

- client/app/scripts/components/app.js
- client/app/scripts/components/help-panel.js
- client/app/styles/_base.scss
Fixes #2470 and introduces the following keyboard shortcuts:
<kbd>g</kbd> - switch to graph layout
<kbd>t</kbd> - switch to table layout
<kbd>r</kbd> - switch to resource layout
All of them do nothing if we're already in that layout (as toggling doesn't make sense now that there are 3 different modes).
> Fixed view mode switching keyboard shortcuts

- site/plugins.md
This PR adds documentation for the primary data structures used to create a report. It will be of great help to developers that want to build their plugins.
I did this work on the website. Do you want me to add the same information on https://github.com/weaveworks/scope/blob/master/examples/plugins/README.md?
Relevant to https://github.com/weaveworks/scope/issues/1963
/cc @2opremio @abuehrle
> Report data structure documentation

- Makefile
Fixes #2269 ("inspired" by https://github.com/weaveworks/service-conf/pull/796 )
> only lint files in git ls-files, not .git/*

- README.md
Currently there is no mention of plugins on the main Scope project README. One has to dig to even find out that a plugin mechanism exists. This commit adds a section highlighting that plugins exist and points to the documentation for writing plugins.
> Add plugin mention to scope readme

- site/features.md
- site/how-it-works.md
- site/installing.md
- site/introducing.md
Jekyll doesn't tolerate this, and it's generally cosidered a cleaner
style, we've had a bit of mixed style and this makes it consistent.
> Consisten spacing in Markdown headings

- client/app/scripts/actions/app-actions.js
- client/app/scripts/charts/node.js
- client/app/scripts/charts/nodes-grid.js
- client/app/scripts/components/app.js
- client/app/scripts/components/footer.js
- client/app/scripts/components/metric-selector-item.js
- client/app/scripts/components/node-details/node-details-relatives-link.js
- client/app/scripts/components/node-details/node-details-table-node-link.js
- client/app/scripts/components/search.js
- client/app/scripts/components/topologies.js
- client/app/scripts/components/topology-options.js
- client/app/scripts/components/view-mode-selector.js
- client/app/scripts/constants/key-codes.js
- client/app/scripts/selectors/node-metric.js
- client/app/scripts/selectors/topology.js
- client/app/scripts/utils/tracking-utils.js
Addresses #2460 by making use of Service UI's configured `window.mixpanel` variable directly.
* `scope.layout.refresh.click`
* `scope.layout.selector.click`
* `scope.layout.selector.keypress`
* `scope.metric.selector.pin.click`
* `scope.metric.selector.pin.next.keypress`
* `scope.metric.selector.pin.previous.keypress`
* `scope.metric.selector.unpin.click`
* `scope.metric.selector.unpin.keypress`
* `scope.node.click`
* `scope.node.relative.click`
* `scope.search.query.change`
* `scope.search.query.pin`
* `scope.topology.option.click`
* `scope.topology.selector.click`
Most of them have the active topology and view mode (layout) props attached to them to have some context of where the events are coming from. I checked it on the mixpanel dashboard and it seems to work nicely!
* Replaced the …
> Added mixpanel tracking for some basic events

- client/app/scripts/components/app.js
- client/app/scripts/components/nodes.js
- client/app/styles/_base.scss
Fixes #2472 by calculating the viewport dimensions from the `scope-app` div bounding rectangle instead of `window.width` & `window.height` (the changes were pulled out from PR #2420).
> Calculate viewport dimensions from the scope-app div

- probe/process/walker_linux.go
- vendor/github.com/weaveworks/common/fs/fs.go
- vendor/github.com/weaveworks/common/fs/readdircount_linux_amd64.go
- vendor/github.com/weaveworks/common/fs/readdircount_unsupported.go
- vendor/github.com/weaveworks/common/middleware/http_auth.go
- vendor/github.com/weaveworks/common/test/fs/fs.go
- vendor/github.com/weaveworks/common/tools/runner/runner.go
- vendor/github.com/weaveworks/common/user/grpc.go
- vendor/github.com/weaveworks/common/user/http.go
- vendor/github.com/weaveworks/common/user/id.go
- vendor/manifest
Golang's ReadDirNames is expensive and better avoided when we don't care
about the names.
See discussion in https://github.com/weaveworks/scope/issues/1011
I tested the performances by looking at the Scope cpu usage with `top -d 10`:
- on master versus this branch
- on my laptop with additional processes versus on my laptop with [200 additional test processes with 500 open files each](https://gist.github.com/alban/009763ef2794f5733aa5463e94f8cdba)
| Scope cpu usage | without test processes | with 200 test processes |
| :-----: | :-----: | -----: |
| master branch | 15% | 24% |
| with this PR | 14% | 20% |
TODO:
> proc walker: optimize open file counter

- client/app/scripts/components/topology-options.js
This can happen when a new option is introduced while using an old URL
state.
Fixes #2489
> Adds a default list to topology options if previous options are missing

- site/.project
- site/ami.md
- site/building.md
- site/features.md
- site/how-it-works.md
- site/installing.md
- site/introducing.md
- site/plugins.md
Added `search_type: Documentation` as a first step for search in the new site.  This variable groups all documentation type content together. 
@2opremio please check that I haven't gaffe'ed anything.
> Please Review: added search type variable

- client/app/scripts/decorators/node.js
- client/app/scripts/selectors/resource-view/layout.js
> Made the displayed metric info reflect the adjustment in resource boxes width.
Taken as a quickfix from #2420 - because of #2389, the resource consumption reported by the backend would sometimes be greater for the children nodes than for their parents which doesn't make sense and is especially *a stab in the eye* with our resource view layout.
Before:
Now:
> Consistent resource consumption info in the resource view

- app/api_topologies.go
This should never have been added. The IsNamespace filter will always return false for these nodes.
It isn't even clear what this filter would mean, even if implemented, since those nodes don't map to a single
container and therefore not to a single namespace.
This bug was introduced in https://github.com/weaveworks/scope/pull/2285 and is very problematic
because it means the default view on those topologies is blank if the 'default' k8s namespace is present.
> api_topologies: Don't put namespace filters on containers-by-dns/image

- app/multitenant/billing_emitter.go
- vendor/github.com/weaveworks/billing-client/event.go
- vendor/manifest
This is intended to give some insights into adoption among weave cloud users
> Add weavenet metrics to billing

- probe/awsecs/client.go
Leftover from #2514 
Part of #2508
> Avoid null dereferences in ECS client (encore)

- client/app/scripts/charts/edge-container.js
- client/app/scripts/charts/nodes-layout.js
- client/app/scripts/constants/styles.js
Fixes #2328 in two steps:
* For edges that are not loops, we're now adding two new endpoints instead of overriding the existing ones, so that the edges enter the nodes in a more *tangential* manner as opposed to having a high curvature.
* Also increased the layout engine's perceived `NODE_SIZE_FACTOR` slightly to the same effect.
Before:
Now:
> Fix arrow heads positioning

- site/installing.md
> Update install documents (again)

- site/plugins.md
The ```multicolumn-table``` feature was added in January (https://github.com/weaveworks/scope/pull/2109) but lacks documentation. This rectifies that.
> Add multicolumn-table documentation

- render/theinternet.go
Currently, `The Internet` in Scope UI only excludes a couple of hostname patterns for AWS and GCE. I've added a handful of common Azure services as a temporary workaround until user-defined hostname patterns are implemented in #1876 so they don't get globbed into the `The Internet` bucket.
This is my first PR into scope, so please let me know if you'd like me to change anything!
> Breaking out some Azure-based services from "The Internet" (#1876)

- app/api_topologies.go
There is nothing special about the "default" namespace, and selecting it by default means we only show a partial view of the system, which is hard to spot, especially for novice users.
> show all namespaces by default

- probe/endpoint/ebpf.go
- vendor/github.com/iovisor/gobpf/elf/elf.go
- vendor/github.com/iovisor/gobpf/elf/elf_unsupported.go
- vendor/github.com/iovisor/gobpf/elf/perf.go
- vendor/github.com/iovisor/gobpf/elf/table.go
- vendor/github.com/weaveworks/tcptracer-bpf/pkg/tracer/tracer.go
- vendor/github.com/weaveworks/tcptracer-bpf/pkg/tracer/tracer_unsupported.go
- vendor/github.com/weaveworks/tcptracer-bpf/tests/tracer.go
- vendor/manifest
This adds fixes in the perf map that receives the tcp events from the ebpf probes:
- gobpf: use the correct timestamp function instead of assuming the timestamp is at offset zero in the struct
- gobpf: fix loop on events that could drop events
- gobpf: add a go channel to notify lost events
- gobpf: make the size of the ring buffers configurable instead of using 8 page (32KB)
- tcptracer-bpf: change the size of the ring buffer "maps/tcp_event_ipv4" to 256 pages (1MB)
- tcptracer-bpf: use the go channel to notify lost events
- scope: add a callback on lost events: log the error and stop the ebpf tracker correctly. So if it ever happens, we will know about it.
This is to address the address the following failure that happened a few weeks ago:
```
<probe> ERRO: 2017/04/13 07:34:17.299127 tcp …
```
> ebpf connection tracker: perf map fixes

- probe/kubernetes/client.go
Supersedes https://github.com/weaveworks/scope/pull/2451
> Re-enable pod shortcut reports

- integration/350_container_to_container_edge_no_weave_test.sh
- probe/endpoint/connection_tracker.go
Fixes #2494 
Regression introduced by https://github.com/weaveworks/scope/pull/2135
> Let conntrack track non-NATed short-lived connections

- app/api_topologies.go
- probe/kubernetes/client.go
- probe/kubernetes/daemonset.go
- probe/kubernetes/deployment.go
- probe/kubernetes/replica_set.go
- probe/kubernetes/replication_controller.go
- probe/kubernetes/reporter.go
- probe/kubernetes/reporter_test.go
- render/detailed/parents.go
- render/detailed/summary.go
- render/pod.go
- render/selectors.go
- report/id.go
- report/report.go
Fixes https://github.com/weaveworks/scope/issues/1444
This adds collection of daemonset info to the probe,
and two new views to the app. One showing only daemonsets,
one showing deployments + daemonsets.
This is too many views (see discussion in #1444), but was useful for initial debugging - we can remove the daemonsets view before merging.
We need to decide how we are going to present this new 'combined view' to the user in a way that makes it obvious what's going on. For now I've labelled it 'Replica groups' but that's not good enough.
> Add daemonsets

- probe/kubernetes/client.go
> Guard against null DaemonSet store

- report/counters.go
- report/edge_metadatas.go
- report/map_helpers.go
- report/node_set.go
- report/sets.go
Refactor various piece of code that use `ps.Map` to use the functions in map_helpers.go.
> Use map helpers

- report/node_set.go
- report/node_set_test.go
It's unnecessary, and none of the other ps.Map derived structures do it.
I have tested this locally by looping through 30s of production reports - I couldn't spot any abnormalities in the UI.
> optimise: don't sort in NodeSet.ForEach

- integration/301_internet_edge_without_ebpf_test.sh
- integration/310_container_to_container_edge_test.sh
- integration/311_container_to_container_edge_without_ebpf_test.sh
- integration/312_container_to_container_edge_same_netns_test.sh
- integration/313_container_to_container_edge_with_ebpf_proc_fallback_test.sh
- integration/314_container_accept_before_kretprobe_test.sh
- prog/main.go
Fixes #2441
We already had an integration test for the proc fallback (313), so I just adjusted the ebpf flag according to its default value and changed tests explicitly testing ebpf-tracking to explicitly test tracking without ebpf.
> Enable eBPF tracking by default

- probe/endpoint/connection_tracker.go
- probe/endpoint/procspy/fixture.go
- probe/endpoint/procspy/spy.go
- probe/endpoint/procspy/spy_darwin.go
- probe/endpoint/procspy/spy_linux.go
- probe/endpoint/procspy/spy_linux_internal_test.go
Previously we were doing the reading even though we weren't looking at the result.
> don't read all of /proc when probe.proc.spy=false

- render/memoise.go
- render/render.go
Execute reducer branches in parallel.
This reduces the time it takes to fetch topologies. Using the same test methodology is as in https://github.com/weaveworks/scope/pull/2559#issuecomment-306142823, running on my feeble laptop...
|            |  before | after |
| ---------- | --- | --- |
| processes  | 0.3 | 0.3 |
| containers | 1.8 | 1.6 |
| pods       | 1.5 | 1.3 |
| services   | 1.4 | 1.2 |
| hosts      | 1.6 | 1.2 |
(all results in seconds)
> parallel reduce

- Makefile
It seems that on my OS the passed param to find gets expanded early and
thus the command
$(shell find ./ -path ./vendor -prune -o -type f -name *.go)
results in
./test.go ./vendor
instead of including all the go files from subdirs. Quoting helps.
> Fix incomplete dependencies for `make scope/prog`

- probe/kubernetes/client.go
> Back off upon errored kubernetes api requests

- Makefile
- backend/Dockerfile
- prog/main_test.go
- tools/test
Is excluded from tests and does not compile.
> Fix prog/main_test.go

- client/README.md
- client/package.json
- client/server.js
also updated documentation for minimum Node.js version required.
Edit: also explicitly set hosts to `localhost` for expressjs servers to make it easier to click on the logged links in case of ipv6 default address.
> es6ify server.js and include in eslint

- app/api_report_test.go
- app/api_topologies_test.go
- app/router.go
- common/xfer/constants.go
- prog/app.go
The first capability is whether there is report persistence, needed to conditionally enable time controls in the UI  ( https://github.com/weaveworks/scope/pull/2524 )
> Add app capabilities to /api endpoint

- probe/kubernetes/reporter.go
It's a number.
This enables numeric sorting of Observed Gen in the table mode of the Deployment and Replicaset views.
> correct type for "Observed Gen."

- probe/appclient/app_client.go
- probe/appclient/multi_client.go
- probe/appclient/multi_client_test.go
> re-target app clients when name resolution changes

- probe/endpoint/connection_tracker.go
- probe/endpoint/nat.go
- probe/endpoint/nat_internal_test.go
- probe/endpoint/reporter.go
- render/detailed/summary.go
- render/process.go
- render/short_lived_connections_test.go
- test/fixture/report_fixture.go
The information is constant and already present in the id, so we can extract it from there.
That reduces the report size and improves report encoding/decoding performance. It should reduce memory usage too and improve report merging performance too.
NB: Probes with this change are incompatible with old apps.
> drop addr and port from Endpoint.Latest map

- client/app/scripts/components/nodes.js
- client/app/scripts/components/search.js
- client/app/scripts/reducers/__tests__/root-test.js
- client/app/scripts/utils/topology-utils.js
Fixes #2592 by making sure the nodes empty message appears only when there are actually no nodes displayed. The `shownNodesSelector` is used to determine the displayed nodes, so with this change, we also get a message when all the nodes have been filtered out by search, so I also added one message for that to the list of possible causes.
> Don't display the empty message when nodes are displayed

- client/app/scripts/charts/nodes-chart-edges.js
- client/app/scripts/charts/nodes-chart-nodes.js
- client/app/scripts/reducers/__tests__/root-test.js
- client/app/scripts/reducers/root.js
- client/app/scripts/selectors/graph-view/decorators.js
- client/app/scripts/utils/layouter-utils.js
A small refactoring PR which gets rid of `highlightedNodeIds`/`highlightedEdgeIds` fields in the global state and uses selectors to calculate them from adjacencies and `mouseOverNodeId`/`mouseOverEdgeId` fields instead.
With this change, all the nodes/edges decorators are now seen as computed properties, either through selectors or through decorators in components. That enables use to move forward with stories like #2432, where we need to deal with more complex logic of node states.
The performance wasn't visibly affected with these changes.
> Moved highlighted nodes/edges info to selectors

- client/app/scripts/actions/app-actions.js
- client/app/scripts/components/footer.js
- client/app/scripts/components/pause-button.js
- client/app/scripts/components/time-travel.js
- client/app/styles/_base.scss
Since Time Travel is currently feature-flagged, we don't want the Pause button to be a part of that component, as that would make it unavailable e.g. in production. Once Time Travel will be exposed to everyone, we might reconsider moving the pause button back there.
Additionally, I changed the name of the flag from `timeline-control` to `time-travel` as it corresponds better to the new naming in the UI.
After this PR is merged, I'd update the Scope version in Service UI to have finally have time travel available for testing in dev environment.
@jpellizzari I'd be curious what your ideas are how we could reconcile the two different state trees that actions are getting depending on the context they're called from (see my `TODO` comment).
> Move pause button back to footer

- probe/endpoint/procspy/proc_linux.go
- probe/endpoint/procspy/spy_linux.go
This will help with #2577 when using `/proc` parsing. Fixing the eBPF connection tracker requeres a separate PR.
> Do not read tcp6 files if TCP version 6 isn't supported

- render/theinternet.go
We hit this code *a lot* during rendering.
I have tested rendering performance against a recent Weave Cloud prod report. Run scope like this:
```
$ prog/scope --mode=app --weave=false --app.collector=file:/tmp/prod-on-dev-report.json
```
and then time the fetching of a topology with
```
$ time curl -so /dev/null http://localhost:4040/api/topology/<topology>
```
and then repeat for other topologies (NB: scope must be restarted in-between in order to defeat memoisation between requests).
Results (all times in seconds):
| topology   | master | branch |
| ------------ | -------- | -------- |
| processes  |   0.14 |   0.11 |
| containers |   0.92 |   0.67 |
| pods       |   0.74 |   0.48 |
| services   |   0.72 |   0.45 |
| hosts      |   0.76 |   0.47 |
So that's a nearly 40% improvement in …
> faster matching of known services

- client/package.json
Pins d3-transition and d3-drag dependencies which were previously
pulled in as deps from d3zoom as version 1.1.0 each. This broke
the zoom feature for `npm start`.
Fixes #2545
> Fix zoom for `npm start`

- CHANGELOG.md
- client/app/scripts/actions/app-actions.js
- client/app/scripts/components/footer.js
- client/app/scripts/components/nodes.js
- client/app/scripts/components/pause-button.js
- client/app/scripts/components/search.js
- client/app/scripts/components/time-travel.js
- client/app/scripts/reducers/__tests__/root-test.js
- client/app/scripts/utils/topology-utils.js
- client/app/styles/_base.scss
- site/installing.md
@rndstr @fbarl @davkal @foot @ekimekim @bowenli @jpellizzari @abuehrle @pidster @errordeveloper @rade Please chip in by testing this release branch in the scenarios below and tick off what you tested afterwards (including your name at the end). Have a look at the CHANGELOG to prioritize your testing.
To make things easier to test I have pushed the image `weaveworks/scope:release-1.5-1667984`:
- ECS Integration
> Release 1.5.0

- client/app/scripts/components/node-details/node-details-table.js
> Fix the table sorting order bug for numerical values

- extras/fixprobe/main.go
- probe/kubernetes/reporter.go
We do this in case that name resolves to something else.
This was done in #2103 for one case; don't see why we wouldn't do the same everywhere.
> Use 127.0.0.1 instead of localhost, more

- render/theinternet.go
This is a follow-up to #2613 and gains another 15% in rendering performance for some topologies (pods), though less for others.
> memoize isKnownServices for improved performance

- probe/host/reporter.go
- report/networks.go
- report/networks_test.go
There is no point in paying attention to them since scope connection tracking only deals in IPv4.
In Weave Cloud Prod, 138 of the 218 local networks in the combined report are IPv6 addresses. That slows down endpoint projection during rendering since that needs to detect whether an address is local. This PR doesn't solve that completely - matching against 80 networks is still expensive - but I have plans for that :)
> Ignore ipv6

- render/container_test.go
- render/theinternet.go
- render/theinternet_test.go
- report/networks.go
- report/networks_test.go
- vendor/github.com/k-sone/critbitgo/LICENSE
- vendor/github.com/k-sone/critbitgo/critbit.go
- vendor/github.com/k-sone/critbitgo/map.go
- vendor/github.com/k-sone/critbitgo/net.go
- vendor/manifest
The rendering code checks whether endpoint IPs are part of cluster-local networks. Due to the prevalence of endpoints - medium sized reports can contain many thousands of endpoints - this is performance critical. Alas the existing code performs the check via a linear scan of a list of networks. That is slow when there are more than a few, which will be the case in the context of k8s, since there the probes register service IPs as local /32 networks.
Here we change representation of the set of networks to a prefix tree (aka trie), which is well-suited for IP network membership checks since networks are in fact a bitstring prefixes.
The specific representation is a crit-bit tree, but that choice was purely based on implementation convenience - the chosen library is the only one I could find …
> fast network membership check

- app/api_topologies.go
- client/app/scripts/components/topology-options.js
* The UI was not correctly interpreting a missing defaultValue value as `''`.
Solution: don't omit the value when it's equal to `''`.
* We replace the none option id `'none'` in the frontend with `''` to avoid several issues
See the individual commits for a detailed breakdown.
Fixes https://github.com/weaveworks/scope/issues/2525
> Fix issues with union types

- render/container.go
- render/host.go
- render/process.go
`ProcessRenderer` was coloring connected nodes because we need that info for rendering details panels. However, the main process topology view renderers depending on `ProcessRenderer` were also doing coloring themselves. For the 'processes' topology that was literally duplicating work. For the 'processes-by-name' topology that was throwing away the process coloring, and then coloring at the name level.
Solution: remove the coloring from the `ProcessRenderer`, thus eliminating the duplicate/thrown-away work, and introduce a `ColorConnectedProcessRenderer` which is only used in places that
populate details panels.
The performance improvement from this is tiny, but the change is worth it for improved clarity alone.
> performance: only color connected once

- probe/endpoint/dns_snooper_linux_amd64.go
> Avoid race conditions in DNSSnooper's cached domains

- integration/100_launch_test.sh
- integration/105_launch_sans_weave_test.sh
- integration/200_clustering_2_test.sh
- integration/205_clustering_sans_weave_2_test.sh
- integration/210_clustering_custom_hostname_2_test.sh
- integration/310_container_to_container_edge_test.sh
- integration/311_container_to_container_edge_without_ebpf_test.sh
- integration/313_container_to_container_edge_with_ebpf_proc_fallback_test.sh
- integration/314_container_accept_before_kretprobe_test.sh
- integration/320_container_edge_cross_host_2_test.sh
- integration/330_process_edge_test.sh
- integration/340_process_edge_across_host_2_test.sh
- integration/410_container_control_test.sh
- integration/config.sh
> make integration tests pass with latest Weave Net release (2.0)

- probe/endpoint/procspy/spy_linux.go
`ProcNet.Next` does not allocate `Connection` structs, for efficiency. Instead it always returns a `*Connection` pointing to the same instance. As a result, any mutations by the caller to struct elements that aren't actually set by `ProcNet.Next`, in particular `Connection.Proc`, are carried across to subsequent calls.
This had hilarious consequences: connections referencing an inode which we hadn't come across during proc walking would be associated with the process corresponding to the last successfully looked up inode.
The fix is to clear out the garbage left over from previous calls.
Fixes #2638.
> ensure connections from /proc/net/tcp{,6} get the right pid

- app/api_topologies.go
- client/app/scripts/charts/node-shapes.js
- client/app/scripts/charts/node.js
- client/app/scripts/utils/node-shape-utils.js
- client/app/scripts/utils/topology-utils.js
- probe/kubernetes/daemonset.go
- probe/kubernetes/deployment.go
- probe/kubernetes/reporter.go
- render/detailed/summary.go
- render/ecs.go
- render/filters.go
- render/pod.go
- render/swarm.go
- report/report.go
This adds a 'combined' kubernetes view that shows each pod at the 'highest level of abstraction', as follows:
* Any daemonsets the pod is in
* Any deployments the pod is in
* Any replica-sets the pod is in that do not map to a deployment
* If none of the above, the bare pod itself
Along the way, it fixes https://github.com/weaveworks/scope/issues/2525 by removing the omitempty for the default value, further generalises render.Map2Parent, and introduces a new Renderer type for combining a set of nodes with a set containing the same nodes with more information, but with the output set of nodes only being the original set (but with the extra information), unlike Reduce which takes a union.
Still to do:
* How does the table view work in this setup?
* We want to assign shapes to the different …
> add k8s combined view

- app/weave.go
- probe/docker/registry.go
- probe/overlay/weave.go
- probe/overlay/weave_test.go
- prog/main.go
- prog/probe.go
Changed default for flag `-app.docker` to use the DOCKER_* env variables
instead of hardcoded /var/run/docker.sock; uses docker's default if
no DOCKER_HOST defined, for both probe and app.
Fixes #1975
---
This is technically a breaking change (if someone had DOCKER_HOST set before and not provided an alternate location in `-app.docker`, it will now take a different location); albeit one I would assume impact is very low. Still, how do we handle this?
> Honor DOCKER_* env variables in probe and app

- app/api_topologies.go
- render/container.go
- render/filters.go
- render/process.go
The filtering of endpoints causes some connections to get missed for non-eBPF-tracked connections. Furthermore, the filtering of endpoints is entirely pointless when the probes run eBPF since the filters just pass through eBPF-tracked endpoints (for good reason too; because otherwise some connections would be missed). So in that case it is just costing CPU and removing it actually improves performance.
Note that removing the filtering does not result in over-counting connections since that is done by source ip:port pairs.
Fixes #2551.
Fixes #2558.
> do not filter endpoints by procspied/ebpf in renderers

- site/installing.md
This has been tested on OpenShift Orgin v1.4.1 (`oc cluster up --version=v1.4.1 --skip-registry-check`),
(using latest builds of `oc` [412b5d6] command and Docker for Mac [v17.06.0-rc5-ce-mac16]).
> Publish updated OpenShift instructions (close #2485)

- app/api_topologies.go
This was always temporary until we could search for type via the search box instead,
since it resulted in too much clutter / didn't seem a useful use-case.
As it turns out, searching like this was already possible.
Related to #2620
> Remove type filter in controllers view

- render/process.go
This eliminates the worst effects of #2665.
It is imperfect because it
- simply drops all connections that originate from the same endpoint, if there is more than one. Not only will this eliminate the problematic connections (i.e. those where it is indeed the case that the same source ip+port was used by different processes), but also those where the source ip+port was used multiple times by the same process. That is unlikely for ephemeral ports (the odds of the *same* process getting given a particular ephemeral port more than once in a short period of time are much lower than the odds of *any two* processes getting given a particular ephemeral port in a short period of time, which is the problematic case we are wanting to eliminate here), but a dead certainty when the process is …
> ignore endpoints with >1 adjacency in process rendering

- client/app/scripts/components/node-details/node-details-table-row.js
- client/app/scripts/utils/array-utils.js
> Show multiple relatives in the nodes-grid view

- client/app/scripts/constants/styles.js
> Prevents 6 digit pids from being truncated in details panel/table mode

- render/host.go
The same container image may be in use on multiple hosts. The latest-map `HostNodeID` of a node in the `ContainerImage` topology is therefore meaningless - it gets set to whatever host reported that image last in the time window covered by the report. Hence using it as a basis for mapping to hosts, as we did, a) fails to associate images with all the right hosts (hence they are missing from the host details panel), and b) causes that association to change semi-randomly (hence the list in the details panel is unstable).
By contrast, the host topology parents of container image nodes is the complete set of all hosts the image is used on. So making that the basis for mapping fixes the problem.
The same technique - mapping based on host parents rather than latest-map `HostNodeID` - also works …
> correct determination of a host's container images

- render/detailed/node.go
- render/detailed/node_test.go
The figure is inaccurate since it counts containers across all hosts. Getting the count correct is non-trivial, so it's better to not show the figure at all.
NB: the count still shows up on mouse-over of the link, but that is defensible and not (very) confusing since the link represents the image, not the image on a particular host, and it's the same count that show up as the minor label in the container images view.
Fixes #2681.
> don't show container count in host detail panel image list

- render/pod.go
Thankfully we only ever set it to UnmanagedID right now, so no user-facing bug.
> render/pod: Fix a typo in Map2Parent where UnmanagedID will always be used for noParentsPseudoID

- client/app/scripts/components/node-details/node-details-table.js
Having to toggle a +1 feels weird while that +1 takes up
the same vertical space as displaying that row.
---
Just something small I came across.
Behavior on default (or configured) row limit equals 5:
Items | Display,Overflow | (Alternative)
-|-|-
4|4,0|4,0
5|5,0|5,0
6|6,0|4,+2
7|5,+2|4,+3
8|5,+3|4,+4
Current implementation shows generally $limit rows, alternative would be if you want a max row (including toggle) to not exceed $limit.
> Show table overflow only if limit exceeded by 2+

- integration/330_process_edge_test.sh
- integration/340_process_edge_across_host_2_test.sh
There really should be two variants - with and without eBPF - but the latter is broken due to #2689.
> don't use eBPF in a couple of tests

- client/package.json
Fixes 
```
mv: cannot stat 'weave-scope-1.5.0.tgz': No such file or directory
```
> Yarn prefixes version with `v` when packing

- client/app/scripts/charts/__tests__/node-layout-test.js
- client/app/scripts/charts/nodes-layout.js
- client/app/scripts/utils/__tests__/math-utils-test.js
- client/app/scripts/utils/math-utils.js
Fixes #2261 by introducing an additional test at the end of the layout function to see if any the nodes would overlap - if they would, the whole layout is refreshed by calling the render engine with a clean cache.
*Note*: The `layoutSingleNodes` has just been moved to the top, nothing was changed there.
> Last line of defense against overlapping nodes in graph layout

- probe/endpoint/ebpf.go
- probe/endpoint/ebpf_test.go
- vendor/github.com/weaveworks/tcptracer-bpf/pkg/tracer/tracer.go
- vendor/github.com/weaveworks/tcptracer-bpf/pkg/tracer/tracer_unsupported.go
- vendor/github.com/weaveworks/tcptracer-bpf/tcptracer-bpf.c
- vendor/github.com/weaveworks/tcptracer-bpf/tests/tracer.go
- vendor/manifest
We defer starting the ebpf tracer until we've set the global var which is referenced by the callback functions. Previously the var could be unset when the callbacks are invoked, resulting in a segfault.
...and then we eliminate the global var altogether :)
Fixes #2687.
> fix ebpf init race segfault

- probe/endpoint/connection_tracker.go
- probe/endpoint/ebpf.go
- probe/endpoint/ebpf_test.go
a bunch of refactors, and race condition fixes.
Best reviewed commit-by-commit.
> EbpfTracker refactoring / cleanup

- client/app/scripts/reducers/__tests__/root-test.js
- client/app/scripts/reducers/root.js
- client/app/scripts/utils/topology-utils.js
If the scope-app API unexpectedly restarts, it has no report
at hand (until it gets one from the probe) and sends node
count 0 to the frontend for all topologies. Once the report
arrives, it will send the proper count.
What happened was the frontend did hide Processes for a short
time till the node count recovered. This moved the topology
selection to the always visible Containers (hide_if_empty == false)
while keeping the graph as is.
Once the node count recovers, Processes comes back but the
selection is still at Containers.
We now keep the selected topology visible at all time even if
the API returns a node count of 0. This recovers nicely when
the correct node counts come in. Once the user selects a different
topology while and a backend response arrives, it disappears.
Fixes #2646
> Keep topology nav visible if selected

- integration/331_process_edge_without_ebpf_test.sh
- integration/341_process_edge_across_host_without_ebpf_2_test.sh
- probe/endpoint/ebpf.go
- probe/endpoint/ebpf_test.go
...when initialising eBPF-based connection tracking.
See commit comments for details.
Fixes #2689.
Fixes #2700.
Obsoletes #2674.
> don't miss, or fail to forget, initial connections

- probe/kubernetes/reporter.go
- probe/kubernetes/reporter_test.go
- prog/main.go
- prog/probe.go
We can get the node name via the downward api, if the Scope probe is run as a pod. This needs to be done in the yaml.
> Use Kubernetes node name to filter pods if possible

- client/app/scripts/reducers/__tests__/root-test.js
- client/app/scripts/reducers/root.js
- client/app/scripts/utils/topology-utils.js
Follow-up to 21a0093c but also displays parent topology if
an empty sub_topology is selected.
> Keep topo nav visible if subnav selected

- client/package.json
The package version is irrelevant for the build process
and is not read anywhere.
The package is not published and causes confusion if the
bump is forgotten.
> Set package.json version to 0.0.0

- client/app/scripts/actions/app-actions.js
- client/app/scripts/reducers/root.js
- render/detailed/topology_diff.go
- render/detailed/topology_diff_test.go
When the scope-app restarts, it no longer has a
reference to the previous node set. Therefore,
the delta update adds *all* nodes but does not
remove legacy ones.
`reset==true` tells the frontend to start fresh.
Fixes #2708
> Reset nodes in frontend when scope-app restarted

- common/weave/client.go
- common/weave/client_test.go
- probe/overlay/weave.go
- probe/overlay/weave_test.go
- test/weave/mock.go
Instead of using Docker, because after Weave Net 2.0 there are no proxy nor
plugin containers.
This has the drawback of not detecting the plugin/proxy in systems running
Weave Net < 2.0 , but I think we can live with it.
Fixes #2634
> Gather Weave Net plugin and proxy info from report

- render/detailed/summary.go
This also fixes a bug where k8s controller nodes would show up as 'Deployment of' without any number
Fixes #2722
> render: In minor labels, display '0 things' instead of blank if zero things present

- client/app/scripts/actions/app-actions.js
- client/app/scripts/components/footer.js
> Fix New Version notification not showing

- probe/kubernetes/client.go
- probe/kubernetes/cronjob.go
- probe/kubernetes/deployment.go
- probe/kubernetes/reporter.go
- probe/kubernetes/reporter_test.go
- probe/kubernetes/statefulset.go
- render/detailed/parents.go
- render/detailed/summary.go
- render/pod.go
- render/selectors.go
- report/id.go
- report/report.go
Fixes #2239. Fixes #2571.
Most basic info is in metadata. Future work:
* Map statefulset to its associated service (probably as a parent)
* Add a control to suspend cronjobs
> kubernetes: Add StatefulSets and CronJobs

- app/multitenant/aws_collector.go
Fixes #2345 
I am intentionally not backing off when writing to Memcached nor NATS. The first one is an optimization and the second one is just used for shortcut reports (not essential).
I tried to use https://github.com/weaveworks/common/blob/master/backoff/backoff.go but it's not suitable for this usecase (it doesn't forward errors and doesn't accept retry limits).
> Back off when writing to Dynamo and S3

- scope
...so it can be used to supply the likes of `--restart=...`.
> only pass WEAVESCOPE_DOCKER_ARGS to actual probe/app start

- client/app/scripts/charts/nodes-layout.js
> Fix Pods number in graph not updating (minor label)

- Makefile
When you run the client locally with `yarn start` and modify the
app/probe code you don't want to compile the client on `make prog/scope`.
This allows you to do `SCOPE_SKIP_UI_ASSETS=true make prog/scope` to
only build the scope binary.
---
Is there a place I should document this?
> Allows to skip client build when doing make prog/scope

- Makefile
- backend/Dockerfile
- extras/example/app/app.py
- extras/example/client/client.py
- extras/example/echo/echo.py
- extras/example/trace_app/app.py
- tools/build/golang/Dockerfile
- tools/circle.yml
- tools/config_management/README.md
- tools/config_management/group_vars/all
- tools/config_management/roles/dev-tools/files/apt-daily.timer.conf
- tools/config_management/roles/dev-tools/tasks/main.yml
- tools/config_management/roles/docker-configuration/files/docker.conf
- tools/config_management/roles/docker-from-docker-ce-repo/tasks/debian.yml
- tools/config_management/roles/docker-from-docker-ce-repo/tasks/main.yml
- tools/config_management/roles/docker-from-docker-ce-repo/tasks/redhat.yml
- tools/config_management/roles/docker-from-get.docker.com/tasks/debian.yml
- tools/config_management/roles/weave-net-utilities/tasks/main.yml
- tools/dependencies/cross_versions.py
- tools/dependencies/list_versions.py
- tools/image-tag
- tools/integration/config.sh
- tools/lint
- tools/sched
- tools/scheduler/main.py
- tools/test
On master, just after `make`:
```
$ time make tests
real	1m18.575s
```
On this branch:
```
$ time make tests
real	1m1.074s
```
Note this relies on https://github.com/weaveworks/build-tools/pull/103
> Pass build tags to unit tests

- probe/appclient/multi_client.go
We don't need to copy from the reader when publishing to just one destination.
> optimisation: don't copy report stream unnecessarily

- prog/main.go
The figure is based on our experience of running scope probes in production systems. Below this we see a lot of "conntrack stderr:WARNING: We have hit ENOBUFS! We are losing events."
There is no downside to a larger buffer size other than, presumably, higher memory use, but since scope probes typically weigh in at >100M RSS, adding a few extra M bufferspace is hardly a concern.
> increase default conntrack buffer size

- probe/appclient/app_client.go
- probe/appclient/multi_client.go
- probe/appclient/multi_client_test.go
- probe/appclient/report_publisher.go
- probe/probe_internal_test.go
so when there is backpressure in publishing reports, drop shortcut reports in preference to full reports, and drop old full reports in preference to new full reports.
Fixes #2738.
> new full reports are more important than old and shortcut reports

- client/app/scripts/actions/app-actions.js
- client/app/scripts/components/nodes-resources.js
- client/app/scripts/components/nodes-resources/node-resources-layer.js
- client/app/scripts/components/nodes-resources/node-resources-metric-box.js
- client/app/scripts/components/zoomable-canvas.js
- client/app/scripts/reducers/root.js
- client/app/styles/_base.scss
Resolves #2663 by making resource view nodes *selectable*. Ideally, we would also zoom into the selected node like we do in the graph view, but the animation there is a bit more involved, so it shouldn't be a blocker for this action that feels very basic.
> Make Resource view nodes clickable

- probe/appclient/app_client.go
...since doing so unnecessarily throttles report sending, to the point where the app is receiving reports so infrequently that often it has no data to show.
The timeout period itself is sufficient to prevent thrashing.
Fixes #2745.
> do not back off on timeouts when sending reports

- probe/appclient/app_client.go
If the app really does take a long time to process reports, it is better not to time out and send it more reports. However, we do want to send at least one report per app.window, otherwise the scope UI
will go blank.
Fixes #2464 (as much as is practically possible)
Note that the timeout also applies to pipe and control traffic. I believe it's a reasonable value for that too.
> maximize report publishing timeout

- probe/kubernetes/cronjob.go
- probe/kubernetes/daemonset.go
- probe/kubernetes/statefulset.go
- render/detailed/summary.go
We can't search for terms with spaces.
Fixes #2752
> k8s: Use 'DaemonSet', 'StatefulSet' etc instead of 'Daemon Set', 'Stateful Set'

- CHANGELOG.md
- site/installing.md
Please test the following and check off when done:
Things to think about
> Release branch for 1.6.0

- client/app/scripts/charts/__tests__/nodes-layout-test.js
- client/app/scripts/utils/__tests__/math-utils-test.js
- client/app/scripts/utils/math-utils.js
> Add test for pods number not updating

- client/app/styles/_base.scss
By mistake, #2703 introduced a change that made *CONFIGURE* button disappear from all the pages in Weave Cloud, instead of just hidding it in configured Scope.
I'm pretty sure @rade wrote somewhere he thinks it's ok to hide the button in Scope to make room for the timeline, but I couldn't find the source to quote him :)
> Hide Service UI Configure button only in Scope

- app/collector.go
- app/multitenant/aws_collector.go
- common/xfer/constants.go
- prog/app.go
since that better captures the intent - the UI doesn't care about reports get stored, but what reports it can retrieve.
Part of #2607.
> rename 'report_persistence' capability to 'historic_reports'

- integration/301_internet_edge_without_ebpf_test.sh
- integration/310_container_to_container_edge_test.sh
- integration/312_container_to_container_edge_same_netns_test.sh
- integration/314_container_accept_before_kretprobe_test.sh
- integration/config.sh
- probe/endpoint/connection_tracker.go
- probe/endpoint/nat_internal_test.go
- probe/endpoint/reporter.go
- render/short_lived_connections_test.go
- test/fixture/report_fixture.go
The app stopped paying attention to these some time ago.
Removing them shrinks reports by 3-10%.
> get rid of endpoint type indicators

- Makefile
- bin/release
...and use that in bin/release, so that we don't build releases with ancient images.
> add 'realclean' make target to clear out container images

- client/app/scripts/utils/web-api-utils.js
Resolves #2769.
In Node Details requests, the query params were added only if the node belonged to the current topology - this PR keeps that logic for topology options but makes sure the timestamp is always added when time travelling, regardless of the topology context.
> Always take timestamp into account in Node Details when time travelling

- client/app/scripts/components/time-travel-timeline.js
- client/app/scripts/utils/math-utils.js
- client/app/styles/_base.scss
- client/app/styles/_variables.scss
Resolves #2770 by shrinking the timeline height for 15px and making the year time tags fade out as hours fade in.
> Shrink timeline height and make years fade out

- probe/kubernetes/reporter.go
- report/networks.go
- report/networks_test.go
This prevents cluttering host.LocalNetworks with lots of /32 addresses. These were unsightly and rather distracting in the UI. They also bloated the report and slowed down server-side rendering.
Fixes #2748.
> synthesise k8s service network from service IPs

- probe/kubernetes/cronjob.go
in which case cj.Status.LastScheduled is nil.
New behaviour is to omit it from the map (and therefore the display) if it has never been scheduled.
Fixes https://github.com/weaveworks/scope/issues/2783
> k8s probe: Fix a panic (nil pointer deref) when a cronjob has never been scheduled

- integration/410_container_control_test.sh
- probe/docker/controls.go
That way PATH is preserved.
Fixes #2550.
> run a normal (rather than login) shell in containers

- client/app/scripts/components/time-travel-timeline.js
- client/app/scripts/utils/zoom-utils.js
Resolves #2768.
If this will behave nicely, consider extending the same logic to #2787.
> Balance timeline zooming sensitivity between Firefox and Chrome

- app/multitenant/sqs_control_router.go
> log sqs messages at 'debug' rather than 'info' level

- client/app/scripts/charts/edge.js
- client/app/scripts/charts/node-shapes.js
- client/app/scripts/utils/__tests__/dom-utils-test.js
- client/app/scripts/utils/dom-utils.js
Replace invalid characters in attribute value; fixes the error
Unescaped '<' not allowed in attributes values
---
Fixes #2534
There are a bunch of other errors when [validating](https://validator.w3.org/#validate_by_upload) the SVG but renderers might be okay with these
element "div" undefined
element "span" undefined
@pidster would you mind opening the following SVG file in the browser where you get the other error and see whether it works now? [weave-cloud-1501839338756.svg.zip](https://github.com/weaveworks/scope/files/1199912/weave-cloud-1501839338756.svg.zip)
> Fix rendering of exported SVG

- client/app/scripts/charts/edge-container.js
- client/app/scripts/charts/edge.js
- client/app/scripts/charts/node-container.js
- client/app/scripts/charts/nodes-chart-elements.js
- client/app/scripts/components/node-details.js
- client/app/scripts/constants/animation.js
- client/app/scripts/selectors/topology.js
- client/app/styles/_base.scss
- client/app/styles/_contrast-overrides.scss
- client/app/styles/_variables.scss
Improves on #2302.
* Added a non-reactive semi-transparent layer between background and foreground nodes and edges in the graph view, removing excessive opacity transitions for individual elements (which also fixes #2431).
* The semi-transparent layer mentioned above is now applied instantly (without a transition) to avoid the glitches and is made a bit lighter (I thought it looked better that way, but that can easily be reverted).
* Made default *spring* animation a bit faster so that it appears smoother and more reactive on Firefox.
* Decreased the graph animation treshold again to make it bearable on Firefox.
> Improve Firefox performance

- client/app/styles/_base.scss
Now supports 88:88:88T88:88:88Z!
Fixes #2804
> Fixes timetravel timestamp input getting truncatated on OSX

- client/app/scripts/actions/app-actions.js
- client/app/scripts/components/time-travel.js
Resolves https://github.com/weaveworks/service-ui/issues/814 by making timeline deconstruction part of the `shutdown()` action, avoiding the attempt to establish new connections.
Also, triggering `resumeTime` action only if previously paused.
> Time Travel: unmount in the shutdown() action

- client/app/scripts/components/node-details.js
Removes empty container that introduce unnecessary margin
> Remove whitespace from empty connection lists

- integration/315_ebpf_restart_test.sh
- integration/config.sh
- probe/endpoint/connection_tracker.go
- probe/endpoint/ebpf.go
- probe/endpoint/ebpf_test.go
- vendor/github.com/weaveworks/tcptracer-bpf/pkg/tracer/tracer.go
- vendor/github.com/weaveworks/tcptracer-bpf/vendor/github.com/iovisor/gobpf/elf/elf.go
- vendor/github.com/weaveworks/tcptracer-bpf/vendor/github.com/iovisor/gobpf/elf/module.go
- vendor/github.com/weaveworks/tcptracer-bpf/vendor/github.com/iovisor/gobpf/elf/perf.go
- vendor/manifest
This is a workaround for https://github.com/weaveworks/scope/issues/2650
Tested manually the following way:
Start Scope with:
```
sudo WEAVESCOPE_DOCKER_ARGS="-e SCOPE_DEBUG_BPF=1" ./scope launch
```    
Simulate EbpfTracker failure with:
```
echo foo | sudo tee /proc/$(pidof scope-probe)/root/var/run/scope/debug-bpf
```
TODO:
> restart eBPF tracking on error

- client/Dockerfile
- client/package.json
- client/yarn.lock
Related to https://github.com/weaveworks/service-ui/issues/930
Builds should be a little faster. It may also be possible to turn off some transpiling features, since Node supports new ES syntax.
> Use Node 8.4 for builds

- client/app/scripts/charts/nodes-chart.js
- client/app/scripts/components/nodes-resources.js
- client/app/scripts/components/time-travel-timeline.js
- client/app/scripts/components/zoomable-canvas.js
- client/app/scripts/constants/naming.js
- client/app/scripts/constants/styles.js
- client/app/scripts/selectors/graph-view/zoom.js
- client/app/scripts/selectors/resource-view/zoom.js
- client/app/scripts/utils/transform-utils.js
- client/app/scripts/utils/zoom-utils.js
- client/app/styles/_base.scss
- client/package.json
Replaces all `d3-zoom` code with our own handlers for zooming/panning events in order to have unified behaviour between all components and across all browsers. Having our own logic also gives us better control over the behaviour.
* Use the same zooming logic in `ZoomableCanvas` as in `TimeTravelTimeline` (fixes #2787).
* Use two modes of translation extent for the nodes canvas:
* `CONTENT_COVERING` - the nodes content bounding box must alwas cover the viewport. This is the case with the resource view, where the content is _sticky_ so that there is never empty space to its left or right.
* `CONTENT_INCLUDED` - this is introduced as a new mode for the nodes graph to fix #2809. Translation is bounded in such a way that a part of the nodes graph bounding box must always be in the viewport.
* …
> Unified zooming sensitivity

- client/app/scripts/components/topology-options.js
- client/app/scripts/reducers/root.js
- client/app/scripts/utils/web-api-utils.js
Resolves #2802.
* Unblock the calls to topology when time travelling, triggering updates of both *topology selector* and *topology options*. Disappearance of the selected option is handled a bit differently between the two:
* The topology selection never changes over time, meaning that e.g. if we select *Processes* and go back in time to the point when that topology wasn't there, we'd still keep it selected but show it as empty. This is to avoid confusion with context switching and also because not sure which one we should default to.
* The namespace selection is taken as an intersection of the full selection and the currently available options. If the intersection is empty, we default to the default option (in case of namespaces, that's the _All namespaces_ option). Here we use the fact …
> Update topologies and namespaces when time travelling

- README.md
The sentence "Easily to find the container using the most CPU or memory for a given host or service" should probably be "*Easily find* the container using the most CPU or memory for a given host or service".
> Fix phrasing in readme

- circle.yml
It doesn't depend on `$DOCKER_USER`. Also, because it was tagged on without a `&&`, it was masking errors in the dockerhub image uploads.
> make circleci ui-upload unconditional

- client/app/scripts/charts/edge-container.js
- client/app/scripts/charts/node-container.js
- client/app/scripts/components/time-travel-timeline.js
- client/app/scripts/constants/animation.js
- client/app/scripts/utils/animation-utils.js
Fixes #2850.
It seems that under some circumstances `isAnimated` prop would turn from _false_ to _true_ after the `waypoints` would be fixed, so `prepareWaypointsForMotion` would never be called given how the conditionals were set, giving an empty `waypointsMap` and consequently an ill-defined spline path for animated edges.
* Simplified and broadened the conditions for `waypointsMap` recalculation to make sure they are called when necessary (but not making excessive calls).
* Made helper functions for `spring` to avoid repeated code.
> Fix edges disappearing in graph mode

- site/ami.md
Depends on https://github.com/weaveworks/integrations/pull/133 (and making the AMIs public after merging)
> Update ECS AMI docs

- prog/app.go
- vendor/github.com/weaveworks/common/aws/config.go
- vendor/github.com/weaveworks/common/http/client/client.go
- vendor/github.com/weaveworks/common/http/http.go
- vendor/github.com/weaveworks/common/logging/logging.go
- vendor/github.com/weaveworks/common/middleware/grpc_logging.go
- vendor/github.com/weaveworks/common/server/server.go
- vendor/github.com/weaveworks/common/user/id.go
- vendor/github.com/weaveworks/common/user/logging.go
- vendor/manifest
This change is parallel to https://github.com/weaveworks/cortex/pull/537 - Scope uses more S3 than Dynamo, but the symptoms and reasoning are the same.
Briefly, we set `MaxIdleConnsPerHost` to `100` to avoid Go killing connections we could otherwise re-use.
> AWS connection keep-alive

- probe/awsecs/client.go
- probe/awsecs/reporter.go
- prog/main.go
- prog/probe.go
As talked with @ekimekim [on slack](https://weave-community.slack.com/archives/C2ND76PAA/p1505756045000138), this PR adds an ECS Cluster Region option.
``` bash
./scope -probe.ecs.cluster.region us-east-1
```
The default behaviour is to get the region from the instance metadata.
> Adds ECS Cluster Region option

- app/multitenant/billing_emitter.go
Fixes #2853 
I went for the simplest possible solution, even though I think that longer term it would be better to emit billing information in parallel with emitting scope reports to AWS.
> Continue processing reports if billing fails

- client/app/scripts/components/node-details/node-details-control-button.js
We'd like to gain some insight on how controls are used.
> tracking: Add Mixpanel event on Control clicks

- app/multitenant/consul_client.go
- report/marshal.go
golint has gained a new check and we don't freeze the golint version so CI was
failing on unrelated PRs:
app/multitenant/consul_client.go:69:2: redundant if ...; err != nil check, just return error instead.
report/marshal.go:188:2: redundant if ...; err != nil check, just return error instead.
Fix those!
> lint: Fix 2 sites failing a recently introduced golint check

- client/app/scripts/components/node-details/node-details-control-button.js
Unfortunately, I forgot to rebase before renaming trackMixpanelEvent() and a PR
adding a new trace point was already in-flight.
More precisely:
- https://github.com/weaveworks/scope/pull/2861 renames trackMixpanelEvent()
to trackAnalysticsEent()
- https://github.com/weaveworks/scope/pull/2857 add a new
trackMixpanelEvent() call.
Each PR is fine, but with the merge of both without rebasing any, we end up
with master having a dandling call to trackMixpanelEvent().
> tracking: Fix in-flight collision of two related PRs

- report/metrics.go
When decoding a report with `Metrics` containing the zero timestamp, which we encode as an empty string, we are causing `time.Parse` to return an error. That error object is created on the heap.
Benchmarks (best time of five runs in each case):
Current master 46c5fca7ce21e12624622234ca32513cb02250e1:
```
BenchmarkDecode-2   	     100	  15286633 ns/op	 4213446 B/op	   75126 allocs/op
```
After 9322b54b68e5b314b742c5981afd3b3f85b6aa28:
```
BenchmarkDecode-2   	     100	  14763561 ns/op	 4156811 B/op	   74416 allocs/op
```
> Small memory-allocation reduction

- client/app/scripts/components/plugins.js
- client/app/scripts/components/tooltip.js
- client/app/styles/_base.scss
- client/package.json
- client/yarn.lock
Fixes #2869.
The positioning of our own component is not that robust but it does the job for now. Tested on all plugins from https://github.com/weaveworks-plugins (by mocking their titles and descriptions).
> Get rid of react-tooltip dependency

- extras/generate_latest_map
- report/latest_map_generated.go
- report/latest_map_internal_test.go
Part of fixing #2866 
```
$ go test -tags netgo -bench=LatestMap
BenchmarkLatestMapMerge-2    	    3000	    403395 ns/op	  559041 B/op	    4993 allocs/op
BenchmarkLatestMapEncode-2   	    5000	    238557 ns/op	   98768 B/op	    1014 allocs/op
BenchmarkLatestMapDecode-2   	    5000	    317857 ns/op	  164944 B/op	    4004 allocs/op
```
```
$ go test -tags netgo -bench=LatestMap
BenchmarkLatestMapMerge-2    	   30000	     53852 ns/op	  131072 B/op	       1 allocs/op
BenchmarkLatestMapEncode-2   	   10000	    216475 ns/op	   98768 B/op	    1014 allocs/op
BenchmarkLatestMapDecode-2   	    5000	    287478 ns/op	   70492 B/op	    2005 allocs/op
```
> Re-implement LatestMap as a sorted slice for better performance

- client/app/scripts/actions/app-actions.js
- client/app/scripts/components/node-details/node-details-image-status.js
> Fixes images in details-panel after service -> resources change

- client/app/scripts/components/terminal.js
- client/app/scripts/index.js
- Service-ui has learned a new route which corresponds to the existing
scope terminal.html route. Both standalone and service-ui scope can now
respond to terminal.html:
- If using standalone scope path/to/scope/ -> path/to/scope/terminal.html will be used.
- If using service-ui app/instanceid -> app/instanceId/terminal.html
> Use a context sensitive route for the popped out terminal.html

- client/app/styles/_base.scss
- client/app/styles/_variables.scss
As decided in last week's design sync.
@fbarl was there another reason why the overlay-wrapper would need a background colour? I remember talking about it...
> Flat background instead of gradient

- probe/docker/controls.go
This hasn't been found in the wild but by code inspection. If we fail the
docker API call, the pipe is never closed. Close it before returning.
> docker: Close pipe when the docker API call fails

- client/app/scripts/components/node-details/node-details-table.js
Fix #2898.
The `tableContent` ref is only set after the first render, so if we would immediatelly focus on a row in the first render cycle, the race conditions would sometimes cause this error.
Ignoring the height if `tableContent` is not there is fine as the height defaults to `0`, which is always fine before the second render (when a row might be removed from the table so that value becomes relevant).
> Check whether tableContent ref is present

- client/app/scripts/actions/app-actions.js
- client/app/scripts/reducers/root.js
Should fix #2858.
Although I couldn't find the exact cause (the problem is not really reproducible, there seems to be a ~0.5% chance of running into a race condition), I believe that one of the two measures will make it vanish:
* Set initial viewport `(width, height)` to `(0, 0)` in the global state. That one gets set to proper values once `App` component mounts, but we want to make sure it's a numerical value (vs. `undefined`) before in case the zooming selectors which depend on it pick it up before the app is mounted.
* Make sure `NaN` values are never cached. That means that even if we hit the same race condition, it should fix itself in the next render loop because the default zoom values will be used again instead of the cached `NaN`. So if this error does happen again, I expect it …
> Try to prevent zooming NaN errors

- client/app/scripts/actions/app-actions.js
- client/app/scripts/components/app.js
- client/app/scripts/components/time-travel-wrapper.js
- client/package.json
- client/yarn.lock
Resolves #2887.
As we need to support both Scope standalone and Scope in Weave Cloud context, a couple of actions and `getState`s needed to be tweaked to handle both cases.
If `firstSeenConnectedAt` field is not available for an instance, we default to beginning of year 2014.
> Use firstSeenConnectAt for beginning of availability period in Time Travel

- probe/awsecs/client.go
> Don't de-reference pointers from AWS without checking

- render/detailed/connections.go
- render/id.go
Since we do this a lot, scanning the lists in-place saves work.
Also we don't need to sort them since StringSet is implemented as a sorted set of strings
It's actually benchmarking a little slower, when the best of five runs is taken, but with reduced memory allocation.  The timing of this benchmark is highly variable on my VM; the new benchmarks in #2920 are more reliably faster with this change.
Before
```
BenchmarkTopologyList-2   	       1	1479321809 ns/op	351308800 B/op	 2913864 allocs/op
```
After
```
BenchmarkTopologyList-2   	       1	1511797615 ns/op	347651256 B/op	 2753226 allocs/op
```
> Avoid object creation when scanning DNS names

- app/api_topologies.go
- render/container.go
- render/ecs.go
- render/filters.go
- render/host.go
- render/pod.go
- render/process.go
- render/render.go
- render/swarm.go
- render/weave.go
Remove all memoisation and then re-introduce it a) for top-level renderes, i.e. those closest to the API, and b) shared renderes.
This cuts the number of memoising renderers from 74 to 21.
I ran a number of tests with a recent prod report
```
prog/scope --mode=app --weave=false --app.collector=file:report.json
```
and then timed the fetching of topologies with
```
time curl -so /dev/null http://localhost:4040/api/topology/<topology>
```
| topology               | befor | rpeat | ahost | hits   | after | rpeat | ahost | hits   |
| ------------------------ | ------- | ------- | ------- | ------- | ------- | ------- | ------- | ------- |
| processes              | 0.315 | 0.108 | 0.125 | 0/1/1 | 0.312 | 0.108 | 0.124 | 0/1/1 |
| processes-by-name      | 0.249 | 0.029 |       | 0/1   | 0.229 …
> remove unused memoisation

- app/benchmark_internal_test.go
- render/container.go
- render/host.go
- render/id.go
- render/process.go
- render/render.go
In three cases: `ConnectionJoin`, `ProcessRenderer` and `HostRenderer`, the code was running a `Map` to speculatively create `Node`s, then a `Reduce` to match them all up with something else.
If we replace those multiple operations with a single routine which does the matching directly, we save a lot of garbage.
I also added benchmark to time a single topology rendering, equivalent to hitting an endpoint like`/api/topology/hosts`. Best time of five runs; input is a 33MB report from production on Oct 15:
Before
```
$ go test -tags 'unsafe netgo' -run=x -bench=Topology -bench-report-file=prod-report1.json
BenchmarkTopologyList-2         	       1	1400508627 ns/op	352382920 B/op	 2913537 allocs/op
BenchmarkTopologyHosts-2        	       1	1124918587 ns/op	302509672 B/op	 2627937 allocs/op …
```
> Optimisation: replace three map-reduces with Renderers

- app/api_topologies.go
- app/api_topologies_test.go
- app/api_topology.go
- render/benchmark_test.go
- render/container.go
- render/container_test.go
- render/detailed/node_test.go
- render/detailed/parents_test.go
- render/detailed/summary_test.go
- render/filters.go
- render/filters_test.go
- render/host.go
- render/host_test.go
- render/memoise.go
- render/memoise_test.go
- render/pod.go
- render/pod_test.go
- render/process.go
- render/process_test.go
- render/render.go
- render/render_test.go
- render/selectors.go
- render/short_lived_connections_test.go
Stats are easily (and efficiently) produced as part of `Render`ing so there is no need for a separate `Stats` method.
> produce stats as part of rendering

- client/app/scripts/components/node-details/node-details-image-status.js
Fixes #2697 
`.length` was called on an object
The cone of shame goes to the author of this: https://github.com/weaveworks/scope/commit/3ec7cc82e65fa94dfc836b0e8e55f7b1c9bd0fc0
> Fix incorrect image status text bug

- client/app/scripts/actions/app-actions.js
- client/app/scripts/components/footer.js
- client/app/scripts/components/node-details/node-details-info.js
- client/app/scripts/components/node-details/node-details-table.js
- client/app/scripts/components/time-travel-wrapper.js
- client/app/scripts/reducers/root.js
- client/app/scripts/utils/router-utils.js
- client/app/scripts/utils/string-utils.js
- client/app/scripts/utils/web-api-utils.js
- client/package.json
- client/yarn.lock
Fixes #2823.
* Store the `pausedAt` value in the URL (as `timestamp` field), effectively storing the Time Travel state.
* Use a fallback mechanism to go into the _paused_ state at the current timestamp if Time Travel functionality is not provided (which is the case for the typical standalone _Scope_ setup).
* Bump the Time Travel component version and forward it timestamps as formatted strings.
* Don't go out of Time Travel mode when unmounting the UI.
* Empty `version` field state is now `null` instead of `...` for state tree consistency.
> Use timestamp in URL

- render/id.go
- report/id.go
- report/networks.go
Make low-level parsing more closely aligned to what we need, to save memory allocations.
See individual commit messages for more details.
These routines are called a lot, so this change reduces garbage collection
Benchmarks before (c5bdebdffebfa7cc0839770a3bf70429260f1bc9):
```
BenchmarkTopologyList-2         	       2	 603197223 ns/op	112161732 B/op	 1253503 allocs/op
BenchmarkTopologyHosts-2        	       3	 385415232 ns/op	82957173 B/op	 1015204 allocs/op
BenchmarkTopologyContainers-2   	      10	 192766565 ns/op	33145659 B/op	  407698 allocs/op
```
after this PR:
```
BenchmarkTopologyList-2         	       3	 484253544 ns/op	104023597 B/op	  977911 allocs/op
BenchmarkTopologyHosts-2        	       3	 366672131 ns/op	75139373 B/op	  742471 allocs/op
BenchmarkTopologyContainers-2 …
```
> Parsing optimisations

- render/filters.go
- render/render.go
They are small and don't carry mutable state, so there is no point passing them by reference.
> pass render filters and maps by value rather than reference

- app/api_topologies.go
to include recently added k8s types.
This is all rather inefficient. See #2945.
> Expand the app's k8s namespace calculation

- app/api_topologies.go
- app/api_topologies_test.go
- app/api_topology.go
- app/benchmark_internal_test.go
- render/benchmark_test.go
- render/container.go
- render/container_test.go
- render/detailed/node_test.go
- render/detailed/parents_test.go
- render/detailed/summary.go
- render/detailed/summary_test.go
- render/filters.go
- render/filters_test.go
- render/host.go
- render/host_test.go
- render/memoise.go
- render/memoise_test.go
- render/pod.go
- render/pod_test.go
- render/process.go
- render/process_test.go
- render/render.go
- render/render_test.go
- render/selectors.go
- render/short_lived_connections_test.go
Decorators turn out to be an unnecessary abstraction that rather obscures what's going on. So let's get rid of them!
Decorators were used to dynamically construct filters from UI selections - e.g. namespaces, system vs app containers, etc; the selectors in the bottom left corner of the current scope UI - and apply them to the output of topology renderers - pods, containers-by-image, etc; the selectors at the top centre of the current scope UI. Decorators were accomplishing that in a rather complicated way, by composing renderers that wrap the base topology renderers.
This PR unravels all that.
The filter selection from the UI is now turned into a `FilterFunc`, which we `Apply()` to the output of topology renderers. The `render.Render()` function does exactly that, and very clearly so. The …
> Decorators, begone!

- render/container.go
- render/host.go
- render/process.go
- render/render.go
`MapX2Host` and to a lesser extent `MapProcess2Name` have the property that they map many nodes onto fewer nodes, so looping and using the machinery in `joinResults` is more effective than creating many copies of the same node and merging.
Benchmarks before (c5bdebdffebfa7cc0839770a3bf70429260f1bc9):
```
BenchmarkTopologyList-2         	       2	 603197223 ns/op	112161732 B/op	 1253503 allocs/op
BenchmarkTopologyHosts-2        	       3	 385415232 ns/op	82957173 B/op	 1015204 allocs/op
BenchmarkTopologyContainers-2   	      10	 192766565 ns/op	33145659 B/op	  407698 allocs/op
```
after this PR:
```
BenchmarkTopologyList-2         	       3	 476705872 ns/op	101366640 B/op	 1109042 allocs/op
BenchmarkTopologyHosts-2        	       3	 373288182 ns/op	76540733 B/op	  933301 allocs/op …
```
> Rewrite more Map-Reduces as Renderers to save garbage

- client/app/scripts/components/node-details/node-details-image-status.js
find returns 'undefined' not 'null'!
Fixes #2941
> Correctly show whether there are new images or not.

- render/memoise.go
- render/render.go
so that benchmarks yield more consistent results.
> make render.ResetCache() reset all caches

- render/memoise.go
- render/memoise_test.go
All outputs of `Memoise()` are fixpoints to the function, i.e. feeding them as inputs to the function just returns them.
We don't hit this optimisation in current code but have had instances in the past.
> optimisation: make Memoise(Memoise(...)) only memoise once

- render/render.go
- render/theinternet.go
- vendor/github.com/camlistore/camlistore/pkg/lru/COPYING
- vendor/github.com/camlistore/camlistore/pkg/lru/cache.go
- vendor/manifest
We use an LRU cache implementation that is keyed on strings, which avoids conversion to/from interface and the memory allocation that entails.
This supersedes #2939.
> optimisation: faster knownServiceCache

- app/api_topologies.go
- app/api_topologies_test.go
- app/api_topology.go
- render/container.go
- render/container_test.go
- render/filters.go
- render/filters_test.go
- render/host.go
- render/pod_test.go
- render/process.go
- render/render.go
The current rendering pipeline looks like this:
```
render . filterUnconnectedPseudo . memoise . filter(options)
```
We render a report, filter unconnected pseudo nodes, memoise the result, and apply user-specified filters.
Some of the steps are composites. `filterUnConnectedPseudo` nodes colours connected nodes in one step and then applies an ordinary filter that drops uncoloured nodes:
```
filterUnconnectedPseudo = colorConnected . filter(unconnectedPseudo)
```
And filtering always filters unconnected pseudo nodes:
```
filter(x) = filter'(x) . filterU
```
where `filter'(x)` is the "raw" filter operation and `filterU` is the "filter unconnected pseudo nodes" step.
So the current pipeline actually looks like this:
```
render . colorConnected . filter'(unconnectedPseudo) . filterU . …
```
> filter out unconnected pseudo nodes just once, at the end

- report/benchmark_internal_test.go
- report/marshal.go
This is speculative: empirically it goes faster but theoretically it could make things worse.
So I would like to try it out by merging into master hence into dev, and if we don't like it we can revert.
> Decode reports from a byte buffer

- probe/kubernetes/replica_set.go
`ReplicaSetSpec.Replicas` is an `*int32`. Just like in `DeploymentSpec`, where we deal with that in the same way.
I stumbled across this when looking at a report...
```json
"kubernetes_desired_replicas": {
"timestamp": "2017-11-30T15:40:13.064620595Z",
"value": "0xc42fd73888"
},
```
Oops.
> fix incorrect reporting of replicaset DesiredReplicas

- probe/kubernetes/reporter.go
Also, add Deployment as Pod parent.
Fixes #2662
> Stop reporting ReplicaSets

- extras/generate_latest_map
- report/latest_map_generated.go
- report/latest_map_internal_test.go
It isn't necessary, and it prevents the codec from seeing maps as empty
Partial fix for https://github.com/weaveworks/scope/issues/1201#issuecomment-235205270 - this makes `omitempty` work for `controls` and `latest`.
> Remove struct wrapping LatestMap

- app/benchmark_internal_test.go
- report/report.go
The vast majority of the cost is memory allocation, so doing a first pass to see whether any upgrading is necessary at all, and thus avoiding allocation when it isn't, is a massive saving.
Part of resolving #2959.
> make report upgrading fast when it's a no-op

- app/benchmark_internal_test.go
- app/merger_test.go
- common/xfer/plugin_spec_internal_test.go
- render/benchmark_test.go
- report/latest_map_internal_test.go
- report/node_set_test.go
That's what `-benchmem` is for.
> do not report allocations in benchmarks 

- prog/probe.go
This can save a few DNS queries here and there!
> probe: Use an absolute FQDN for cloud.weave.works by default

- app/collector.go
- app/multitenant/aws_collector.go
This change will reduces upgrades, since `report.Upgrade` only performs an upgrade if necessary.
Fixes https://github.com/weaveworks/scope/issues/2970
> Upgrade reports before caching

- app/api_report.go
- app/collector.go
- app/multitenant/aws_collector.go
This introduce a cheap `/api/probes?sparse` variant.
In many cases we only need to know whether there are _any_ connected probes, and not the probe details. Obtaining that info is cheaper since it requires no reading or merging or reports.
Fixes #2982.
> cheap probe connectedness api endpoint

- client/app/scripts/components/time-control.js
- client/app/scripts/components/time-travel-wrapper.js
- client/package.json
- client/yarn.lock
Also extends the `TimeTravelWrapper` with the show/hide CSS animations removed in https://github.com/weaveworks/ui-components/pull/78.
Prerequisite for https://github.com/weaveworks/service-ui/pull/1618 to be merged.
> Bump ui-components to include decomposed Time Travel

- render/process.go
We used to ignore source endpoints that are associated with multiple destination endpoints, which is a partial workaround for our inability to correctly represent two connections from the same source ip/port
but different processes, or the same destination ip/port but different processes. See #2665.
However, that condition is too coarse. In particular, we end up ignoring endpoints that are connected to NATed destinations, since the latter are represented by two (or more) endpoints.
The change here corrects that.
Fixes #2943 (or, rather, it fixes the bit that isn't covered by other issues).
> don't exclude NATed connections in mapping to processes

- bin/release
`push_images` used to tag and publish the latest built image, no matter what version or what branch or tag was checked out.
Since `bin/release build` and `bin/release publish` can be run at different times, it was possible for the latest built image to change. At which point `bin/release publish` would tag and publish an intended image.
Moving image tagging at build time will prevent this from happening again.
See #2984.
> Tag images at build time

- render/container.go
- render/container_test.go
- render/metrics.go
- render/metrics_test.go
- render/pod.go
- render/render.go
- render/render_test.go
- render/weave.go
All the MapFuncs that needed networks have been elevated to Renderers.
> refactor: drop networks from render.MapFunc

- common/weave/client.go
This applies when running scope deployments without Weave Net.
Fixes #1726.
> Suggest how to disable weave errors and warnings

- render/container.go
- render/host.go
- render/process.go
- render/render.go
A bunch of refactoring, tidying up, simplification and a tiny bit of optimisation.
> simplify `joinResults`

- render/render.go
We need this when mapping from container images to hosts - the same container image can reside on multiple hosts - and from pods to services - the same pod can be selected by multiple services. (Though the latter case currently isn't using `joinResults`.)
> cope with one->many topology mappings

- backend/Dockerfile
I came up with some benchmarks that say it goes a bit faster, but the timings are highly variable from one minute to the next so without spending an hour trying to tie them down let's just upgrade because Go 1.9 is better than Go 1.8.
Right after a release (1.6.7) is a good time to upgrade.
> Upgrade Go to 1.9.2

- probe/plugins/registry.go
- probe/topology_tagger.go
- report/report.go
- report/report_test.go
Previously this was buidling a fresh map of all topologies, just so it could look up the one given as an argument.
Node summarisation (via `detailed.Summaries()`) in particular was badly affected by that.
> make `Report.Topology(name)` fast

- render/detailed/parents.go
- report/metadata_template.go
- report/metric_template.go
- report/table.go
Pre-allocating slices really pays dividends when we create loads of them and they don't grow very large.
Also, a bunch of code in templates/tables used slices as Maybes, i.e. returning nil or a single-element slice, which is horrendously inefficient.
> optimisation: pre-allocate, and fewer slices during summarisation

- render/detailed/connections.go
- render/detailed/summary.go
- render/filters.go
- render/id.go
- report/id.go
TheInternet hasn't existed as a single node for a long time.
We also move & export the IsInternetNode predicate so it can be used in more places.
> refactor: banish TheInternet

- app/api_topologies.go
- app/api_topologies_test.go
- app/api_topology.go
- app/benchmark_internal_test.go
- app/collector.go
- render/detailed/node.go
- render/detailed/node_test.go
- render/detailed/summary.go
- render/detailed/summary_test.go
- report/report.go
It shouldn't be in 'report' because that is shared between the probe and the app, and RenderContext, as the name suggests, is only needed in the app.
> refactor: move RenderContext where it belongs

- render/container.go
- render/host.go
- render/id.go
- render/pod.go
- render/process.go
- render/render.go
It turns out that nothing is actually looking at the metadata fields we were propagating in the Map/join functions. Instead, all the metadata being rendered comes from nodes we are joining with. Furthermore, summarisation does a reasonable job of rendering nodes knowing just their ID and topology.
This change makes the Map/join functions much more regular. With the exception of `PropagateSingleMetric` (which really shouldn't be a Map - see  #3008), all these functions now produce nodes with just an id & topology, and no metadata. This allows us to simply `joinResults.add*`. It also brings some performance benefits - a few % saved allocations in the rendering benchmarks. And it's a step on the way to unifying Map and join.
> remove unnecessary metadata propagation

- app/api_topologies.go
- client/app/scripts/components/node-details/node-details-table-node-link.js
- render/detailed/connections.go
- render/detailed/node_test.go
- render/detailed/summary.go
- render/detailed/summary_test.go
- render/process.go
> show unconnected processes

- probe/kubernetes/client.go
...which is useful if we want to disable periodic fetching of all objects.
Previously the interval was also used to set the initial backoff of the reconnect logic (all this code was introduced in #2562). A zero value there would result in _no_ backoff. So instead we now just use the default, which is 10s which also happens to be the default `probe.kubernetes.interval`, so there is no change in behaviour for the stock settings.
> permit setting `probe.kubernetes.interval` to 0

- app/api_topologies.go
- probe/kubernetes/client.go
- probe/kubernetes/meta.go
- probe/kubernetes/namespace.go
- probe/kubernetes/reporter.go
- probe/kubernetes/reporter_test.go
- report/id.go
- report/map_keys.go
- report/report.go
- report/report_test.go
If the probe reports namespace topologies, the app, in particular `updateKubeFilters()`, is able to avoid unnecessary loops.
Fixes #2945.
This PR also fixes incorrect comments and removes `WalkNodes()` which was unused.
> Probe reports namespaces

- app/api_topologies.go
This change makes sure an empty `APITopologyOptionGroup` struct is not created for namespaces, if there are no namespaces to report.
This was introduced in https://github.com/weaveworks/scope/commit/1fb23dd8f9a8e5402f1e16e0a29e9f1229c5f313 .
> 'updateKubeFilters` returns early if there are no namespaces

- probe/kubernetes/client.go
- probe/kubernetes/controls.go
- probe/kubernetes/logreadcloser.go
- probe/kubernetes/logreadcloser_test.go
- probe/kubernetes/pod.go
- probe/kubernetes/reporter_test.go
This is achieved by issuing an http request for each container to kubernetes' API, which yields one Reader for the corresponding container.
`logReadCloser' then reads from the above readers in parallel as data is available, buffering when necessary, forwarding it to clients by implementing the io.ReadCloser interface.
Part of #2234.
> Reading pod logs returns all container logs

- render/container.go
- render/endpoint.go
- render/host.go
- render/pod.go
- render/process.go
This isn't quite as neat as we'd want to make it, because two of the three call sites still require a closure, but it's still an improvement.
Note that every instance of MapEndpoints only ever maps to one topology, which, furthermore, is a core report topology. Hence we can just parameterise MapEndpoints with that topology, and then the map functions can return just the node ids.
> refactor: extract common code in endpoint mapping

- client/package.json
- client/yarn.lock
Resolves https://github.com/weaveworks/service-ui/issues/1304.
The issue was actually solved in https://github.com/weaveworks/ui-components/pull/90, but that only got released in `v0.4.2`, so wasn't included in Scope.
> Bump ui-components to v0.4.18

- client/app/scripts/components/embedded-terminal.js
If the animation has no effect, `onTransitionEnd`'s handler is not called.
Since `onTransitionEnd`'s handler controls whether the terminal is shown or not (by passing `connect=true` as a Terminal prop), set the `animated` variable to true after a timeout.
Please see:
* https://stackoverflow.com/questions/2087510/callback-on-css-transition/11354026#11354026
* https://github.com/scttnlsn/backbone.viewkit/issues/4
* https://forums.xamarin.com/discussion/58456/why-isnt-my-transitionlistener-getting-called
Fixes: #3020
> Set a timeout to Terminal animation

- client/app/scripts/components/app.js
Fixes #3024.
The router hooks weren't properly cleaned up, so when Scope app would be mounted second time, they would be in conflict with the new hooks.
This fix is a prerequisite for making https://github.com/weaveworks/service-ui/pull/1787 work.
> Stop page router on App unmount

- probe/kubernetes/logreadcloser.go
logReadCloser would spin on Read after Close because EOF was not returned.
This change ensures EOF is returned once Close() is called.
Fixes #3033.
> logReadCloser: ensure EOF after `Close()`

- client/app/scripts/components/node-details.js
- client/app/scripts/components/node-details/__tests__/node-details-health-link-item-test.js
- client/app/scripts/components/node-details/node-details-health-link-item.js
- client/app/scripts/components/time-travel-wrapper.js
- client/app/scripts/reducers/root.js
- client/app/scripts/utils/__tests__/web-api-utils-test.js
- client/app/scripts/utils/router-utils.js
- client/app/scripts/utils/time-utils.js
- client/app/scripts/utils/web-api-utils.js
Resolves #3029.
Everything should be working as before :)
> Change pausedAt format from moment() back to ISO string

- probe/kubernetes/client.go
`isResourceSupported` checks whether a kubernetes resource is supported by the api server.
This ensures that, if the probe is unable to communicate with the api server, the call is retried until a true/false response.
If `isResourceSupported` returns false, `ListAndWatch` is not called and `runReflectorUntil` just exits.
Fixes #3027.
Tested with kubernetes v1.3.0 and v1.8.0.
> Check if k8s resources are supported in `runReflectorUntil`

- client/app/scripts/components/node-details/__tests__/node-details-table-test.js
- client/app/scripts/components/node-details/node-details-generic-table.js
- client/app/scripts/components/node-details/node-details-table.js
- client/app/scripts/utils/node-details-utils.js
Duration dataType for table columns is now sorted as numeric value.
Default sorting is kept as ascending and text is left-aligned, unlike
numbers.
Fixes #3026
> client: Fix uptime sort in table view

- client/app/scripts/reducers/__tests__/root-test.js
- client/app/scripts/reducers/root.js
- client/app/scripts/utils/hash-utils.js
- client/app/scripts/utils/router-utils.js
Resolves #1727.
_major_
* Use only non-default values for `topologyOptions` in Scope state. These are calculated via new helper `hashDifferenceDeep` which basically omits all the deep non-hash values which correspond literally to default options.
* Filter out all (other) URL state fields which correspond to their initial Redux state.
_minor_
* Removed `label` field from `nodeDetails` Scope state hash array, as it wasn't used anywhere.
* Changed `searchQuery` Redux state default to `''` for better matching with the URL state.
Note: I'm aware that `topologyId` field could also have been omitted in the URL in case it has a default value, but that default topology is somewhat arbitrary and I didn't want to make a special case of it.
> Remove default values from URL state hash

- client/app/scripts/actions/app-actions.js
- client/app/scripts/components/terminal.js
Moving `deletePipe()` in `componentWillUnmount()` ensures the pipe is deleted when:
1. the terminal is closed
2. the terminal is closed when closing the pod panel
The pipe still does not get deleted when popping out the terminal. Created https://github.com/weaveworks/scope/issues/3047.
Fixes #3035.
> Close terminal pipe, when closing the pod panel

- probe/kubernetes/client.go
Reflectors are created and run within the same function, asynchronously from the main thread.
Creating reflectors may require calls to the kubernetes api, which can return errors.
API errors are not handled in the main thread, but are handled asynchronously by retries.
Fixes #3049.
> Create reflectors asynchronously

- site/installing.md
...and add instructions to get the requisite permissions on GKE.
Fixes #3051.
> revamp install instructions

- client/app/scripts/components/node-details.js
- client/app/scripts/components/node-details/node-details-image-status.js
- It should only be visible on the kubernetes contoller node-details
panels.
- This fixes a bug where we were showing it on all node-details if you
were on the controller topology.
Fixes https://github.com/weaveworks/service-ui/issues/1887
> Fixes bug showing "container image status" on all resource types

- render/detailed/links.go
- render/detailed/links_test.go
- render/detailed/summary.go
The previous link to 'Monitor' contained a recording rule metric, and since not all Weave Clound instances have recording rules, the link would redirect to a 'Monitor' page without data points.
The recording rule metric has been substituted with the underlying query.
Fixes #2925
> Replace service cpu/mem link to 'Monitor'

- client/app/scripts/actions/app-actions.js
- client/app/scripts/components/app.js
- client/app/scripts/components/nodes.js
- client/app/scripts/components/time-control.js
- client/app/scripts/components/time-travel-wrapper.js
- client/app/scripts/constants/styles.js
- client/app/scripts/reducers/root.js
- client/app/scripts/selectors/time-travel.js
- client/app/styles/_base.scss
* Show Time Travel at all times if historic reports are supported (in particular in Weave Cloud) together with pause/live buttons, removing the Time Control _live/pause/time travel_ buttons in the top right corner.
* If historic reports are not supported, show only Time Control with _live/paused_ buttons as before.
**Scope in Weave Cloud**
**Scope standalone**
> Show Time Travel at all times in Weave Cloud

- client/app/scripts/charts/nodes-grid.js
- client/app/scripts/constants/styles.js
- client/app/scripts/selectors/canvas.js
- client/app/styles/_base.scss
Follow-up on #3065 (which needs to be merged first).
Fixes #3015.
Use relative positioning for `NodesGrid` and calculate its height from its _top_ coordinate + window height.
> Relative positioning for Table view tables

- report/node.go
Looks like an omission from #462
(mostly we don't get `omitempty` because codecgen can't look through our data structures to spot they are empty, but `IDList` is a simple slice so it does work)
(later versions of codecgen do this better)
> Set 'omitempty' on Node Adjacency

- app/merger_test.go
- probe/awsecs/reporter.go
- probe/awsecs/reporter_test.go
- probe/docker/reporter.go
- probe/docker/tagger.go
- probe/endpoint/connection_tracker.go
- probe/kubernetes/reporter.go
- probe/overlay/weave_test.go
- probe/plugins/registry_internal_test.go
- report/topology.go
This had little use and was obscuring the mutating nature of `AddNode()`.
> refactor: don't return receiver in Topology.AddNode()

- probe/host/tagger.go
- probe/topology_tagger.go
- report/topology.go
In some places `AddNode()` was called after adding to an existing node, in which case the `Merge()` is just a waste of time.  
Spotted in a memory profile of the probe: about 14% of all memory allocated is in `Merge()`:
```
----------------------------------------------------------+-------------
flat  flat%   sum%        cum   cum%   calls calls% + context 	 	 
----------------------------------------------------------+-------------
16356.22MB 41.27% |   github.com/weaveworks/scope/probe.topologyTagger.Tag.func1 /go/src/github.com/weaveworks/scope/probe/topology_tagger.go
12215.04MB 30.82% |   github.com/weaveworks/scope/probe/host.Tagger.Tag /go/src/github.com/weaveworks/scope/probe/host/tagger.go
4821.62MB 12.17% |   github.com/weaveworks/scope/probe/endpoint.(*connectionTracker).addConn …
```
> Add topology.ReplaceNode() for efficiency

- probe/process/reporter.go
- probe/process/reporter_test.go
- report/controls.go
- report/metadata_template.go
- report/metric_template.go
- report/metrics.go
- report/topology.go
From a memory profile, 11% of all space is allocated in `process.reporter.processTopology()`; this PR creates a benchmark and reduces allocations by half through calling different APIs.
Also optimised the merge-to-empty case in a few sub-structures that should help a little elsewhere.
before:
```
BenchmarkReporter-2   	   10000	    105043 ns/op	   32205 B/op	     227 allocs/op
```
after:
```
BenchmarkReporter-2   	   50000	     34800 ns/op	   15818 B/op	     161 allocs/op
```
> Optimise processTopology()

- prog/main.go
If we have the node-name then we can save work requesting the list of local pods from kubelet.  And the best way to get the node name is via the "downwards api", i.e. put this in the DaemonSet Yaml:
```
- name: KUBERNETES_NODENAME
valueFrom:
fieldRef:
apiVersion: v1
fieldPath: spec.nodeName
```
Also drive-by fix of incorrect doc string.
> Read Kubernetes node name from environment

- client/.babelrc
- client/app/scripts/components/node-details/node-details-table-row.js
- client/app/scripts/components/topologies.js
- client/app/scripts/components/view-mode-button.js
- client/app/scripts/components/view-mode-selector.js
- client/app/styles/_base.scss
- client/package.json
- client/yarn.lock
Laying the ground for interactive tours in Scope - https://github.com/weaveworks/service-ui/issues/1861.
* Use `babel-plugin-transform-class-properties` in Scope to remove the need for annoying `.bind(this)` in constructors.
* Added a `ViewModeButton` component for smarter rerendering, to make sure the tour step on view selectors _survives_ the transition.
* Changed `onMouseUp` to `onClick` event on NodesGrid rows to catch clicking on the first row while it's focused in the tours.
* Add `className` to all the items in Topologies selector for anchoring tour steps to specific topologies.
* Hide `.nodes-chart-overlay` when transparent to get a better bounding box for the nodes graph for a tour step focus.
**Note to reviewers:** It should suffice to take a look at the code and make sure …
> Prepare DOM for Guided Tours

- probe/endpoint/connection_tracker.go
- probe/endpoint/resolver.go
- render/detailed/connections.go
- render/endpoint.go
- render/id.go
- report/dns.go
- report/report.go
- report/string_set.go
Fixes #3058 
If the probe sees many TCP sockets on a host, it will repeat the same address information on each endpoint.  Moving it to report level saves all this repetition.  Also `Sets` is an expensive data structure; for the DNS mapping I used a straightforward `map`, similar to `Topology.Nodes`.
I see about a 6% reduction in JSON file size, on Weave Cloud production reports.
The mapping is used as a mapping from IP address to name, and the current implementation encodes it the same way, but to me it seems more logical to send it as a mapping from name to address.  Probably that doesn't matter.
~I considered moving `DNSFirstMatch` from `render` to `report`, to collect all the behaviour together.  However the decisions made are somewhat related to rendering, so I left it.~
>  Move DNS name mapping from endpoint to report

- probe/kubernetes/reporter.go
- probe/kubernetes/service.go
- report/map_keys.go
Addresses part of #2749 - this adds mapped ports, and the service type.
> Add Kubernetes service type and ports

- probe/kubernetes/client.go
- prog/main.go
We set up a "watch" on everything we need so there is no reason to ~poll~ re-sync repeatedly.
> Remove flag -probe.kubernetes.interval and stop re-syncing Kubernetes data

- probe/docker/tagger.go
Augment existing node rather than creating a new one then merging it, and avoid creating a set with one entry.
This restores the "item 4" from #3073 that was incorrectly done and removed.
> More efficient docker Tagger

- probe/docker/tagger_test.go
- probe/process/tree.go
I was trying to understand how pids were looked up, and wasted some time looking at this function which is never used.
> Remove unused process tree function GetChildren()

- extras/generate_latest_map
- report/latest_map_generated.go
- report/latest_map_internal_test.go
Fixing a rare case that came up in a test. In order for this to cause a problem, the data being decoded has to have entries out of order, and have a value that is nil or omitted.  Current probes always serialise the entries in order, and don't omit empty values, but I think it's better to be safe.
> Blank out value on LatestMap decode insert

- report/marshal_test.go
- report/node.go
- report/topology.go
- test/reflect/deepequal.go
Previously the only roundtrip test was for an empty report. This test has fake data similar to that found in real reports.
`Node.Metrics` does not round-trip exactly: it is tagged with `omitempty` so when decoded an empty map turns into the zero value.  A `DeepEqual` workaround is added so the test passes.
Perhaps it would be better to adjust the decode so the field is not nil after decoding.
This PR is a precursor to tests which check backwards compatibility: for instance that the binary data encoded by version 1.2 still decodes to the expected structure.
> Add a test that checks if reports with data round-trip

- client/app/scripts/components/app.js
This is instead of dispatching the flag from the constructor which was called only once, hence neutralizing updates.
> Dispatch 'Monitor' flag `render` function

- client/app/scripts/reducers/root.js
Fixes https://github.com/weaveworks/service-ui/issues/1999.
As @foot discovered, the issue was actually easily reproducable - it would always show the _Uncontained_/_Unmanaged_ nodes on fresh page load, regardless of the options set in the UI.
The problem was that the initial `ROUTE_TOPOLOGY` handler would set `topologyOptions` to a certain value and then the condition in `RECEIVE_TOPOLOGIES` would not update with the default options once they'd be received with topologies data (with a certain delay).
The solution was to unconditionally update the options with defaults in `RECEIVE_TOPOLOGIES`  on first load, but using them only as 'fallback', still giving priority to the URL/local state options.
> Pick up default topology options on initial load

- client/package.json
- client/yarn.lock
Fixes #3101.
Also upgrades `ui-components` from `v0.4.18` to `v0.4.36`. That's a big bump but only https://github.com/weaveworks/ui-components/pull/123, https://github.com/weaveworks/ui-components/pull/113 and https://github.com/weaveworks/ui-components/pull/129 have changed the components used by Scope. Out of them, only the last one (changing the circular loader appearance) will have a visible effect in Scope.
> Bump moment.js & ui-components deps

- circle.yml
Looks like the order of types in the generated output is unpredictable, so we need the actual file Scope was built with for debugging or profiling.
Also drive-by optimisation to stop saving the tarfile - we started in 441b71884b1d434221b8866e6719191eb975eff2, which offers no explanation as to why.
> Save codegen output as CI artifact

- probe/docker/registry.go
- report/report.go
To test this, run
```
docker run --name=foo --rm -ti alpine sleep 10
```
On master it can take several seconds for the container to appear on the topology view, and then several seconds for it to disappear when it stops.
After the first commit, it disappears immediately when stopped, but still takes time to appear. The latter is cured by the 2nd commit.
Fixes #3113.
In the process I discovered #3120.
> make shortcut reports work (again)

- probe/kubernetes/pod.go
- render/pod.go
- report/map_keys.go
- report/report.go
Fixes #3083.
An alternative here would be to not even _report_ Failed pods, but that is more work.
> don't show Failed pods

- site/installing.md
Current installation instructions for OpenShift fail because they introduce policy changes to a different project than the one where weave scope pods and resources are created.
`https://cloud.weave.works/k8s/scope.yaml` explicitly uses the `weave` namespace - this ought to match the OpenShift project.
> documentation fix: project for openshift installation

- extras/generate_latest_map
- report/latest_map_generated.go
Small issue, but `go vet` complains.
(haven't investigated why our lint step is not catching it)
> Fix format string to work for all types

- client/app/scripts/utils/router-utils.js
- client/package.json
Fixes browser history when deep linking into node details with time context in https://github.com/weaveworks/service-ui/pull/2254.
The problem was that the URLs with the same hash, but permutted keys would be treated as different ones, so we'd end up in routing loops under some circumstances.he 
My solution was to use `json-stable-sort` helper in some parts where `JSON.stringify` was previously used. We might want to generalize this policy whenever encoding Scope JSON state - https://github.com/weaveworks/scope/issues/3133.
Let's see if https://github.com/weaveworks/service-ui/issues/2021 also gets fixed by this change.
> Don't update route if it hasn't changed

- render/container.go
- render/container_test.go
- render/pod.go
- render/render.go
- render/render_test.go
- render/weave.go
Make all `MapFunc`s return a single `Node` instead of a set.
This lets us save a bit of time by not creating all those `map`s, and re-integrate the adjacency mapping code that was split out into `joinResults`.
Benchmarks, using a set of reports from Weave Cloud - the timings are a bit mixed but bytes and allocations are generally in the right direction:
```
benchmark                            old ns/op      new ns/op      delta
BenchmarkReportUnmarshal-2           1355945521     1327087556     -2.13%
BenchmarkReportUpgrade-2             70184976       69354449       -1.18%
BenchmarkReportMerge-2               878730403      921976801      +4.92%
BenchmarkRenderList-2                561471520      563783165      +0.41%
BenchmarkRenderHosts-2               403998863      413859127 …
```
> Simplify Map.Render()

- app/merger_test.go
- render/render.go
- report/node_set.go
We added `ps.Map.UnsafeMutableSet()` to optimise the case where you know a NodeSet is not shared with any other nodes.  We can arrange this quite easily for the `Children` of each node in `joinResults`, hence speed up rendering.
I had to adjust the smart/dumb merger benchmarks when they showed an improvement, which is spurious because this code isn't involved in merging.
Benchmarks comparison between first commit and last commit:
```
benchmark                            old ns/op      new ns/op      delta
BenchmarkRenderList-2                575964931      553021897      -3.98%
BenchmarkRenderHosts-2               408721601      362484026      -11.31%
BenchmarkRenderControllers-2         334499307      334047789      -0.13%
BenchmarkRenderPods-2                298092408      289996139 …
```
> Use single-owner code path to accumulate children when rendering

- scope
@dglaubman found that recent versions of Docker for Mac (Docker version 18.03.0-ce, build 0520e24) don't write out `${HOME}/Library/Containers/com.docker.docker/Data/database` any more.
@foot confirmed this. A fresh installation of Docker for Mac (Version 18.03.0-ce-mac60 (23751), Channel: stable) did not create the file.
The result was that installations which had this leftover file could start scope, whereas newer couldn't. The fix simply changes this check to a path which actually exists.
Thanks @dglaubman and @foot for the analysis and confirmation.
Fixes #3064
> Minimal fix to make scope start with Docker for Mac again.

- render/render.go
- report/node_set.go
This was missed from #3138.  It's a bug as-is - `Merge()` can return the rhs which is not safe to do further 'unsafe' operations on.
Benchmarks show the impact is mixed:
```
benchmark                         old ns/op     new ns/op     delta
BenchmarkRenderList-2             553973514     505759984     -8.70%
BenchmarkRenderHosts-2            345194045     366304720     +6.12%
BenchmarkRenderControllers-2      314828412     309772476     -1.61%
BenchmarkRenderPods-2             283650521     313774503     +10.62%
BenchmarkRenderContainers-2       187017594     194096252     +3.79%
BenchmarkRenderProcesses-2        121727679     111295296     -8.57%
BenchmarkRenderProcessNames-2     127764403     121302933     -5.06%
benchmark                         old allocs     new allocs     delta …
```
>  Use unsafe merge in joinResults.addChildAndChildren()

- client/app/styles/_base.scss
- client/app/styles/_contrast-overrides.scss
- client/app/styles/_variables.scss
- client/package.json
- client/yarn.lock
To be merged after https://github.com/weaveworks/ui-components/pull/175.
> Merge neutral theme colors

- report/networks.go
- vendor/github.com/k-sone/critbitgo/net.go
- vendor/manifest
We modify the critbitgo library to skip creating a route object we don't use.
The weaveworks-local modification can be removed if https://github.com/k-sone/critbitgo/pull/7 is merged.
Benchmarks (fastest of 10 runs; timings are highly variable):
```
benchmark                         old ns/op     new ns/op     delta
BenchmarkRenderList-2             593307328     555257029     -6.41%
BenchmarkRenderHosts-2            433287444     394693695     -8.91%
BenchmarkRenderControllers-2      361384179     323186742     -10.57%
BenchmarkRenderPods-2             346144553     329953227     -4.68%
BenchmarkRenderContainers-2       201489916     200237356     -0.62%
BenchmarkRenderProcesses-2        135127597     123572216     -8.55%
BenchmarkRenderProcessNames-2     152146655     149658203 …
```
> Faster path to check an IP address against known networks

- client/.sass-lint.yml
- client/.stylelintrc
- client/app/styles/_base.scss
- client/package.json
- client/yarn.lock
Resolves `scope` part of https://github.com/weaveworks/ui-components/issues/202.
Font size distribution across `scope`:
```
17 - tiny
17 - small
11 - normal
7 - large
2 - extra large
1 - huge
```
There was a strong bias towards really small font sizes compared to `service-ui`, so hopefully this will make Scope look a tiny bit more like Weave Cloud UI (although a lot of font sizes will require tiny tweaking after this PR, I'm sure).
> Enforce theme font sizes

- client/app/scripts/components/node-details/node-details-table.js
- client/app/scripts/constants/styles.js
- client/app/styles/_base.scss
Sizes the fixed table header of `NodeDetailsTable` width dynamically
depending on the content's scrollbar width. Makes sure the table header
cells align with the table body cells.
This also widens the "Parent PID" cell to make sure the text is not cut
off. Alternatively, could be renamed to "PPID".
Fixes #3158.
> Dynamic table header width according to scrollbar

- Makefile
- backend/Dockerfile
- client/Dockerfile
- docker/Dockerfile.cloud-agent
- docker/Dockerfile.scope
- extras/dialer/Dockerfile
- extras/example/Makefile
- extras/example/app/Dockerfile
- extras/example/client/Dockerfile
- extras/example/echo/Dockerfile
- extras/example/frontend-k8s/Dockerfile
- extras/example/frontend/Dockerfile
- extras/example/qotd/Dockerfile
- extras/example/searchapp/Dockerfile
- extras/example/shout/Dockerfile
- extras/example/trace_app/Dockerfile
Why? What?
- This should ultimately help for image-to-code back references.
- `org.label-schema.*` labels are now deprecated, in favour of `org.opencontainers.image.*` labels.
See also: https://github.com/opencontainers/image-spec/blob/master/annotations.md#back-compatibility-with-label-schema
- Git revision (`git rev-parse HEAD`) is now injected at `docker build` time.
Testing
```console
$ docker inspect weaveworks/scope
[
{
[...]
"ContainerConfig": {
[...]
"Labels": {
"maintainer": "Weaveworks <help@weave.works>",
"org.opencontainers.image.revision": "4e58b8302416437f3af8a938ee823b6297bcd50b",
"org.opencontainers.image.source": "https://github.com/weaveworks/scope",
"org.opencontainers.image.title": "scope",
"org.opencontainers.image.vendor": "Weaveworks",
"works.weave.role": "system"
} …
```
> Add org.opencontainers.image.* labels to Dockerfiles

- client/.sass-lint.yml
- client/.stylelintrc
- client/app/styles/_base.scss
- client/app/styles/_variables.scss
- client/package.json
- client/yarn.lock
Resolves Scope part of https://github.com/weaveworks/ui-components/issues/208.
> Enforce theme border radius

- probe/docker/container.go
- probe/docker/controls_test.go
- probe/docker/registry.go
- probe/docker/registry_test.go
- probe/docker/reporter.go
- probe/docker/tagger.go
- render/container.go
- render/detailed/node_test.go
- render/detailed/summary.go
- render/detailed/summary_test.go
- report/map_keys.go
> Show image tag in node details

- app/api_topologies.go
- app/api_topologies_test.go
- client/app/scripts/charts/nodes-grid.js
- client/app/scripts/components/node-details/node-details-image-status.js
- client/app/styles/_base.scss
- probe/awsecs/reporter.go
- probe/docker/reporter.go
- probe/host/reporter.go
- probe/kubernetes/reporter.go
- probe/overlay/weave.go
- probe/process/reporter.go
- render/detailed/node.go
- render/detailed/node_test.go
- render/detailed/summary_test.go
Follows Weave Cloud's direction of sentence case on most things.
> Sentence cased text everywhere

- vendor/manifest
Undo the local override introduced in 04ceb0cc87443b63548d6d9bbb58341ca1efc2c5
because https://github.com/k-sone/critbitgo/pull/7 has been merged.
> Put critbitgo library back to master branch

- probe/endpoint/ebpf.go
- probe/endpoint/ebpf_test.go
With c75700fe04251b6d93240fb36ec423ed22b5d59d we added code to detect
Ubuntu Xenial kernels with a regression in the eBPF subsystem in order
to gently fallback to procfs scanning on such systems (and not crash the
host system by running eBPF code).
With the latest kernel update for Ubuntu Xenial, the bug was fixed:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1763454
Therefore we can update the added check with an upper limit and make
sure that eBPF connection tracking only is disabled on kernels within
the range having the bug.
xref: https://github.com/weaveworks/scope/issues/3131
> ebpf: update check for known faulty Ubuntu kernels

- README.md
Changing the slack channel to `#scope`.
I'm pointing to the scope Google group as well. I saw that there's only one message on it. Is it new? Should it be announced somewhere else, so people know where to look?
> change slack channel to '#scope', change wording a little bit, point to mailing list

- app/api_topologies.go
Without this, we see unmanaged, uncontained or not-running containers in the graph until the front-end requests them to go away.
There was a shouty comment saying not to use the default, but I can't see any reason to take that stance. There is only one place where `""` is a valid value, which is namespaces, and it is also the default there.
To be safe, I changed the code to distinguish a lack of value from `""` so you can have both.
>  Use the default value for a TopologyOption if omitted

- client/app/scripts/reducers/root.js
- Which fails sometimes as we overwrite them whatever we find in the
url state. Url state is not complete anymore so this doesn't work
Test with:
```
cd $WEAVE/scope/client
mkdir tmp
yarn bundle
cd $WEAVE/service-ui/client
yarn add $WEAVE/scope/client/tmp/weave-scope.tgz
SERVICE_HOST=frontend.dev.weave.works yarn start
```
> Fixes sending the default topologyOptions to the /api

- client/app/scripts/components/time-control.js
- client/package.json
- client/yarn.lock
Closes https://github.com/weaveworks/service-ui/issues/2538.
Using `<TimestampTag />` component in only one place in Scope:
> Use TimestampTag component

- client/app/scripts/components/troubleshooting-menu.js
Fixes https://github.com/weaveworks/service-ui/issues/2645
Uses the correct helper to determine where to download reports from.
> Fix scope report download URL

- probe/probe.go
- report/report.go
- report/report_test.go
Removed to reduce CPU and memory usage in probes.
This code was added [in August 2016](https://github.com/weaveworks/scope/pull/1682) so that newer probes could be used with older apps. Since then we have adopted the stance that new apps will accept reports from old probes but not vice-versa, on a version change.
> Probe: remove backwards-compatibility code when publishing reports

- client/app/scripts/utils/web-api-utils.js
Prerequisite for https://github.com/weaveworks/service-ui/issues/1457.
**Note:** These changes only affect Scope in Weave Cloud (nothing about the standalone should have changed).
> Separate API endpoint namespace from URL path part

- client/app/scripts/actions/app-actions.js
- client/app/scripts/components/time-travel-wrapper.js
- client/app/styles/_base.scss
- client/package.json
- client/yarn.lock
Resolves https://github.com/weaveworks/service-ui/issues/2614 (affects only Scope in Weave Cloud).
Reuses a lot of code from `<TimeTravelWrapper />` in Service UI - @foot and I had a discussion about converging those two, but that's a separate issue.
* Bump `ui-components` `v0.4.82` -> `v0.4.95`
* Use `z-index: $layer-front` on the whole header
> Show deployments in Time Travel

- client/app/styles/_base.scss
- client/package.json
- client/yarn.lock
Scope part of https://github.com/weaveworks/ui-components/issues/265.
Tested in Scope standalone.
> Use new accent theme colors

- render/pod.go
A small performance improvement - instead of creating an entry in a map which doesn't match anything, just skip a pod with a blank IP.
This was sitting as part of #3089 which we're not going to merge.
> Don't return blank addresses for pods

- client/app/scripts/actions/app-actions.js
`api.getFluxImages` takes 3 parameters: `getFluxImages(id, serviceId = null, containerFields = [])` with a recent change adding the containerFields parameter.
The 3rd parameter (`2`) passed to `api.getFluxImages` has been incorrect for a while now.
Fixes https://github.com/weaveworks/service-ui/issues/2749
> Correct api.getFluxImages usage

- render/filters.go
Helper function `filterInternetAdjacencies()` would sometimes copy and sometimes not copy the input, which can lead to concurrent reads and writes as seen in #3219.
Changed to always copy, before calling.
I found this by eyeballing; this is the only case I could see where the input `.Nodes` can be modified.
> Stop filterUnconnected() modifying its input

- app/benchmark_internal_test.go
- app/collector.go
- app/merger.go
- app/merger_test.go
- app/multitenant/aws_collector.go
- report/report.go
- report/topology.go
When we know we have the only reference to a `Report` or `Node` object we can avoid copying the data to change it. Add "Unsafe" variants of various `Merge` operations which mutate the receiver, and a new `Merger` which takes advantage of them.
Benchmarks:
```
BenchmarkReportMerge-2 	       2	 608175373 ns/op	257994508 B/op	 1403665 allocs/op
BenchmarkReportFastMerge-2     3	 368993238 ns/op	110116594 B/op	  887828 allocs/op
BenchmarkSmartMerger-2 	      50	  28800741 ns/op	12794115 B/op	   58118 allocs/op
BenchmarkDumbMerger-2  	      20	 172918072 ns/op	54793384 B/op	  208674 allocs/op
BenchmarkFastMerger-2  	     500	   3997132 ns/op	  740686 B/op	   21410 allocs/op
```
Further refinements can be made by adding `UnsafeMerge` on `MetricTemplates`, etc., though this should be guided by …
> Faster report merging through mutating objects

- client/app/scripts/components/terminal.js
Fixes #3245 
I believe this fixes the linked issue but I haven't had a chance to test under linux yet..
> Fixes monospace font overlapping in terminal+linux

- report/marshal.go
I noticed in a profile that a lot of memory is allocated and discarded in this activity.
Benchmark run with 78 reports of around 1-3MB uncompressed:
Before (best of 5):
```
BenchmarkReportUnmarshal-2   	       1	1242562071 ns/op	427326232 B/op	 2631780 allocs/op
```
After:
```
BenchmarkReportUnmarshal-2   	       1	1035790710 ns/op	188397000 B/op	 2630861 allocs/op
```
> Use a buffer pool in report.ReadBinary() to reduce garbage-collection

- app/benchmark_internal_test.go
- extras/generate_latest_map
- report/dns.go
- report/id_list.go
- report/latest_map_generated.go
- report/latest_map_internal_test.go
- report/report.go
- report/sets.go
- report/sets_test.go
- report/string_set.go
- report/topology_test.go
This is beneficial because Scope very often merges multiple versions of the same node over time that have exactly the same labels, tags, etc., so we detect this and avoid copying.
This PR covers just three data structures - `StringSet`, `StringLatestMap` and `NodeControlDataLatestMap` - which benefit the most in profiles.
All three now use the same loop structure to merge. The loop is coded twice: once as far as we can get without changing the result, and then again after allocating space for a new return value.  If we got all the way to the end without changing anything, then return what we already have.
`StringSet` is mainly used in `Sets` where it benefits to avoid assigning to its map, so add an `unchanged` return.
Before (best of five):
```
BenchmarkReportMerge-2   	       3 …
```
> Optimise merge where one side is a subset of the other

- app/api_topologies.go
- render/benchmark_test.go
- render/process.go
Followup from #3212 
`ProcessWithContainerNameRenderer` wasn't working due missing a variable update (see #3212 ) so we decided to simply remove it, since nobody noticed and presumably nobody cares.
> Remove ProcessWithContainerNameRenderer, it wasn't working

- probe/awsecs/reporter.go
- probe/docker/container.go
- probe/docker/tagger.go
- probe/host/tagger.go
- probe/kubernetes/pod.go
- probe/kubernetes/reporter.go
- probe/kubernetes/reporter_test.go
- probe/overlay/weave.go
- render/container.go
- report/node.go
- report/sets.go
This arises from the benchmark written for #3137, in which I noticed a lot of work going into `MakeStringSets()` which turn out to be throwaway parameters for `WithParents()`.
This change also makes the call sites more readable.
Results before (best of 5):
```
BenchmarkReporter 	     500	   2671920 ns/op	  841966 B/op	    9290 allocs/op
```
After:
```
BenchmarkReporter 	    1000	   1992011 ns/op	  712151 B/op	    3975 allocs/op
```
> Optimise WithParents() when there is only one parent

- probe/kubernetes/reporter_test.go
- render/container.go
- render/render.go
- report/map_helpers.go
- report/node.go
This is a different take on solving the same problem as in #3137.  It's not quite as fast but has lower memory usage, and it doesn't have the same readability issue.
Here we make one memory allocation to resize the array, then add the contents of the map, sort to regain the `LatestMap` invariant, then remove any keys which are now duplicated (in normal usage this doesn't happen, but better to be safe. It does happen in at least one test).
Based on profiling some real probes, I wrote a benchmark to mimic typical operation of this code.
Results before (best of 5):
```
BenchmarkReporter 	     500	   2671920 ns/op	  841966 B/op	    9290 allocs/op
```
After:
```
BenchmarkReporter 	     500	   2364309 ns/op	  472526 B/op	    8479 allocs/op
```
~Note the optimisation to `propagateLatests()` in …
> Optimise Node.WithLatests()

- prog/app.go
Should fix:
```
2018/07/23 20:29:49 http: panic serving 10.244.204.241:34716: runtime error: invalid memory address or nil pointer dereference
goroutine 1169 [running]:
net/http.(*conn).serve.func1(0xc420739a40)
/usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0x17d5200, 0x2a7f5e0)
/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/weaveworks/scope/vendor/github.com/weaveworks/common/middleware.Log.Wrap.func1(0x1dc60e0, 0xc4215e7a40, 0xc4202cee00)
/go/src/github.com/weaveworks/scope/vendor/github.com/weaveworks/common/middleware/logging.go:40 +0x3c7
[...]
```
caused by an update of dependencies and that change http://github.com/weaveworks/common/pull/96/files#diff-34ebe92b41e559320767523ef0557f71R15
> Pass a logger to middleware.Log

- report/map_helpers.go
- report/node_test.go
The `fixup()` method was modifying a copy of its input, so you could get duplicate keys in the output.
Thankfully this is rare: in most cases `WithLatests()` is called with fields that are not duplicates of existing ones.
Added a test that would have caught it.
I made this PR against the release-1.9 branch so we can make a clean patch release.
> Fix WithLatests() fixup on duplicate keys

- examples/k8s/cluster-role.yaml
This will add rules to cluster role for k8s storage components.
These RBAC permissions are required for scope to fetch details about PV, PVC, SC
resources.
Signed-off-by: Satyam Zode <satyamzode@gmail.com>
> Add rules in cluster role for k8s storage components

- probe/kubernetes/persistentvolume.go
- probe/kubernetes/reporter.go
- render/expected/expected.go
- report/map_keys.go
- test/fixture/report_fixture.go
Every PV is backed by storage driver.
This will show the storage driver in the PV metadata.
Signed-off-by: Akash Srivastava <akash.srivastava@openebs.io>
fixes: https://github.com/weaveworks/scope/issues/3258
> Add storage driver name to Persistent Volume

- report/marshal_test.go
- report/node.go
- report/report.go
- report/report_test.go
This saves memory and CPU time encoding and decoding.
We assume that no probes two years old are still running, and we don't need to reconstruct the data for saved historical reports because controls are not relevant to historical nodes.
Before (best of 5):
```
BenchmarkReportUnmarshal-2   	       1	1115642386 ns/op	180600552 B/op	 2451487 allocs/op
BenchmarkReportMerge-2   	       5	 319579062 ns/op	63458179 B/op	  474721 allocs/op
```
After:
```
BenchmarkReportUnmarshal-2   	       1	1017682911 ns/op	174734200 B/op	 2451483 allocs/op
BenchmarkReportMerge-2   	       5	 284404766 ns/op	61683891 B/op	  474442 allocs/op
```
> Remove old 'Controls' field which was replaced two years ago

- probe/docker/container.go
Otherwise we get pointless errors logged in debug mode when we encounter dead containers.
> Check container is running before trying to open its namespace

- prog/main.go
This was enabled by default but we want it to be disabled instead, just
like with the docker probe.
> Disable CRI probe by default

- examples/cri/ds.yaml
volumeMounts need to refer to an existing volume name to be successfully
mounted. cri-socket is the defined volume name.
> Fix the CRI volumeMount name in the example manifest

- tools/socks/Dockerfile
- tools/socks/main.go
The `tools` directory is vendor'd in from https://github.com/weaveworks/build-tools so must not be changed here.
Since the changes were made in two different commits nearly a year apart I am simply hand-undoing them and then we can fix upstream.
> Undo changes made in the 'tools' subtree

- client/app/scripts/utils/router-utils.js
So far the localStorage state was being updated only through the route change in `updateRoute`, meaning the initial URL hit would never update it.
This PR fixes that.
> Update localStorage with Scope state also on initial router hook

- render/expected/expected.go
- report/report.go
the client now expects a node shape of `sheet` not `storagesheet`
update report.go to reflect this.
fixes #3322
> rename 'storagesheet' to 'sheet'

- client/app/scripts/charts/nodes-chart-elements.js
Old versions of scope reports use `storagesheet` as the value for node
shape. This shape is no longer supported in weaveworks-ui-components and
so this commit normalises to `sheet` for compatibility with old reports.
related #3322
> support `storagesheet` for old scope reports

- backend/Dockerfile
- client/Dockerfile
- docker/Dockerfile.cloud-agent
- probe/endpoint/dns_snooper.go
- probe/process/walker_linux_test.go
Observed this particular test  was failing on ppc64le architecture. Added the test failure log below, 
walker_linux_test.go:97:
```                --- want
+++ have
@@ -32,7 +32,7 @@
Cmdline: (string) (len=15) "curl google.com",
Threads: (int) 1,
Jiffies: (uint64) 0,
-  RSSBytes: (uint64) 8192,
+  RSSBytes: (uint64) 131072,
RSSBytesLimit: (uint64) 2048,
OpenFilesCount: (int) 3,
OpenFilesLimit: (uint64) 32768,
```
Hence modified the value for RSSBytes to accept variable value which is computed based on pageSize instead of hard-coded values, as suggested by Adam Harrison over slack channel. 
I have verified this patch on x86 setup as well and all the tests pass there.  Please provide your comments/suggestions on this. 
Thanks,
Meghali
> [Power Support] Enable weaveworks scope on Power.

- COPYING.LGPL-3
- VENDORED_CODE.md
After #3284 and #3283 are fixed, merging this PR should bring our licenses closer to reality again.
Regarding assert.sh, we follow weaveworks/build-tools#138
Regarding the MPL licensed code, I followed https://www.apache.org/legal/resolved.html#category-b
> license: document files under LGPL3 and MPL3 licenses

- probe/docker/network_linux.go
Code was unnecessarily fetching all links then fetching all addresses filtered by link, when we can just get the addresses without any filter.
> Simplify fetch of IP addresses in a namespace

- probe/docker/registry_test.go
Fixes #3209
Not very purist, but it seems to work.
> Sleep to stop TestRegistryDelete() failing

- client/app/styles/contrast.scss
import terminal.scss in contrast.scss which is missing currently and causing the terminal styling in contrast mode.
Before:
After:
fixes: #3346
> import missing terminal.scss in contrast.scss

- .circleci/config.yml
- Makefile
- client/Dockerfile
- client/package.json
Stop baking the toolchain and dependencies into the build image. Instead, run the install step each time, but use volume mounts or CircleCI caching to keep the happy path fast.
Previously, some parts of the client (UI) directory were baked into the build image, and some parts were mounted or copied into the build environment. As a result, files baked into the build image require a two-step update for changes to take effect in CI.
Now, for dockerised builds, we pre-install very little into the build image and mount the whole directory into the build environment. However, we do overlay a volume on the node_modules folder to allow the standard build toolchain to be separate from the host build toolchain.
Non-dockerised builds (e.g. CI) are now more similar to the dockerised versions.
Fixes …
> Rework UI build to improve caching and fix packaging issue

- .circleci/config.yml
This is a follow up to #3353. It should make the cache directory be properly used.
> Update CI UI build container to master-c0b60a16

- examples/k8s/cluster-role.yaml
- examples/k8s/psp.yaml
This add a psp file with needed right to work on kubernetes.
Fixes https://github.com/weaveworks/scope/issues/3203
Signed-off-by: Julien Garcia Gonzalez <julien@giantswarm.io>
> example k8s: add support for PodSecurityPolicy

- probe/cri/registry_test.go
tests: Adding Unit tests
Some work on adding unit tests for `probe/cri`. This PR adds absolute basic unit tests.
Partially fixes https://github.com/weaveworks/scope/issues/3302
P.S: I'm a beginner to Go. Open to listening for things I can do better.
> #3302: Absolute basic UT

- Makefile
Create the UI toolchain dir from the Makefile to prevent docker from creating it with root as the owner
> Fix UI toolchain dir permissions error

- backend/Dockerfile
The import path for golint has changed
Fixes #3388
> build: Fix import for golint

- probe/probe.go
Fixes #3150 
Rate-limit report publishing so that, if many shortcut reports are produced in quick succession, they will tend to get merged together before sending.
Also expand the queue size for shortcut reports, to avoid holding up the producer so much.
The behaviour of the Go rate-limiter with a burst size of 1 is that it will let 1 report go through immediately, then the next one will wait until the time specified (300ms by default).  If nothing happens for more than 300ms the next report will go immediately, and so on.
> Probe: Rate-limit report publishing

- probe/kubernetes/reporter.go
We were filtering pods to those on the local node already, for regular reports, so we should also filter events that come in asynchronously.
Problem noted at https://github.com/weaveworks/scope/issues/3150#issuecomment-429563114
> Discard pod updates for other nodes

- docker/Dockerfile.cloud-agent
- docker/Dockerfile.scope
- Moves the `weave` and `weaveutil` from `Dockerfile.cloud-agent` to
`Dockerfile.scope`
- Fixes #3341
> Remove weaveutil and weave from Dockerfile.cloud-agent

- probe/process/walker_linux.go
If the state is reported as dead or zombie, return an error so the process will be skipped.
This will fix the direct cause of the situation described at #3330
> Probe: Don't report dead or defunct processes

- probe/host/tagger.go
- probe/kubernetes/reporter.go
- probe/kubernetes/reporter_test.go
- prog/main.go
- prog/probe.go
- render/pod.go
This set of changes allows you to configure the probe on each node with Kubernetes probing disabled, and run one extra probe with Kubernetes enabled and processes, containers, etc., disabled. This is quite simple to arrange with one DaemonSet and one Deployment.
Benefits:
* less impact on the Kubernetes api-server
* less work on each node gathering and reporting the data in each probe
* less work in the app to merge N copies of identical nodes
* less network traffic to send them to the app.  
Disappointingly the CPU-usage benefit wasn't huge when I tried it in our staging cluster, but I didn't spend long looking at why.
It has one disruptive change: pods never get tagged with a host-id.  The rendering code is changed to find this on a container node. When reporting Kubernetes on just one …
> Enable Kubernetes objects to be reported just once in a cluster

- examples/k8s/cluster-role.yaml
- examples/k8s/deploy.yaml
- examples/k8s/ds.yaml
- Change `apigroups` to `apiGroups` in cluster-role.yaml
- Change `resourcenames` to `resourceNames` in cluster-role.yaml
- Add `selector` in deploy.yaml and ds.yaml
Signed-off-by: Akash Srivastava <akash.srivastava@openebs.io>
fixes: #3400
> Fix issues in k8s yaml files

- client/app/scripts/components/node-details.js
The message is now more friendly as requested!
Fixes #2879
> client: update stopped container message

- app/multitenant/aws_collector.go
- prog/app.go
- prog/main.go
- report/report.go
As a protection against overloading the app server, drop topologies that have really large node counts. In practice we only see this with runaway numbers of zombie processes.
I've only wired this in to the AWS collector, since that is where we felt the pain.
Also some refactoring of the AWS collector parameters where the duplication started to get annoying.
> In multitenant app, drop all nodes for big topologies

- prog/probe.go
When the probe is run with `--probe.kubernetes.role=cluster`, disable host reporting and endpoint reporting since it duplicates what is being done by the per-host probe.
This was missed from #3274
> Disable host and endpoint reporting in Kubernetes cluster mode

- docker/Dockerfile.cloud-agent
- docker/Dockerfile.scope
Changed `--update` & removing the apk cache to using the `--no-cache` flag, which just installs the newest version of the packages without caching any information.
Changed `ADD` to `COPY`, because they are not archives, which have to be unpacked after adding them. In general it is not encouraged to use `ADD` for just copying files into the image, because of the overloaded functionality of `ADD`.
> Clean up Dockerfiles

- probe/cri/registry.go
- probe/cri/registry_test.go
Hey all 👋,
First of all, thank you for making such a great project! Found it via Hacktoberfest and immediately jumped into the bandwagon for helping out. Love the current organisation/labelling of the issues. Super helpful for us newcomers.
Figured I should get this PR out sooner rather than later to start getting some feedback. While stressing the different code paths with the tests, I noticed there was one case that no matter what I do, I couldn't get an error to bubble up: The case where the scheme is `""`. 
I'm not sure if this is some sort of 🐞 or am I missing something (?), but I ended up refactoring (to the best of my _very_ limited Go knowledge and understanding of the project) some bits to make it so that it complies with what I _think_ the intention was.
From what I read, the …
> Fix intention of support for fallback protocol and add tests for probe/cri/registry 

- MAINTAINERS
@fbarl has made 137 PRs on Scope, which easily justifies his position as a maintainer.
CC @2opremio and @satyamz as other current maintainers
> Add Filip Barl as maintainer

- probe/kubernetes/reporter.go
- render/theinternet.go
This is to address an inconsistency introduced by #3274, reporting Kubernetes info from a cluster-level probe, and removes a lie from the probe data.
Suggested at https://github.com/weaveworks/scope/pull/3428#issuecomment-439064091
Rather than do the work every time the probe sends a report, we do it every time the app renders endpoints, which should be once per merged report set.
Replaces #3428
> Move "hideous hack" for Kubernetes service network from probe to app

- client/webpack.production.config.js
This can cause an empty static UI if things build in an unfortunate order.
Fixes #3438
> UI Build: stop deleting static ui files when building external ui

- prog/probe.go
It is essential for rendering many node types, so lift it out of the condition on Kubernetes cluster mode.
Fixes #3443
> Add TopologyTagger in all modes

- render/persistentvolume.go
If a pod has no VolumeClaim set, just move on to the next pod.
Eliminates small waste of time.
> Don't look for blank volume claims when rendering

- site/faq.md
Follow up from https://github.com/weaveworks/scope/pull/3417#pullrequestreview-178245830.
I added all the entries that I thought were relevant for Scope OSS. I've updated some of the entries here compared to Notion, so I'm gonna update it there after this gets merged :)
> Populate FAQ with more questions from Weave Cloud Notion's knowledge base

- integration/100_launch_test.sh
Should detect the symptom at #3438
> Add a check that the top-level UI is not empty

- render/persistentvolume.go
- Name of the PVC can be the same in different namespaces, in this
scenario an application pod is connected to multiple PVC.
- Add adjacency between Pod and PVC when `claim name` and `namespace` are same.
Signed-off-by: Akash Srivastava <akash.srivastava@openebs.io>
> Add adjacency between Pod and PVC when claim name and namespace are same

- probe/docker/container.go
So that Scope numbers match Docker numbers.
See https://success.docker.com/article/the-docker-stats-command-reports-incorrect-memory-utilization
Related: #1133, #3376
> Subtract page cache from container memory usage

- client/app/scripts/components/cloud-link.js
- client/app/scripts/components/node-details/__tests__/node-details-health-link-item-test.js
- client/app/scripts/utils/web-api-utils.js
- prog/main.go
- render/detailed/links_test.go
- Renames placeholders `:orgId` to `:instanceId` in
`--app.metrics-graph`
- Adjusts frontend client to use the provided instanceId by its host
application (Weave Cloud)
> Rename :orgId to :instanceId in metrics graph url

- tools/README.md
- tools/build/golang/Dockerfile
- tools/scheduler/README.md
- tools/scheduler/main.py
- tools/scheduler/requirements.txt
- tools/socks/main.go
Import new build-tools instead of changing `tools/README.md` (https://github.com/weaveworks/scope/pull/3545).
> Import new build-tools instead of changing tools/README.md

- Makefile
`yarn` will otherwise complain about missing `client/package.json` in "make client-test"
Signed-off-by: Daniel Holbach <daniel@weave.works>
> Fix bind-mount volume path "client/client"

- probe/kubernetes/pod.go
- render/persistentvolume.go
Read all the PVC source from a pod spec
and add adjacency between the pod and its PVCs.
Signed-off-by: Akash Srivastava <akashsrivastava4927@gmail.com>
fixes: #3550
> Fix one pod to multiple PVC connection

- site/faq.md
- site/installing.md
Move docs about our local k8s deploy manifest from FAQ to `installing.md`. Still provide a reference.
> move local k8s install steps to installing.md

- client/app/styles/_base.scss
Fixes #3555 
Applied the hover effect to the last child to fix the other above sidebar nodes to remain constant and to improve experience through all the browsers. 
Signed-off-by: A V RAHUL  a.v.rahul11@gmail.com
> Fixed the sidebar namespaces hover effect at last-child

- client/package.json
- client/yarn.lock
Updating xterm.js because of https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-0542
> update xterm.js dependency (CVE-2019-0542)

- client/package.json
- client/yarn.lock
Update to latest lodash release, c.f.
- https://nvd.nist.gov/vuln/detail/CVE-2018-16487
- https://hackerone.com/reports/380873
> fix CVE-2018-16487 (lodash vulnerability)

- CHANGELOG.md
- examples/cri/deploy.yaml
- examples/cri/ds.yaml
- examples/docker/docker-compose-probe-v1.yml
- examples/docker/docker-compose-probe-v2.yml
- examples/k8s/deploy.yaml
- examples/k8s/ds.yaml
- examples/mesos/minimesos.json
- site/installing.md
This release has a security fix, a few bug-fixes and some other minor
improvements.
Special thanks to arnulfojr, Akashtic, AVRahul, carlosedp, ycao56
for community contributions!
Security and bug fixes:
- Address vulnerability (CVE-2019-0542) by updating xterm.js dependency
[#3557](https://github.com/weaveworks/scope/pull/3557)
- Fix missing nodes in Kubernetes Cluster mode
[#3444](https://github.com/weaveworks/scope/pull/3444)
- Show all connections when one pod has multiple PVCs
[#3553](https://github.com/weaveworks/scope/pull/3553)
- Fix spurious connection to PVC with same name in different namespace
[#3530](https://github.com/weaveworks/scope/pull/3530)
- Fix linkage from metrics graph to external monitoring url
[#3534](https://github.com/weaveworks/scope/pull/3534)
- Fix build mount …
> Release 1.10.2

- client/app/scripts/components/node-details/node-details-control-button.js
- client/app/scripts/components/node-details/node-details-controls.js
- probe/kubernetes/reporter.go
- render/detailed/node.go
- report/controls.go
Resolves #3548.
On the UI side I used the native `window.confirm` dialog which is generally not encouraged, but is the quickest way of solving the issue at hand. If this becomes a more common pattern, we should put more thought in what sort of component we want to replace it with.
> Add a confirmation dialog for deleting a pod.

- site/faq.md
Resolves #3531 by filling in the missing info from #3453.
> Extend FAQ with basic auth through env variables

- examples/k8s/ds.yaml
- examples/k8s/probe-deploy.yaml
We stop the per-host probes talking to Kubernetes and run an extra Deployment with one more probe process to collect all information for the cluster, which is less resource-intensive overall.
This feature was added at #3274
(I haven't tried this exact config on a cluster yet; publishing for visibility and if someone else wants to test it)
> Update example yamls to probe Kubernetes once per cluster

- examples/k8s/deploy.yaml
- examples/k8s/ds.yaml
If you don't specify, the default is typically 0 which (a) gives the Kubernetes scheduler a false idea of expected usage and (b) makes the Linux scheduler penalise Scope processes under contention.
For best results adjust the figures here after observing actual usage on your cluster.
> Add CPU and memory requests to example Kubernetes manifests

- client/.babelrc
Follow-up to #3580.
This change makes babel in `build-pkg` script fully transform the JS files to make them more compatible when imported from Weave Cloud.
> Fix build-pkg script

- examples/cri/ds.yaml
- examples/k8s/ds.yaml
Fixes #3544 (at least the part that I could find to fix)
Kubernetes sets up a lengthy DNS search path, so any names are looked up multiple times. Adding a dot at the end tells the DNS resolver the name is absolute, and should not be tried against the search path.
This will reduce pointless DNS lookups.
> Add a dot to make DNS names absolute

- client/app/scripts/components/zoomable-canvas.js
I use a new method to bind wheel event.
https://www.chromestatus.com/features/6662647093133312
Fixes #3592
> Fix bug 56+ chrome can't prevent default wheel events.

- client/package.json
- client/yarn.lock
We are not using it at all and we've received security warnings for it:
> Remove materialize-css JS dep

- probe/endpoint/dns_snooper.go
- probe/endpoint/dns_snooper_test.go
Hello,
Playing with scope I noticed a bug where the dns snooper does not identify some external hosts. Digging a bit deeper I found the faulty pattern - if there are multiple CNAMEs in a record but only one of it has a corresponding A address then the match will not be done. Here's an example:
```
100.x.x.x.domain > 100.y.y.y.54637: 34745 3/0/0 graph.facebook.com. CNAME api.facebook.com., api.facebook.com. CNAME star.c10r.facebook.com., star.c10r.facebook.com. A 31.13.66.4 (174)
```
For this frame the outbound calls from my service to `graph.facebook.com.` where never caught.
The fix I considered goes through all the CNAME records and builds a list of aliases. Let me know what you think.
P.S. Scope is awesome, thanks for building it!
> Fix dnssnooper probe for multiple CNAMEs.

- app/benchmark_internal_test.go
- app/collector.go
- app/multitenant/s3_client.go
- app/router.go
- extras/copyreport/main.go
- report/marshal.go
- report/marshal_test.go
So we can see the timing and size in Jaeger.
> Add OpenTracing span for report.ReadBinary()

- app/multitenant/aws_collector.go
In a multitenant system it is useful to be able to drill into which tenants have the most or biggest reports.
> Add metrics for report size and count per tenant

- client/package.json
- client/yarn.lock
- examples/k8s/cluster-role.yaml
- probe/kubernetes/client.go
- probe/kubernetes/controls.go
- probe/kubernetes/job.go
- probe/kubernetes/reporter.go
- probe/kubernetes/reporter_test.go
- render/detailed/summary.go
- render/pod.go
- render/selectors.go
- report/id.go
- report/report.go
- Implementation of the Job kubernetes resource in probe
- Reporter changes for the Job
- Add Describe Control to the Job
- Pass Job object to the kube controller renderer
- ~Need to decide the shape for the Job.~
fixes: #3362 
Signed-off-by: Satyam Zode <satyamzode@gmail.com>
> Add Kubernetes Job support to Weave Scope

- CHANGELOG.md
- site/installing.md
See [CHANGELOG.md](https://github.com/weaveworks/scope/pull/3610/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1e) for the list of changes.
* Contrast mode not persisted properly in the URL #3611 
* Building with `make` puts too strong permissions on client assets #3612
> Release 1.11.0

- probe/docker/registry.go
Fixes #3576 
Previously it would only delete if Docker said the container didn't exist, which is a race between Docker sending the event and Docker removing the info from its own records. If Scope lost the race it would never check again, so the set of containers grows and grows.
Extract a couple of functions to make the action clearer.
> Always delete container info when we get a 'destroy' event

- probe/docker/registry.go
Fixes #3576 (I know, we've been here before...)
Event notifications from Docker have been seen to get dropped; using a buffered chan seems to reduce the chance of this happening.
> fix(probe): Use a buffered chan to reduce the chance of losing events

- probe/endpoint/conntrack.go
In particular, ENOBUFS which indicates data has been dropped.
With this change the collector will restart, thus resynchronising with the OS.
I believe this is the cause of #3645
> fix: handle errors reported by the conntrack package

- probe/endpoint/reporter.go
- probe/endpoint/reporter_linux.go
The call to register this metric was removed in #633 over three years ago.
If it isn't registered then nobody can see the values.
The measurement is duplicated by metrics added in #658.
> fix: remove unused metric SpyDuration

- app/multitenant/aws_collector.go
- app/multitenant/memcache_client.go
- app/multitenant/s3_client.go
- app/multitenant/sqs_control_router.go
- prog/app.go
This avoids app-specific metrics appearing in the probe.
> Defer metrics registration until we need it

- vendor/github.com/weaveworks/tcptracer-bpf/pkg/tracer/event.go
- vendor/github.com/weaveworks/tcptracer-bpf/tests/tracer.go
- vendor/manifest
Fixes #2827
Needs the [upstream PR](https://github.com/weaveworks/tcptracer-bpf/pull/67) to be merged then vendor that change here.
The idea is described at https://github.com/iovisor/gobpf/issues/42#issuecomment-508500065 but no response in that repo so I'm making the change in a weaveworks-controlled repo.
> fix(probe): Avoid ebpf events out of order by adding offset to time

- probe/probe.go
1. Adding reporter name to logs improves tracing of error.
2. Capitalize first letter of error log.
Fixes https://github.com/weaveworks/scope/issues/3306
Signed-off-by: Prince Rachit Sinha <prince.rachit@mayadata.io>
> refactor(logs): Add reporter name to error logs.

- README.md
- site/installing.md
- site/plugins.md
Trying to improve the situation at #3624 and #2814 
Also drive-by removal of `boot2docker` since it's ancient history and complicates the instructions.
> Docs: improve the warning about opening Scope to the Internet

- probe/endpoint/connection_tracker.go
- probe/endpoint/conntrack.go
- probe/endpoint/ebpf.go
Fixes #3645 
Restarting the thing every six hours is somewhat heavy-handed, but I couldn't find an underlying cause and this will remove the pain for the users affected.
Also loosen the parameters around ebpf restarts, so we will tend to use ebpf more and conntrack less. Continuation of #3653.
> Reduce leaks in probe endpoint reporter

- app/multitenant/aws_collector.go
Cache merged groups of reports, to reduce the number we handle in parallel.
Previously we would merge all reports in a 15-second window. Now we use a 'quantum' of 3 seconds, similar to the single-user app.
E.g. a 30-node cluster will have 150 individual reports over 15 seconds, but the new code will merge 5 pre-merged reports plus 20-ish very recent individual ones.
This reduces the max heap size used for deserialising, since we only do 3 seconds at once per instance. This improves #3256, but I'm not marking it as a fix since the number done in parallel is still unlimited.
Individual reports are still put into the cache, but should get displaced by the pre-merged ones under LRU.
> Quantise report cache in query side of aws-collector

- client/app/scripts/utils/string-utils.js
- Should be "45MB"
- Seems like the filesize lib subtley changed their API
Fixes #3672
> Fixes "45undefined" in node memory overlay

- app/api_report.go
- probe/docker/container.go
- probe/docker/registry.go
- probe/docker/registry_test.go
- probe/docker/reporter.go
- probe/docker/reporter_test.go
- probe/host/reporter.go
- probe/kubernetes/pod.go
- probe/kubernetes/reporter.go
- probe/overlay/weave.go
- probe/overlay/weave_test.go
- render/container.go
- render/container_test.go
- render/detailed/node_test.go
- render/detailed/summary_test.go
- render/expected/expected.go
- render/filters.go
- render/persistentvolume.go
- render/pod.go
- render/pod_test.go
- render/process.go
- render/short_lived_connections_test.go
- render/theinternet.go
- render/theinternet_test.go
- render/weave.go
- report/id.go
- report/map_keys.go
- report/map_values.go
- test/fixture/report_fixture.go
This dependency makes it harder to see the structure of the program, and sometimes complicates compilation.
Mostly just changing the source of strings that are already exported from the `report` package.  A few new strings have to be moved there, plus the function `IsPauseImageName()`.
> Stop render package depending on probe

- .github/CODEOWNERS
The [docs](https://help.github.com/en/articles/about-code-owners) say the format is pattern followed by one or more owners.
What we had previously was multiple patterns all the same, so it takes the last one.
> fix(github): give all code owners equal weight

- probe/appclient/app_client_internal_test.go
- probe/probe_internal_test.go
- report/topology.go
So we save space writing out empty topologies, which we see more often after #3677.  Very small impact overall.
Need to fix up `app_client_internal_test.go` to use Scope's `test/reflect` package that understands empty==nil, so now it doesn't need a previous workaround.
Remove a similar workaround in `probe_internal_test.go` that isn't necessary since it's already using that package.
> perf(probe): add 'omitempty' tag to Topology.Nodes

- app/api_topology.go
- app/multitenant/aws_collector.go
Since the http call lasts forever, the spans for it don't appear.
Instead, start a new root span every time round the loop (which is typically every 5 seconds).
For the multitenant case it's useful to have a tag with the userid.
> Websocket tracing spans

- extras/generate_latest_map
- probe/probe.go
- probe/probe_internal_test.go
- prog/main.go
- prog/probe.go
- report/id_list.go
- report/latest_map_generated.go
- report/node.go
- report/report.go
- report/report_test.go
- report/topology.go
Similar to video compression which uses key-frames and differences between them: every N publishes we send a full report, but inbetween we only send what has changed.
Fairly simple approach in the probe - hold on to the last full report, and for the deltas remove anything that would be merged in from the full report.
On the receiving side in the app it already merges a set of reports together to produce the final output for rendering, so provided N is smaller than that set we don't need to do anything different.
Deltas don't need to represent nodes that have disappeared - an earlier full node will have that node so it would be merged into the final output anyway.
Results from a small test showed around 40% drop in bytes/second sent by probes - process and container metrics are still …
> perf(probe): publish delta reports to reduce data size

- app/collector.go
- app/multitenant/aws_collector.go
- app/router.go
- prog/app.go
- report/report.go
- site/faq.md
When someone says they have a performance problem, the first thing I want to know is whether Scope is reporting 26,000 processes on a node, or similar.  It's awkward to do that via the raw reports, so I wrote this summarising function you can call via URL `/admin/summary`
Example output:
```
pod:183, service:81, deployment:87, daemon_set:8, stateful_set:2, cron_job:5, namespace:14, persistent_volume:3, persistent_volume_claim:4, storage_class:1
ip-172-20-2-197;<host>:endpoint:992, process:369, container:101, container_image:41, host:1, overlay:1
ip-172-20-1-59;<host>:endpoint:266, process:250, container:43, container_image:15, host:1, overlay:1
ip-172-20-3-247;<host>:endpoint:891, process:383, container:107, container_image:43, host:1, overlay:1
```
> feature(app): Add a debugging summary function, exposed via http

- report/controls.go
- report/metric_row.go
- report/metrics.go
Scope stopped using `NodeControls` in bd43c34852ea, and since 1cfc8f458136 `WireMetrics` is identical to `Metrics` so unnecessary.
> refactor: remove old unnecessary controls code

- probe/docker/registry_test.go
Fixes #3209 (again)
This is a different race to last time: reading the result just once when they are written on a separate goroutine by `WatchContainerUpdates` was always a bit hopeful.
> fix(test-flake): poll for result in TestRegistryDelete() to avoid race

- extras/example/k8s/app-deployment.yaml
- extras/example/k8s/client-deployment.yaml
- extras/example/k8s/echo-deployment.yaml
- extras/example/k8s/elasticsearch-deployment.yaml
- extras/example/k8s/frontend-deployment.yaml
- extras/example/k8s/qotd-deployment.yaml
- extras/example/k8s/redis-deployment.yaml
- extras/example/k8s/search-deployment.yaml
- probe/kubernetes/client.go
- probe/kubernetes/cronjob.go
- probe/kubernetes/daemonset.go
- probe/kubernetes/deployment.go
- probe/kubernetes/reporter_test.go
- probe/kubernetes/statefulset.go
The latest Kubernetes release, 1.16, no longer serves the v1beta1 APIs by default.
Scope will no longer work with Kubernetes 1.8 and below.
> Move to Kubernetes 'v1' APIs

- app/benchmark_internal_test.go
- app/collector.go
- app/multitenant/memcache_client.go
- app/multitenant/s3_client.go
- app/router.go
- report/marshal.go
- report/marshal_test.go
There was a lot of duplication and confusingly-similar functions.
> Refactor report reading

- app/api_topology.go
- probe/awsecs/reporter.go
Not sure why these slipped past the lint tools we currently use.
> chore: fix typos in debugging format strings

- probe/docker/container.go
- probe/docker/reporter.go
- probe/endpoint/connection_tracker.go
- probe/endpoint/ebpf.go
- probe/endpoint/ebpf_test.go
- probe/endpoint/four_tuple.go
- probe/endpoint/nat.go
- probe/endpoint/procspy/proc_linux.go
- probe/endpoint/procspy/spy.go
- report/id.go
This is more compact, and in some cases the code was converting to a string then parsing back to an IP address again so we save effort by deferring the conversion.
> handle IP addresses in binary rather than strings

- prog/main.go
- prog/probe.go
I wanted to do this to get rid of debug-level log messages every few seconds, but it might also be desirable to reduce attack surface.
> feature: allow user to disable plugins via command-line flag

- client/app/scripts/components/global-style.js
- client/app/scripts/fonts.js
- client/app/scripts/main.dev.js
- client/app/scripts/main.js
Importing Scope fonts seems to not have worked even before #3700, but it wouldn't fail loudly. It makes sense that the parent app should enforce the fonts on all its components, including Scope when it gets injected.
There should be no visible changes to Scope standalone with this PR.
> Import fonts only in Scope standalone

- probe/appclient/app_client.go
Previously it would try to run the JSON decoder on a string like "404 not found" and report that failing with the message "Error fetching app details: only encoded map or array can be decoded into a struct".
Now it will report the http error, like this:
```
<probe> ERRO: 2019/10/06 17:00:42.290708 Error fetching app details: Error response from http://172.16.0.3:4040//api: 404 Not Found
```
Fixes #3249
> fix: report http error if /api call fails

- extras/example/k8s/elasticsearch-deployment.yaml
> Fix for ImagePullBackOff error when running the k8s example

- .circleci/config.yml
- Builds are failing because CI is not able to login to docker
because -e (email) flag is deprecated.
Signed-off-by: Akash Srivastava <akashsrivastava4927@gmail.com>
> Remove -e flag from docker login

- Makefile
We are building ui-dist in make using docker image of nodejs after building dist it put those dist in build or build-external folder. These folders are created by docker run under root user. After make if we try to build it locally by yarn build it tries to delete build folder from `$USER` user thats why we are getting permission error.
```bash
shovan@probot:~/Desktop/workspace/src/github.com/weaveworks/scope/client$ ls -l
total 420
drwxr-xr-x    7 shovan shovan   4096 Jun 12 15:46 app
drwxr-xr-x    2 root   root     4096 Jun 13 00:42 build
drwxr-xr-x    2 root   root     4096 Jun 13 00:37 build-external
-rw-r--r--    1 shovan shovan    608 Jun 12 15:46 Dockerfile
drwxr-xr-x 1016 shovan shovan  36864 Jun 13 00:36 node_modules
-rw-r--r--    1 shovan shovan   4642 Jun 13 00:29 package.json …
```
> [fix] [make] update ui build to avoid yarn build fail after make.

- report/report.go
In commit 951629af292a (part of #3677) the `DNS` field was accidentally renamed in serialised data to `nodes`.  Put it back, and also add a field to fix up data coming from a probe with that fault.
🤦‍♂
> Fix accidental rename of DNS to 'nodes'

- app/multitenant/aws_collector.go
Shortcut reports are sent to update the UI quickly, on events like a container starting. 
We don't need to persist them in the time-travel data since the same information will be covered by a regular report a few seconds later.
> performance(aws_collector): don't persist shortcut reports

- examples/k8s/probe-deploy.yaml
- Mount the plugin volume to deployment
Fixes https://github.com/weaveworks/scope/issues/3667
> (fix): Mount plugin volume to weave-scope-cluster-agent resource

- probe/endpoint/connection_tracker.go
Fixes #3711 
If we run `getInitialState()` async there is some chance we will see another ebpf failure and call `useProcfs()` before `getInitialState()` gets to the last line, whereupon it will crash on nil pointer.
Also it seems pointless to call `performEbpfTrack()` without waiting for something to feed in, so I suspect this is what the original author had in mind.
It will slow down this one `Report()` on machines with a lot of processes or connections, but `EbpfTracker` restart is supposed to be a rare event.
> fix(probe/ebpf): feed initial connections synchronously on restart

- client/yarn.lock
An attempt to stop GitHub screaming at me about [critical vulnerabilities](https://github.com/weaveworks/scope/network/alerts)
I used [yarn-deduplicate](https://github.com/atlassian/yarn-deduplicate).  I have no idea what I am doing.
> Consolidate all lodash versions to 4.17.15

- probe/kubernetes/pod.go
- kubectl way - 
```
if pod.DeletionTimestamp != nil {
reason = "Terminating"
}
```
Fixes: #3554 
Signed-off-by: Sumit Lalwani <sumit.lalwani97@gmail.com>
> Update pod status to terminating

- probe/appclient/app_client_internal_test.go
- probe/appclient/probe_config.go
Added the "user-agent" header with the value: "Scope/1.11.6" and added a test for it.
Fixes #3715.
> Adding the "user-agent" Header

- examples/k8s/cluster-role.yaml
Apparently `daemonset` was missed in the update from `v1beta1` to `v1`; also we need `get` and `update` on `deployments/scale`.
(I am a bit confused why nobody has pointed this out before)
> Add more rbac permissions in the 'apps' group

- client/yarn.lock
Does the same #3721 did with two additions:
* I ran it on a current fresh master
* The `integrity sha512-` bits weren't removed
I gave it a smoke test with `yarn start` and it seems to be idempotent under `yarn install` now so things look good :+1:
> Dedupe yarn.lock

- probe/kubernetes/reporter.go
- probe/kubernetes/reporter_test.go
- render/filters.go
Dockershim has added a label `io.kubernetes.docker.type` for at least four years, where the pause container is of type `podsandbox`.  This should be more reliable than trying to keep up with everyone's name for the pause container.
I don't like the way we do this in two places (one probe, one app), but it seemed a bit complicated to unwind that right now.
I left in the old name-based code just in case; I don't think it is necessary any more.
> kubernetes: detect more 'pause' containers

- integration/321_many_connections_2_test.sh
- integration/config.sh
- probe/endpoint/connection_tracker.go
- probe/endpoint/connection_tracker_test.go
- probe/endpoint/ebpf.go
- probe/endpoint/ebpf_test.go
- render/detailed/connections.go
- report/map_keys.go
Fixes #3584 
The app will only show one line, regardless of how many connections we have, so reduce the number we send to save bandwidth and rendering time. Include a note of how many connections were elided in the report, so the app can still show the same number in the detail window.
I've only done this for the ebpf collector for now.  
We collect the details by "triple" of (source address, destination address, destination port), recording what we know about the source or destination pid, then where there are more than 5 connections going to the same endpoint, all for the same process, we thin them down using a modulus.
Inspired by the discussion at https://github.com/weaveworks/scope/pull/3452#pullrequestreview-179371870
Note this is a (minor) breaking change in the protocol: older …
> Report a subset of connections from/to the same endpoint

- render/container.go
`ContainerImageRenderer`: Crunch a `Map` and `Reduce` into a single `Renderer` that has the same function.
`ContainerHostnameRenderer`: The second half of the render added all the same nodes, except for
those with no Docker image information, so we could show a figure for those filtered out on that basis. This just isn't worth the effort.
And remove unused parameterisation of `containerWithImageNameRenderer`
> Simplify some renderers

- app/multitenant/billing_emitter.go
Use the duration supplied, if there is one.
It was looking for a process named "scope-probe", whereas the executable is just named "scope".
> Improve calculation of usage in multitenant code

- app/collector_test.go
- probe/plugins/registry.go
- probe/probe.go
- probe/probe_internal_test.go
- render/theinternet_test.go
- report/report.go
We had a `Window` field but it was never filled in.
And it seems natural to me to give the timestamp so you understand the beginning and end time it covers.
Some refactoring to remove `Report.Merge()` so I only worry about merging timestamps in one place.
> Set timestamp and window on each report

- client/app/scripts/utils/__tests__/string-utils-test.js
- client/app/scripts/utils/string-utils.js
Added ~ option to d3Format which trims trailing zeros across format types.
Fixes #3741
> Remove trailing zeros in large numbers in UI

- probe/appclient/resolver.go
There's no reason to expect anyone is changing their DNS that fast, and the probe queries all endpoints every time it polls so slowing down will reduce effort.
> Slow down DNS poll interval

- client/package.json
- client/yarn.lock
I updated five listed on https://github.com/weaveworks/scope/network/alerts:
minimist, acorn, set-value, mixin-deep, sshpk
I did not update clean-css because I believe it's only used at build time.
All changes are point versions only.
I ran `yarn-deduplicate` as in #3733 prior to starting, and after each change.
> security: update JS dependencies which have notified vulnerabilities

- backend/Dockerfile
I figured before making Scope release 1.13 I should update Go to the latest patch release.
Will look at moving to Go 1.14 after release.
> Update Go to 1.13.9

- docker/Dockerfile.cloud-agent
Note I'm pinning the minor version here, otherwise it can vary depending on what's on your machine when you build.
Replaces #3767
> Update alpine base image to 3.11.3

- app/collector.go
- app/multitenant/aws_collector.go
- app/multitenant/billing_emitter.go
- app/router.go
Previously the code called `time.Now()` in two different places so the timestamps didn't match. 
Now we use the timestamp of the report itself.
Add the collector's local time to the report if it didn't have one.
> fix (multitenant collector): Use consistent report timestamp

- app/collector.go
- app/multitenant/aws_collector.go
- app/multitenant/billing_emitter.go
- app/router.go
This reverts #3773 
The app merges reports within a 15-second window of its own time, so if one or more probes have a time that is several seconds different they will get excluded from the window.
> Revert #3773 - change to use report timestamp

- probe/probe.go
If the probe is configured with `spy.interval` greater than `publish.interval`, the report to be published can be completely blank.  
In that case, skip publishing it so the next time we do have some data the time-window is correct.
> fix (probe): skip publishing empty reports

- app/multitenant/consul_pipe_router.go
- app/pipes.go
- common/xfer/pipes.go
- probe/appclient/app_client.go
- probe/docker/controls_test.go
Fixes #3684
Move the check for `IsExpectedWSCloseError()` inside `CopyToWebsocket()` and only do the check on the websocket side.
Previously we were treating EOF on the non-websocket side of the conversation as no-error, meaning that operations like Kubernetes Describe would retry endlessly when finished.
> Stop pipe operations after EOF

- bin/release
If it is `--draft --pre-release` then we need to pass that unquoted so it is seen as two arguments.
> Don't quote RELEASE_ARGS which may contain two arguments

- app/multitenant/billing_emitter.go
- app/multitenant/billing_emitter_test.go
In most cases there will be fewer containers than processes, so we can get the answer faster.
Also this works in the case where process-scanning has been turned off.
> multitenant: scan container command-lines as well as process

- examples/k8s/psp.yaml
With reference to blog from [Kubernetes](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/)
**PodSecurityPolicy** (in the **extensions/v1beta1** API group)
Migrate to use the **policy/v1beta1** API, available since v1.10. Existing persisted data can be retrieved/updated via the policy/v1beta1 API.
This PR fixes this.
> Fixed example for PodSecurityPolicy inside examples/k8s/psp.yaml

- app/multitenant/aws_collector.go
We have a limit of (by default) 10,000 nodes per topology, but when a report has been merged from several probes it's much more likely to hit this limit.  Apply a heuristic to use a higher limit.
Also fix the metric that was supposed to show problems like this, but wasn't registered.
> multitenant query: don't drop topologies so much

- integration/312_container_to_container_edge_same_netns_test.sh
Continuing the tradition of #2103 and #2554. 
This was causing [integration test failures](https://circleci.com/gh/weaveworks/scope/15424) because the container was connecting to `::1` and Scope ignores ipv6 connections.
> fix (integration tests): replace localhost with 127.0.0.1 

- app/api_report.go
- app/api_topologies.go
- app/api_topology.go
- app/controls.go
- app/pipes.go
- app/router.go
- app/server_helpers.go
- render/filters.go
- render/render.go
Typically this means the http caller has closed the connection, so no point responding to them.
Also check at the point we send a response back, and log to OpenTracing.
> improvement: stop rendering if Context is cancelled

- app/multitenant/billing_emitter.go
- app/multitenant/billing_emitter_test.go
If spy interval is higher than publish interval, some reports will have no process data, so use the spy interval for billing purposes.
> billing: cope with spy-interval set longer than publish-interval

- examples/cri/cluster-role.yaml
- examples/k8s/cluster-role.yaml
This PR is intended to fix the issue mentioned in [this](https://github.com/weaveworks/scope/issues/3805#issuecomment-652585371) comment.
**Issue:** The serviceaccount - weave-scope don't have permission to list resource "namespaces" in API group "" at the cluster scope.
**Fix:** Have updated the cluster role to include listing of `namespaces` resource.
> Updating cluster-role.yaml to fix rbac

- integration/315_ebpf_restart_test.sh
- scope
This gets over a problem with Docker for Mac where `/var/run` is read-only.
Now, anyone wishing to use Scope plugins will have to ensure that directory (where the sockets used to communicate between Scope and plugins live) exists.
I'm not clear whether it is ever possible under Docker for Mac to create the `/var/run/scope/plugins` directory the code is looking for, or whether it will be necessary to parameterise the code.
Also fix the Mac probe launch command - paren in wrong place meant it was running the app and not getting any extra args
> Only mount plugins directory if it exists

- examples/k8s/ds.yaml
- scope
This will allow the app to match up data from node and cluster probes, e.g. for #3822
> Set hostname to Kubernetes node name

- site/faq.md
Someone's text editor has made this `U+2014 : EM DASH` instead of a double-dash. Closes #3835
> Update faq.md - fix read-only mode gotcha

- backend/Dockerfile
- tools/build/golang/Dockerfile
github.com/fatih/hclfmt was archived. Technically there is a possibility to fork (or used another forked version) to executle hclfmt.
But it leads to another issues - problems with importing https://github.com/hashicorp/hcl/hcl/printers. HCL was released in version 2 so that the file structure was changes.
I do not see any way to install it in changed Makefile. Go installs does not support pining to given tags so that always the newest version is installed.
For now, the impact on build process should be minimal. it is used only in ./tools/lint/lint() method. I was able to execute it locally without executing hclfmt.
> Remove obsolete dependency github.com/fatih/hclfmt

- docker/Dockerfile.cloud-agent
Update alpine 3.11 to latest patch version.
It would make more sense at this point to update to 3.13, let me know if you want make to make the change. 
Change log for 3.11.8: https://alpinelinux.org/posts/Alpine-3.10.6-3.11.8-3.12.4-released.html
> Update alpine base image to 3.13

- .circleci/config.yml
- Makefile
The change in #3833 to stop installing Python in the build container means we can no longer just `pip install aws-cli`.
Instead, use the official AWS image to run it.
Need to run in 'machine' executor on CircleCI so we can mount volumes into the Docker container.
Note that `setup_remote_docker` spins up a VM anyway, so this is probably more efficient.
> Run AWS CLI from a container image

- app/api_report.go
- app/multitenant/aws_collector.go
- app/multitenant/collector.go
- app/server_helpers.go
- go.mod
- prog/app.go
- prog/main.go
- report/marshal.go
- vendor/modules.txt
Fixes #3783 
Collectors hold recent reports in memory; when querier needs 'live' data, it fetches it from collectors instead of from the long-term store.
This means queriers get more up-to-date data, by the store-frequency collector was using (e.g. 2 seconds), and we can slow down that frequency to spend less on S3/DynamoDB.
Included in this change: multitenant collector now always saves async - removed support for saving all reports immediately to store.
> Multitenant mode: fetch live data from collectors

- render/render.go
These can be long-running operations, and if the client retries we get the cancelled one running in parallel with the retry, slowing both down and making it likely the next one will time out too.
> Break out of Map.Render loop if context cancelled

- render/container.go
- render/endpoint.go
- render/filters.go
- render/host.go
- render/pod.go
- render/process.go
- render/render.go
Similar to #3848 
These can be long-running operations, and if the client retries we get the cancelled one running in parallel with the retry, slowing both down and making it likely the next one will time out too.
Also a little more tracing on mapEndpoints.
> Exit joinResults.result() if context cancelled

- app/api_topologies.go
- app/api_topology.go
- app/benchmark_internal_test.go
- app/collector_test.go
- report/node.go
- report/report.go
Scope probes send full reports and deltas. If a node is eliminated between two full reports, then the app might only have a delta of its last state.
Remove all such nodes before rendering.
> Remove partially merged nodes from deltas

- backend/Dockerfile
- probe/endpoint/dns_snooper_others.go
This PR adds support for s390x architecture. 
Changes implemented:
1) Skipped `go install -race -tags netgo std;` in backend/Dockerfile as ` -race ` flag is not supported on s390x.
2) Added docker binary link for s390x arch in backend/Dockerfile
3) Added s390x in `probe/endpoint/dns_snooper_others.go`  as the make command failed for s390x arch with `undefined: DNSSnooper` error.
> Add s390x support

- app/multitenant/aws_collector.go
- app/multitenant/collector.go
- prog/app.go
- prog/main.go
For when we want to collect reports in memory, but not save them to store.
Extract this functionality out of `awsCollector` to create new `liveCollector` object.
`liveCollector` now behaves quite similarly to `collector` in the single-tenant app, but with some differences: for instance it still uses NATS to broadcast shortcut reports.
> Add multitenant-live collector

- report/node.go
- report/node_test.go
Need to do the special-case merge before `n.Latest.Merge()`, otherwise it picks just one set of controls.
Also modified the test to call `Merge()` where the problem happened.
> fix: merging active controls on host

- .circleci/config.yml
- app/multitenant/collector.go
- backend/Dockerfile
- probe/docker/network_linux.go
- probe/docker/network_others.go
- probe/endpoint/connection_tracker.go
- probe/endpoint/conntrack.go
- probe/endpoint/dns_snooper.go
- probe/endpoint/dns_snooper_others.go
- probe/endpoint/dns_snooper_test.go
- probe/endpoint/ebpf.go
- probe/endpoint/ebpf_test.go
- probe/endpoint/nat.go
- probe/endpoint/nat_internal_test.go
- probe/endpoint/reporter_linux.go
- probe/endpoint/reporter_other.go
- prog/tools.go
- report/tools.go
Need to specify `-buster` otherwise libpcap gets unresolved symbols.
Add back a missing `&&` after installing packages; it doesn't make a practical difference but looks more consistent to me.
Stop rebuilding various Go libraries since they are now cached automatically for each different set of tags, and in a different
directory so the ones inside the image aren't actually used.
Compare build on master vs this branch:
```
weaveworks/scope-backend-build      master-a774857b        af5063a2025a     1.54GB
weaveworks/scope-backend-build      go-1-17-8-87988e5a     0bec25faf9c5     1.15GB
```
I have uploaded a copy of the build image to DockerHub at `bboreham/scope-backend-build:go-1-17-8-87988e5a` since I don't have write access to `weaveworks/scope-backend-build`.
> Update Go to 1.17.8; tidy build image
