app/main.go, probe/hostname.go, probe/instrumentation.go, probe/process_mapper_test.go
=> Remove old references

client/app/scripts/actions/app-actions.js, client/app/scripts/charts/nodes-chart.js, client/app/scripts/components/app.js, client/app/scripts/components/groupings.js, client/app/scripts/components/topologies.js, client/app/scripts/constants/action-types.js, client/app/scripts/stores/app-store.js, client/app/scripts/stores/topology-store.js, client/app/styles/main.less
=> Grouping switch for topologies

.gitignore, experimental/example/Makefile, experimental/example/README.md, experimental/example/client/Dockerfile, experimental/example/client/client, experimental/example/docker-compose.yml, experimental/example/goapp/Dockerfile, experimental/example/goapp/app.go, experimental/example/goapp/entrypoint.sh, experimental/example/pyapp/Dockerfile, experimental/example/pyapp/app.py, experimental/example/pyapp/requirements.txt, experimental/example/qotd/Dockerfile, experimental/example/qotd/qotd.c
This is still a bit WIP, but I reckon we stick it in the repo and all have a play with it.
Fixes #49
=> An example micro-services based application for testing purposes.

probe/main.go, xfer/publisher.go, xfer/publisher_test.go
=> One connection per app

Makefile, app/main.go, probe/main.go
=> Embed the git commit id in a go file and print it on startup.

app/origin_node.go
=> Stabilize order of rows in origin node

Makefile, app/origin_node.go, bin/test, probe/docker_process_mapper.go, probe/docker_process_mapper_test.go, probe/main.go
=> Expose Docker image IDs and Names

docker/run-probe, scope
=> Don't do the hostproc dance, use --pid=host

client/app/scripts/components/node-details.js, client/app/scripts/utils/title-utils.js
=> Set document title for node details

client/app/scripts/stores/app-store.js
=> Make containers the default topology

app/resolver.go
=> Don't bother logging DNS resolution errors.

probe/docker_process_mapper.go, probe/docker_process_mapper_test.go, probe/main.go, probe/pidtree.go
=> Use Docker events API instead of polling Docker daemon.

probe/docker_process_mapper.go, probe/main.go, probe/process_mapper.go
=> Gracefully shutdown goroutines in the probe.

.gitignore, circle.yml, experimental/Makefile, experimental/bridge/main.go, experimental/graphviz/handle.go, experimental/graphviz/main.go, experimental/oneshot/main.go
Could also remove all the lead makefiles in experimental?
=> Fix up experimental, add a makefile and add it to circle to stop experimental getting broken again.

app/report_lifo.go, experimental/demoprobe/generate.go, experimental/genreport/generate.go, experimental/graphviz/report_lifo.go, experimental/oneshot/main.go, probe/main.go, probe/spy.go, report/report.go, xfer/collector.go, xfer/merge_test.go
=> Rename NewReport -> MakeReport

probe/main.go
=> probe: only allow Docker on Linux

bin/test, xfer/collector.go, xfer/collector_test.go
=> Start testing with the race detector.

scope
=> Use a bash command in a docker container to work out host IP addresses.

report/detailed_node_test.go, report/report_fixture_test.go
Leaves some process topology bits commented out, for the future.
=> Add TestOriginTable

probe/main.go, probe/tag/docker_tagger.go, probe/tag/docker_tagger_test.go, probe/tag/pidtree.go, report/detailed_node.go, report/detailed_node_test.go, report/merge.go, report/report.go, report/report_fixture_test.go
=> Process topology

report/id_list.go, report/report.go, report/topology.go, xfer/collector.go, xfer/collector_test.go, xfer/merge_test.go
=> Add Validate method to Report & Topology.

app/api_topologies.go, app/api_topology.go, app/router.go, probe/tag/docker_tagger.go, probe/tag/docker_tagger_test.go, report/detailed_node.go, report/mapping.go, report/mapping_test.go, report/merge.go, report/report.go, report/topology.go, report/topology_test.go
With this change, the containers topology shows containers not actively communicating.
Fixes #171
=> All merging of RenderableNodes, such that we can merge multiple topologies.

client/app/scripts/components/details.js, client/app/scripts/components/node-details.js, client/app/styles/main.less
=> Display a n/a header in details if nodes are gone

client/app/scripts/charts/nodes-chart.js, client/app/scripts/charts/nodes-layout.js, client/app/scripts/stores/app-store.js, client/package.json, client/webpack.config.js
=> Reduce build warnings

client/app/scripts/charts/node.js, client/app/scripts/charts/nodes-chart.js, client/app/styles/main.less
=> Styled pseudonodes pale and remove interaction

report/detailed_node.go
=> Dedupe tables in detail pane

app/main.go
=> Seed random so different apps have different ids.

app/report_lifo.go
=> Squash merged reports as they come out of the LIFO, not individual reports as they come in.

probe/tag/docker_container.go, probe/tag/docker_tagger.go
This accidentally got deleted.  See #217 for background,  Will merge tomorrow.
=> Add docker stats to the Container Topology

client/README.md, client/app/scripts/actions/app-actions.js, client/app/scripts/charts/nodes-chart.js, client/app/scripts/charts/nodes-layout.js, client/app/scripts/components/app.js, client/app/scripts/components/status.js, client/app/scripts/constants/action-types.js, client/app/scripts/stores/__tests__/app-store-test.js, client/app/scripts/stores/app-store.js, client/app/scripts/utils/web-api-utils.js, client/webpack.config.js
* clear nodes cache when websocket closes connection
* also show reconnection status
fixes #162
=> Prevent leftover nodes after scope restart

.gitignore, report/topology.go, xfer/collector.go
=> Improve error messages during report validation

probe/main.go, probe/tag/weave_tagger.go, probe/tag/weave_tagger_test.go, report/id.go, report/merge.go, report/report.go
PTAL! No changes to the Weave /status-json yet, obviously.
=> WeaveTagger and the Overlay topology 

client/app/styles/main.less, client/gulpfile.js, client/package.json
Included so fonts work also w/o internet connection
=> Include roboto in build

render/renderable_node_test.go
=> Add test for renderable node merging.

bin/lint
Also fix up some variable naming, and don't lint git history!
=> Add simple spellchecking to linter.

app/api_topology_test.go, render/id.go, render/mapping.go, render/topologies_test.go, report/id.go
=> Extract out rendered node id generation into a small set of functions.

Makefile, app/origin_host.go, probe/host/reporter.go, probe/host/reporter_test.go, probe/host/system_darwin.go, probe/host/system_linux.go, probe/main.go, render/detailed_node.go, render/mapping.go, render/theinternet.go, render/theinternet_test.go
- add tests
- use constants for NodeMetadata keys
- add host uptime and kernel version
helps toward #238
=> Move probe host topology code into its own module

render/detailed_node.go, render/detailed_node_test.go
=> Fix order of tables in details panel to go from most to least granular.

scope
=> Fail quickly in the ./scope script.

Makefile, circle.yml, client/webpack.config.js
run JS smoke test before make static
fixes #277
=> Add smoke test for JS bundle

bin/test, probe/docker/container_test.go, probe/docker/registry_test.go, test/poll.go, xfer/collector_internal_test.go
=> Add -cpu 4 to tests.

report/id_list.go
=> Neater implementation of de-duplication in MakeIDList()

probe/docker/container_test.go, probe/docker/registry_test.go, test/poll.go, xfer/collector_internal_test.go
=> Use poll in TestRegistryEvents.

bin/rebuild-ui-build-image, circle.yml
=> Detect when to rebuild cached build image.

scope
Seems to work. Whether or not it's a good idea... maybe we want to put it on a switch? `scope launch --no-expose`?
=> weave expose prior to scope launch

client/app/scripts/stores/__tests__/app-store-test.js, client/app/scripts/stores/app-store.js
=> Close details when changing topologies

integration/105_launch_sans_weave_test.sh, integration/setup.sh
=> add integration test for launching scope without weave installed

app/main.go
This has been bugging me for a little while. Any objection I've overlooked?
=> app may only log to stderr, just like probe

scope
=> Rm temporary containers.

render/detailed_node.go, render/detailed_node_test.go, report/id.go
=> Condense origin address entries into a single table.

app/api_topology_test.go, render/expected/expected.go, render/mapping.go, render/topologies.go, report/merge.go, report/topology.go
=> Show how many containers have been grouped together under an image

probe/process/reporter.go, probe/process/reporter_test.go
=> Don't report empty fields from process

probe/docker/container.go
=> Change log message to make it clear this probably isn't an error.

app/router.go, xfer/publisher.go, xfer/publisher_test.go
=> gzip compression

probe/docker/registry_test.go, test/poll.go
=> Fail if want != have!

Makefile
=> Improved error message when docker-squash is not detected

docker/Dockerfile, experimental/example/shout/Dockerfile
=> Use alpine:latest instead of gliderlabs/alpine

client/app/scripts/components/node-details-table.js, client/app/scripts/components/node-details.js, client/app/styles/main.less
=> Trim long container names and labels in details

render/expected/expected.go, render/mapping.go, render/mapping_test.go, render/render.go, render/render_test.go, render/renderable_node.go, render/renderable_node_test.go, render/selectors.go, render/topologies.go, render/topology_diff_test.go, report/report.go, report/topology.go
Includes #421, those changes will go away when thats merged.
Part of #357 
Doesn't actually buy us as much as I'd hoped.
=> Remove LeafMap - have a generic function which converts a Topology to RenderableNodes

app/router.go, render/expected/expected.go, render/mapping.go, render/topologies.go, render/topologies_test.go
=> Make container rank the image _name_

probe/endpoint/reporter.go, render/mapping.go
=> Prevent short lived connections appearing as pseudo nodes in the applications view.

render/detailed_node.go, render/detailed_node_test.go
=> Don't send numeric=true for connections table.

client/app/scripts/actions/app-actions.js, client/app/scripts/utils/web-api-utils.js
=> Apply topology options to detail API

client/app/scripts/stores/__tests__/app-store-test.js, client/app/scripts/stores/app-store.js
=> Refresh should keep topology options

.gitignore, Makefile, backend/Dockerfile, backend/build.bash
=> Backend build container

app/router.go
=> Don't close the request body.

probe/docker/registry_test.go
=> Address intermittent failure in registry_test.go

client/app/scripts/charts/edge.js, client/app/scripts/charts/node.js, client/app/scripts/charts/nodes-chart.js, client/app/scripts/components/app.js, client/app/scripts/components/nodes.js, client/app/scripts/stores/__tests__/app-store-test.js, client/app/scripts/stores/app-store.js, client/app/styles/main.less, client/package.json
Highlights selected nodes like in Cello, with a circular layout of the adjacent nodes and a fade out of the non-adjacent nodes.
=> Highlight selected node

client/app/scripts/charts/nodes-chart.js, client/app/scripts/components/nodes.js, client/app/styles/main.less
=> Show message in UI when topology too big to render

client/app/scripts/charts/node.js, client/app/scripts/charts/nodes-chart.js
* shift center of radial layout a bit
* shrink blurred nodes
* blow up focused nodes a bit
=> Dont cover other nodes on radial layout

client/app/scripts/charts/nodes-chart.js, client/app/scripts/charts/nodes-layout.js
=> Dont shift canvas after it has been autoshifted

probe/endpoint/conntrack.go
=> Don't fail if there are no existing NAT mappings.

probe/docker/reporter.go, probe/docker/tagger.go, probe/docker/tagger_test.go, probe/host/reporter.go, probe/host/reporter_test.go, probe/host/tagger.go, probe/host/tagger_test.go, probe/overlay/weave.go, probe/sniff/sniffer_internal_test.go, probe/tag_report.go, probe/tag_report_test.go, xfer/collector_test.go
=> Audit uses to Topology.Nodes, use AddNode where appropriate.

render/render.go, render/render_test.go
=> Remove pseudo nodes that are made unconnected by filtering.

vendor/runsvinit/README.md, vendor/runsvinit/main.go
=> vendor/runsvinit: update vendored copy

app/router.go, probe/docker/container.go, probe/docker/container_linux_test.go, probe/docker/registry_test.go, render/mapping.go, render/topologies.go
=> Add containers by hostname view.

integration/100_launch_test.sh, integration/105_launch_sans_weave_test.sh, integration/200_clustering_2_test.sh, integration/205_clustering_sans_weave_2_test.sh, integration/300_internet_edge_test.sh, integration/310_container_to_container_edge_test.sh, integration/320_container_edge_cross_host_2_test.sh, integration/config.sh, integration/setup.sh
=> Add tests for short-lived connection between hosts and containers.

probe/host/system_linux.go, probe/host/system_utils_linux.go, probe/host/system_utils_linux_arm.go
=> Make Scope build on arm

scope
=> Make getting the docker run command easier.

app/api_topologies.go, app/api_topology.go, app/router.go
Fixes #561 
Also dedupe some of of the structs in the app, topologyView -> APITopolgyDesc, optionValue -> APITopologyOption.
=> Sort the structs returned by /api/topology

common/exec/exec.go, probe/endpoint/conntrack.go, test/exec/exec.go
=> Retry conntrack, after a short delay, in a loop.

scope
=> Make Docker version extraction more robust

probe/endpoint/conntrack.go, probe/endpoint/conntrack_internal_test.go
=> Fix close on nil channel

app/api_topologies.go, app/api_topology.go, app/router.go
=> Don't keep stacking filters onto renderers, close idle http connections when we close a http publisher.

app/origin_host.go, probe/docker/container.go, probe/docker/container_linux_test.go, probe/host/reporter.go, probe/host/reporter_test.go, probe/overlay/weave.go, probe/overlay/weave_test.go, render/mapping.go, render/renderable_node.go, render/short_lived_connections_test.go, render/theinternet.go, render/theinternet_test.go, report/id_list.go, report/topology.go, report/topology_test.go, test/fixture/report_fixture.go
=> NodeMetadata Sets

scope
=> Make sure scope can start after an upgrade.

Makefile, backend/build.sh, bin/release
=> Release script should use make tests to run tests; also fix build warning.

app/api_topologies.go
=> Fix stats for sub topologies.

render/topologies.go
Do this by filtering unconnected nodes after mapping them to containers, not before.
Fixes #511
=> Prevent a stranded Uncontained node from appearing in container view.

client/app/scripts/components/node-details-controls.js, client/app/scripts/components/node-details.js, client/app/scripts/mixins/node-color-mixin.js, client/app/styles/main.less
Added a spinner too, it shows up during the request.
=> Control bar below node details header

report/metrics.go, report/metrics_internal_test.go
=> Fix a couple bugs in metrics first/last calculation

circle.yml
Seems to shave a minute or so.
=> Merge some steps in vain attempt to speed up runs.

client/app/scripts/charts/node.js, client/app/scripts/charts/nodes-chart.js, client/app/scripts/components/nodes.js, client/app/styles/main.less
* dont allow panning while node is selected
* restore old panning position after deselect
Fixes #615
=> Always center selected node

render/topologies.go
=> Avoid stranded internet nodes in the containers view.

client/app/scripts/components/details.js, client/app/styles/main.less
=> Add x to close details panel again

client/app/scripts/components/topology-options.js
=> Take default topology option if missing in URL

client/app/scripts/actions/app-actions.js, client/app/scripts/utils/web-api-utils.js
=> Dont send topology options when requesting node details

render/filters.go, render/filters_test.go
=> Filter nodes that are only connected to themselves.

app/router.go, client/app/scripts/actions/app-actions.js, client/app/scripts/components/app.js, client/app/scripts/stores/app-store.js, common/hostname/hostname.go, prog/probe/main.go, xfer/app_client.go
Fixes #282
- Add hostname to /api
- todo: show it in ui.
=> Show hostname of app you are connected to

docker/entrypoint.sh, prog/app.go, prog/main.go, prog/probe.go, scope
=> Rationalise version handling

client/app/scripts/components/terminal-app.js, client/app/scripts/components/terminal.js
=> Fixes popped out terminal title

client/app/scripts/components/terminal.js, client/app/scripts/vendor/term.js
=> Fixes AltGr+3 which is required in some locales (UK).

client/app/scripts/components/terminal.js
=> Fixes display of unicode characters in the terminal

circle.yml, integration/gce.sh
This fixes the breakages on master.  @rade suspects it was https://github.com/weaveworks/weave/issues/1851
=> Build new test VM (to pickup latest Docker version).

xfer/controls.go
=> Don't panic if you don't understand the message on the control WS.

integration/330_application_edge_test.sh, integration/340_application_edge_across_host_2_test.sh
Interaction of two PRs which on their own passed, it seems.
=> Fix tests.

Makefile, backend/Dockerfile, tools/test
And some improvements from https://github.com/weaveworks/weave/pull/1861
=> Speed up tests with go test -i

render/mapping.go
Fixes #727 
@paulbellamy @tomwilkie PTAL
=> k8s: Render container names from label "io.kubernetes.container.name"

circle.yml, integration/330_application_edge_test.sh, integration/config.sh, integration/gce.sh, integration/run_all.sh, integration/setup.sh, tools/integration/assert.sh, tools/integration/config.sh, tools/integration/gce.sh, tools/integration/run_all.sh, tools/integration/sanity_check.sh, tools/runner/runner.go
This uses tools from https://github.com/weaveworks/build-tools/pull/13, so that should be merged first.
- <s>increase lifespan of cached templates</s> (deferred to later PR)
=> Speed up integration tests

client/app/scripts/vendor/term.js
=> Fixes ctrl-arrow keys in terminal

app/api_topologies.go, probe/kubernetes/service.go
=> General k8s fixups

client/app/scripts/actions/app-actions.js
=> Allow dismissing a disconnected terminal w/ <esc>

client/app/scripts/components/node-details/node-details-controls.js
=> Corrects the node control error placement

client/app/scripts/actions/app-actions.js, client/app/scripts/components/app.js, client/app/scripts/components/embedded-terminal.js, client/app/scripts/stores/app-store.js
- Also fixes strange issue where hitting ESC while a terminal was
active, would update the route, reload the top card, and break the
terminal connection status.
Fixes #847
=> Fixes exec/attach from the 2nd+ card.

render/topologies.go, render/topologies_test.go
Fixes #857
Was introduced in #838
=> fix bug in containers being filtered by image name

render/filters.go, render/memoise.go, render/memoise_test.go, render/render.go
No performance impact, but encapsulates the caching mechanism a bit more.
@tomwilkie wdyt?
=> Refactored render/memoise and added a basic test for it

render/detailed/node.go, render/filters_test.go, render/renderable_node.go, report/node_set.go, report/node_set_test.go
Part of #502, #854
Gives a small performance boost (~30%) on the HostRenderer report.json.
=> use immutability for the NodeSet

app/api_topologies.go
=> Rename 'by hostname' to 'by dns name'

client/app/scripts/charts/nodes-chart.js, client/app/scripts/components/details-card.js, client/app/scripts/components/embedded-terminal.js, client/app/scripts/components/terminal.js, client/app/scripts/constants/styles.js, client/app/scripts/stores/app-store.js
Couple of other small fixes in this PR. Tried to split it up into lots of little commits for easier reviewing.
Fixes #848
=> Stop details cards popping up over the terminal.

render/selectors_test.go, report/edge_metadatas_internal_test.go, report/sets.go
=> Add some tests, and a zero-value for report.Sets

probe/appclient/app_client_internal_test.go
=> Increase timeout, remove double close.

client/app/scripts/components/node-details/node-details-table-node-link.js
=> Just show the untruncated label in the tooltip on children

render/detailed/node.go, render/detailed/parents.go, render/detailed/parents_test.go, test/fixture/report_fixture.go
=> Hosts should not be their own parent

probe/kubernetes/reporter.go
@paul creating a pull request since it brings down the probe CPU performance impact of kubernetes from 15% to ~2%
Improves #812
=> Compile k8s selectors once (not for each pod)

client/app/styles/main.less
Broken icon margins:
Fixed version:
=> Fixes status icon regression

experimental/fixprobe/main.go
=> Fix JSON encoding for fixedprobe

client/app/styles/main.less
* expand contrast between text styles
* remove low opacity from footer
Fixes #874 together with #954
=> Improve contrast of default view

client/app/styles/main.less
=> Center align "SHOW MORE" labels in details panel

client/app/scripts/charts/node-shape-stack.js
=> Increase space between stacked nodes and their labels

README.md
Similar to what we do for Weave Net.
=> Use short URL for scope download

Makefile
Also, don't rmi the images on `make clean` - rm'ing the .uptodate files is enough to ensure we rebuild the images, and rmi'ing the images causes us to have to redownload a lot of stuff.
A complete rebuild with this PR is almost 2 minutes faster (not these both include the rmi change):
```
$ # without change
$ make clean; time make
...
real	5m38.475s
user	0m5.205s
sys	0m1.306s
$ # with change
$ make clean; time make
...
real	3m56.951s
user	0m5.190s
sys	0m1.259s
```
=> Turn off GC for builds.

probe/docker/registry.go
=> Handle closing of docker events channel gracefully

README.md
=> Document how to obtain profiles without `go tool pprof`

client/app/scripts/charts/node-shape-heptagon.js, client/app/scripts/charts/node-shape-septagon.js, client/app/scripts/charts/node.js, client/app/scripts/components/debug-toolbar.js, render/expected/expected.go, render/mapping.go, render/renderable_node.go
=> Adds support for the heptagon node shape

docker/entrypoint.sh, integration/210_clustering_custom_hostname_2_test.sh
=> Plumb through custom weave domains.

docker/entrypoint.sh, prog/probe.go
=> Fix up some flags

backend/Dockerfile, render/theinternet_test.go, report/edge_metadatas_internal_test.go
=> Upgrade to go1.6

render/mapping.go, render/topologies.go
=> Stop mutating nodes in the rendering pipeline

app/controls.go, common/xfer/controls.go, probe/appclient/app_client.go
=> Have the probe fill in the app id, not the app

prog/app.go
=> Check error in checkpoint callback.

Makefile
=> Remove codecgen-generated file before building package

client/app/scripts/charts/node-shape-cloud.js, client/app/scripts/charts/node-shape-stack.js, client/app/scripts/charts/node.js, client/app/scripts/components/app.js, client/app/scripts/utils/contrast-utils.js, client/app/styles/contrast.less, client/app/styles/main.less
* increase stack node borders by 0.5px (fixes #1080)
* space out stacks in contrast mode (fixes #1020)
* fix cloud border stroke-width setting (exlude from CSS styling)
* adjust cloud border for contrast mode
=> Adjust node borders

experimental/demoprobe/main.go, experimental/genreport/generate.go, experimental/sniff/sniffer.go, probe/appclient/app_client_internal_test.go, probe/endpoint/reporter.go, probe/endpoint/reporter_test.go, probe/probe_internal_test.go, probe/topology_tagger.go, render/expected/expected.go, render/id.go, render/mapping.go, render/mapping_test.go, render/selectors.go, render/topologies.go, render/topologies_test.go, report/report.go, test/fixture/report_fixture.go
=> Remove address topology

experimental/example/Makefile, experimental/example/client/client.py, experimental/example/run_tracer.sh, experimental/example/trace_app/Dockerfile, experimental/example/trace_app/app.py, experimental/example/trace_app/requirements.txt, experimental/tracer/Makefile, experimental/tracer/main/main.go, experimental/tracer/main/store.go, experimental/tracer/tracer, probe/docker/controls_test.go, probe/docker/registry.go, probe/docker/registry_test.go, prog/probe.go
Needs a quick review as slightly modifies the docker registry in the probe (which tracer reuses).
=> Update demo for tracer

client/app/styles/main.less
* epilogue to #1080
* slightly thinner borders are more in line with, ehem, other lines
=> Slightly thinner borders on nodes

client/app/scripts/utils/web-api-utils.js
=> Fixes term error handling

probe/docker/container.go, probe/docker/reporter.go
=> strip sha256: from docker image ids

client/app/scripts/charts/edge.js, client/app/scripts/charts/node.js, client/package.json
* caused lots of lag when dev tools were open
=> Downgrade react-motion

render/filters.go
=> Stop mutating nodes in ColorConnected filter

CHANGELOG.md, Makefile, README.md, backend/Dockerfile, client/Dockerfile, client/app/scripts/actions/app-actions.js, client/app/scripts/charts/__tests__/node-layout-test.js, client/app/scripts/charts/node.js, experimental/sniff/sniffer.go, experimental/tracer/README.md, experimental/tracer/ptrace/ptracer.go, probe/docker/registry.go, probe/endpoint/procspy/lsof.go, probe/endpoint/reporter_test.go, probe/host/tagger.go, render/filters.go, render/mapping.go, report/id.go, report/report.go, test/poll.go, tools/lint, tools/rebuild-image, tools/socks/main.go
=> Update tools & build container to check for spelling mistakes

vendor/README.md
=> Add vendoring docs

render/expected/expected.go, render/mapping.go
Fixes #1155 
Note this will have the same effect on the process view, but given we now have node shape, I think that desirable.
=> Don't show multiple pseudo nodes in the host view for the same IP

bin/release
Need to figure out what to do about the version check.
=> Make bin/release work on a mac.

client/app/scripts/utils/web-api-utils.js, client/app/styles/main.less
* blank keyframes for blinking Connect animation
* increased topology API retry timer interval
Fixes #1220
=> Reduce CPU consumption if UI cannot connect to backend

render/detailed/connections.go
=> better detection of endpoint children, to avoid including MapX2IP results

client/app/scripts/charts/nodes-layout.js
Prevents lots of JS errors when starting/stopping scope.
=> Make cached edge processing more robust

client/app/scripts/charts/node.js, client/app/scripts/components/debug-toolbar.js
* makes it easier to read long node labels on demand
=> Dont trunctate node labels on hover

client/app/scripts/charts/nodes-chart.js
Fixes regression introduced by #1186 (comparing wrong layout state
objects)
Fixes #1242
=> Keep edge and node movement in sync

client/app/scripts/charts/nodes-chart.js
* track browser dimensions as chart state
* only override on force layout
Fixes #1096 
Alternative to PR #1266
=> Dont scale nodes after browser window resize

prog/probe.go
=> Don't add plugin registry if creating it fails

render/detailed/docker_labels.go, render/detailed/docker_labels_test.go, render/detailed/node_test.go
=> Add labels to docker labels

app/collector.go, app/collector_test.go
=> Correctly expire the cache in the collector

probe/kubernetes/pod.go, probe/kubernetes/reporter.go, render/detailed/node_test.go, test/fixture/report_fixture.go
=> Show k8s pod status

render/detailed/parents.go
=> Construct correct id for pod parents

probe/docker/container.go, probe/docker/env.go, probe/docker/env_test.go, render/detailed/summary.go
=> More sensible container names for Mesos/Marathon

client/app/scripts/charts/nodes-chart-elements.js, client/app/scripts/charts/nodes-chart-nodes.js, client/app/scripts/charts/nodes-chart.js, client/app/scripts/components/app.js, client/app/scripts/components/node-details/node-details-health-item.js, client/app/scripts/components/node-details/node-details-health-overflow-item.js
=> Sync ui metrics

examples/plugins/README.md, examples/plugins/iowait/Makefile, examples/plugins/iowait/main.go
* fix json highlighting on github
* added screenshot
* note about kernel version for bcc plugin
* sentence about seeing plugin in the UI
=> Fix plugins docs

Makefile, backend/Dockerfile
See https://groups.google.com/forum/#!msg/golang-announce/9eqIHqaWvck/kXsfO0ogLAAJ
I don't think we're affected, but might as well do it.
=> Update to go 1.6.1

render/detailed/parents.go
=> Strip image version from parent links

render/mapping.go
=> Show number of pods in service minor

probe/kubernetes/reporter.go, probe/kubernetes/reporter_test.go, probe/kubernetes/service.go
Fixes #1343 
Need to try this out on a k8s cluster which supports public load balancers
=> Show the k8s load balancer IP if it is set

render/filters.go
A small pull request, solving https://github.com/weaveworks/scope/issues/1355.
=> Add swarm-agent, swarm-agent master to sys container filters

prog/probe.go, vendor/github.com/weaveworks/go-checkpoint/Makefile, vendor/github.com/weaveworks/go-checkpoint/README.md, vendor/github.com/weaveworks/go-checkpoint/backend/Dockerfile, vendor/github.com/weaveworks/go-checkpoint/backend/build.sh, vendor/github.com/weaveworks/go-checkpoint/checkpoint.go, vendor/github.com/weaveworks/go-checkpoint/checkpoint_test.go, vendor/github.com/weaveworks/go-checkpoint/circle.yml, vendor/manifest
=> Add kubernetes checkpoint flag

probe/appclient/app_client.go, probe/docker/controls.go, probe/kubernetes/client.go, probe/kubernetes/controls.go, probe/kubernetes/pod.go, probe/kubernetes/reporter.go, probe/kubernetes/reporter_test.go, probe/kubernetes/service.go, probe/kubernetes/store.go, prog/probe.go, render/pod.go, report/id.go
Didn't add service, as it looks like [kubectl is responsible to tidying up pods...](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/delete.go)
=> Add pod delete controls

probe/kubernetes/pod.go, probe/kubernetes/reporter.go, render/detailed/node_test.go
=> Show Pod IP in details panel.

probe/docker/container.go, probe/docker/container_test.go, probe/docker/registry.go, probe/docker/registry_test.go, probe/docker/reporter.go, probe/docker/reporter_test.go, render/container.go, render/container_test.go, report/controls.go, vendor/github.com/armon/go-radix/LICENSE, vendor/github.com/armon/go-radix/radix.go, vendor/manifest
=> Propagate network info for containers sharing network namespaces

prog/main.go
=> Honour the --service-token flag properly.

render/pod.go, render/render.go
=> Add a condition to rendering any kubernetes nodes at all

scope
=> Make Scope work on Docker for Mac

probe/docker/container.go, probe/docker/container_test.go, probe/endpoint/nat_internal_test.go, probe/endpoint/reporter.go, probe/kubernetes/reporter.go, prog/probe.go, render/short_lived_connections_test.go
=> Correctly attribute DNAT-ed short-lived connections

scope
=> Revert "Make Scope work on Docker for Mac"

app/api_topologies.go
=> Set 'default' as the default namespace filter instead of 'all'

render/pod.go
We don't do our filtering like that anymore.
=> Don't filter out Services etc which don't have pods

probe/kubernetes/client.go
=> Disable deployments and replica sets if k8s is 1.1

integration/106_launch_with_peers_test.sh, integration/205_clustering_sans_weave_2_test.sh, integration/215_clustering_split_2_test.sh, prog/main.go, prog/probe.go
=> Don't require the user to specify localhost when manually listing hosts

scope
=> Check HOME variable before using it

render/container.go
This is the basic fix for #1501 
<s>I'm worries how this might affect filtering though.  @paulbellamy, thoughts?</s>  Pretty sure its safe.
=> Don't merge in container image metadata into containers anymore.

app/multitenant/consul_pipe_router_internal_test.go, integration/gce.sh
To try and make tests run faster.
=> Increase test replicas

render/pod.go
=> Propagate the pod counter from replicasets for deployments.

app/multitenant/dynamo_collector.go
Should give us a bit of a speed up.
=> Use smart merger in the DynamoDB collector.

common/middleware/path_rewrite.go
=> Rewrite net/http.Request.{URL.Path,RequestURI} consistently

probe/docker/container.go, probe/docker/container_test.go, probe/docker/registry_test.go
=> Gather IPs from all the container networks

probe/appclient/app_client.go, probe/appclient/app_client_internal_test.go
=> probe: add timeout to publisher and cancel requests on Stop()

site/installing.md
=> added line about kubectl version matching cluster

docker/entrypoint.sh, docker/run-probe, prog/probe.go
Also, clean up entrypoint script.
Fixes #1566
=> Fix handling of implicit probe targets

probe/docker/reporter.go
=> Add all docker subnets to overlay topology

render/container.go, render/pod.go
=> Join pod topology directly with short lived connections

app/multitenant/consul_client.go
Fixes https://github.com/weaveworks/service/issues/423
=> Add backoff to the consul client

prog/main.go, site/installing.md
Fixes #1596 
- "My Scope" -> "View Instance"
- A couple of occurrences of scope.weave.works
- Example of how to use Weave Cloud with k8s
- Examples of when its appropriate to use Weave Cloud
=> Clarify instructions for using Scope with Weave Cloud

site/installing.md
@tomwilkie fixes #1525 
if this looks OK, I will also fix the readme in the repo with the same instructions.
=> removed boot2docker reference 

app/multitenant/aws_collector.go
I've verified locally that the data shows up and looks good.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/scope/1668)
=> Store a histogram of report sizes

probe/docker/container.go
This got broken in b78c503
Fixes #1691
=> show names of stopped containers

common/instrument/instrument.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/scope/1722)
=> Delete unused instrumentation code

client/app/scripts/components/node-details/node-details-table.js
For firefox+linux which renders slightly tighter it seems
Fixes #1711
=> Make the port column a little wider to stop truncation

prog/app.go
Part of https://github.com/weaveworks/service/issues/671
=> Also serve UI under /ui

client/app/scripts/components/search.js, client/app/styles/main.less
* simplify search icon and label markup
Fixes #1715
=> Fixes search icon position on chrome

probe/kubernetes/reporter.go, render/filters.go
=> Identify kubernetes pause containers more broadly

scope
=> Don't complain when stopping Scope if it wasn't running

client/app/scripts/charts/nodes-grid.js, client/app/scripts/components/node-details/node-details-table-row.js, client/app/scripts/components/node-details/node-details-table.js, probe/process/reporter.go
ala excel/spreadsheets etc.
Fixes #1745
=> Right align numbers, left align strings.

app/multitenant/aws_collector.go
We fell victim to variable shadowing here. Ouch.
=> fix report store query chaining

examples/plugins/http-requests/http-requests.c, prog/main.go, report/report.go
Circle won't be clean until these two bugs are squashed though: https://github.com/client9/misspell/issues/76 https://github.com/client9/misspell/issues/77
=> Fix spelling mistakes

app/collector.go, app/collector_test.go, app/multitenant/aws_collector.go, app/multitenant/memcache_client.go, app/multitenant/s3_client.go, app/router.go, docker/Dockerfile
=> Don't reencode reports in the collector

integration/410_container_control_test.sh, probe/docker/controls.go, probe/host/controls_darwin.go, probe/host/controls_linux.go
=> Use login shells in terminals

probe/docker/container.go, probe/host/system_darwin.go, probe/host/system_linux.go
=> correct cpu metrics

probe/kubernetes/reporter.go
=> Only consider pod parents living in the same namespace

probe/endpoint/conntrack.go, probe/endpoint/conntrack_internal_test.go, probe/endpoint/reporter.go, probe/endpoint/reporter_test.go, prog/probe.go
=> Improve conntrack kernel-support detection for in-kernel compilations

client/app/scripts/components/node-details/node-details-table.js, client/app/scripts/reducers/root.js
- And number columns DESCending by default.
- default: when you sort by that column for the first time.
Fixes #1802
=> Sort non-number columns ASCending by default.

client/app/scripts/components/terminal-app.js, client/app/scripts/components/terminal.js, client/app/styles/main.less
- Fixes react warning p > div.
- Adds esc to close popped out terminal.
Fixes #1639
=> Adds tooltip to terminal-popout button

probe/endpoint/reporter.go, render/detailed/connections.go
=> correctly reverse resolve source of inbound connections

render/detailed/summary.go
plus some fly-by constification.
=> refactor: extract pluralization

backend/Dockerfile
=> Upgrade to go1.7

render/detailed/connections.go
=> in details panel, count connections only once

client/app/scripts/components/node-details/node-details-table.js, render/detailed/connections.go
=> Fix ip column width in connections table, avoid truncating long ips

client/app/scripts/components/node-details/node-details-table.js
- The label column now flexes to the available space. (Old behaviour:
label width was a function of # of cols).
- Most columns other than the label now have a fixed width specified
(some large ones are left to share the avaiable space w/ the label)
Fixes #1882
=> Drop our label-col width heuristic for less wasted col. space

client/app/scripts/charts/node-container.js, client/app/scripts/charts/nodes-chart-elements.js, client/app/scripts/charts/nodes-chart.js, client/app/scripts/charts/nodes-grid.js, client/app/scripts/components/app.js, client/app/scripts/components/debug-toolbar.js, client/app/scripts/components/nodes.js, client/app/scripts/selectors/chartSelectors.js, client/app/scripts/utils/topology-utils.js, client/package.json, client/server.js, client/test/actions/90-nodes-select.js, client/test/browser-perf/main.js, client/test/run-jankie.sh
- We were being a bit overzealous w/ our layout caching.
Fixes #1829
=> Fixes metrics-on-canvas updating.

circle.yml
Conditional was the wrong way around.
=> Fix circle.yml to actually deploy external ui changes

probe/appclient/app_client.go, probe/appclient/probe_config.go
=> Add timeouts to the probe http client

client/app/scripts/components/help-panel.js, client/app/scripts/components/search.js, client/app/scripts/selectors/chartSelectors.js, client/app/scripts/utils/search-utils.js, client/app/scripts/utils/string-utils.js, client/app/styles/main.less
=> Add a new search section to the help popover

client/app/scripts/components/node-details/node-details-table.js, probe/docker/container.go, probe/docker/container_test.go, probe/kubernetes/meta.go, probe/kubernetes/reporter_test.go
=> Increase timestamp precision

app/api_topologies_test.go, probe/kubernetes/pod.go, probe/kubernetes/reporter_test.go, render/pod.go
=> Discard short-lived connections to/from Pods in the host net

client/app/styles/main.less
Fixes https://github.com/weaveworks/scope/issues/1945
=> fixes visual bug where empty span shows up

client/app/scripts/utils/__tests__/web-api-utils-test.js, client/app/scripts/utils/web-api-utils.js
=> Prevent querystrings from starting with &

probe/docker/container.go, probe/docker/reporter.go, probe/kubernetes/meta.go, render/container.go, render/detailed/metadata_test.go, render/detailed/node_test.go, render/detailed/summary_test.go, render/detailed/tables_test.go, report/table.go, report/table_test.go, vendor/github.com/dustin/go-humanize/LICENSE, vendor/github.com/dustin/go-humanize/big.go, vendor/github.com/dustin/go-humanize/bigbytes.go, vendor/github.com/dustin/go-humanize/bytes.go, vendor/github.com/dustin/go-humanize/comma.go, vendor/github.com/dustin/go-humanize/commaf.go, vendor/github.com/dustin/go-humanize/ftoa.go, vendor/github.com/dustin/go-humanize/humanize.go, vendor/github.com/dustin/go-humanize/number.go, vendor/github.com/dustin/go-humanize/ordinals.go, vendor/github.com/dustin/go-humanize/si.go, vendor/github.com/dustin/go-humanize/times.go, vendor/manifest
=> Add image information table to container details panel

client/app/scripts/components/terminal.js
Forgot to debounce the initial implementation
Fixes #1974
=> Fixes the terminal spamming POST requests on resize

client/app/scripts/charts/nodes-chart.js
Fix for #1997.
@foot Could you review please?
=> Fix details panel not closing on canvas click

probe/docker/container_test.go
=> Fix time-dependant test (stop testing docker client library)

app/multitenant/sqs_control_router.go
=> plug goroutine leak in control

client/app/styles/contrast.less, client/app/styles/main.less
Splitting out the text portion, re conversation here https://github.com/weaveworks/scope/pull/1952
=> increase black/white text contrast in contrast mode

site/installing.md
Context: https://weaveworks.slack.com/archives/weave-users/p1479477446003653
=> Use intuitive standalone service name in compose

app/multitenant/aws_collector.go, app/multitenant/memcache_client.go, app/multitenant/s3_client.go, app/multitenant/sqs_control_router.go, common/instrument/instrument.go, vendor/github.com/opentracing/opentracing-go/LICENSE, vendor/github.com/opentracing/opentracing-go/ext/tags.go, vendor/github.com/opentracing/opentracing-go/globaltracer.go, vendor/github.com/opentracing/opentracing-go/gocontext.go, vendor/github.com/opentracing/opentracing-go/log/field.go, vendor/github.com/opentracing/opentracing-go/log/util.go, vendor/github.com/opentracing/opentracing-go/mocktracer/mocklogrecord.go, vendor/github.com/opentracing/opentracing-go/mocktracer/mockspan.go, vendor/github.com/opentracing/opentracing-go/mocktracer/mocktracer.go, vendor/github.com/opentracing/opentracing-go/mocktracer/propagation.go, vendor/github.com/opentracing/opentracing-go/noop.go, vendor/github.com/opentracing/opentracing-go/propagation.go, vendor/github.com/opentracing/opentracing-go/span.go, vendor/github.com/opentracing/opentracing-go/tracer.go, vendor/manifest
And plumb contexts through the aws_collector etc.
=> Add OpenTracing support to TimeRequestHistogram

client/webpack.production.config.js
=> Empty publicpath needed for relative paths of scope

site/installing.md
=> Update Scope version in install docs

site/installing.md
Part of 
https://github.com/weaveworks/service/issues/1028
=> Follow redirections in curl when getting k8s resources

vendor/github.com/weaveworks/common/middleware/instrument.go, vendor/manifest
Part of weaveworks/monitoring#82
Just vendors a correct version of the library.
=> Correctly instrument websocket handshakes

scope
=> Fixes ./scope launch starting probe under d4m

client/app/scripts/contrast-main.js
Fix for #2138 
@fbarl Please review when you get a chance.
=> Fix contrast page import statement

examples/docker/docker-compose-probe-v1.yml, examples/docker/docker-compose-probe-v2.yml, site/installing.md
Fixes #2142 
Introduced in https://github.com/weaveworks/scope/pull/1146 (CC @pidster )
=> Fix Scope arguments in Docker Compose installation docs

client/app/styles/_base.scss
=> Fixes base font-size of popped out terminal.

client/app/scripts/charts/node-shape-stack.js
Fixes #2207. Forgot to rescale the stack to the `NODE_BASE_SIZE` when doing the graph layout optimizations in #2180.
=> Fix for node stack display bug

client/app/scripts/charts/node-shape-square.js
=> Fix rounded square node shadow radius

README.md, site/installing.md
Pushed these changes again (it's easier)
=> update cloud description and small edits

README.md, site/installing.md
Something was merged at the same time and caused a collision.  Please review.
=> Revert "Revert "update cloud description and small edits""

probe/docker/container.go, probe/docker/container_test.go, probe/docker/controls_test.go, probe/docker/registry.go, probe/docker/registry_test.go, probe/process/reporter.go, probe/process/reporter_test.go, prog/main.go, prog/probe.go
This reverts commit 764afb6301f2715c5d1814d7bc773d40b42610f9.
=> Revert "Add options to hide args and env vars (#2306)"

circle.yml, tools/integration/gce.sh, tools/lint
Fixes #2282 
~Tests https://github.com/weaveworks/build-tools/pull/80 locallly~
=> Secure integration tests

client/package.json
https://github.com/facebook/react/releases/tag/v15.4.2
cc @davkal. No review needed, but should help with https://github.com/weaveworks/service-ui/pull/355
=> Bump react version

app/multitenant/aws_collector.go
Discovered whilst attempting to resolve weaveworks/service#1157
=> Correct dynamoDB metric label

client/app/scripts/components/metric-selector.js
=> Keep the resource metric pinned on mouse out

client/app/scripts/utils/router-utils.js
Adds a check to ensure that breaking states are not loaded from localStorage or from the URL. Topology option values were changed from a `String` type to an `Array` type. If a string is loaded, the UI will break.
This can be removed after a reasonable amount of time has gone by (a few weeks maybe?).
=> Add check for old options

client/app/scripts/reducers/root.js, client/app/styles/_base.scss
Fixes #2377.
Also fixes #2352 again after #2353 was accidentally reversed by #2296 :)
=> Don't reset zoom on refresh layout

client/app/scripts/charts/nodes-grid.js, client/app/scripts/components/debug-toolbar.js
=> Show sublabel in tooltip for Internet nodes in table view mode

app/multitenant/billing_emitter.go, vendor/github.com/weaveworks/billing-client/client.go, vendor/github.com/weaveworks/billing-client/event.go, vendor/manifest
Fixes https://github.com/weaveworks/billing/issues/37
=> Add NodeSeconds to billing emitter

client/app/scripts/components/metric-selector.js
=> Not showing metric selector when empty

circle.yml
=> publish master to dockerhub (again)

probe/kubernetes/client.go
=> Log specific error when deployments are not supported

client/app/scripts/components/cloud-feature.js, client/app/scripts/components/sparkline.js, client/package.json, client/yarn.lock
~Will fix #2496 once https://github.com/weaveworks/ui-components/pull/27 is merged and `weaveworks-ui-components` version is updated.~
Fixes #2496.
=> Use prop-types library to silence PropTypes deprecation warning

site/installing.md
Improves #2497 
Let's please update the Scope instructions when the launch-generator _API_ changes. (CC @errordeveloper @marccarre )
=> Update k8s installation instructions

probe/awsecs/client.go
=> Avoid null dereferences in ECS client

client/app/scripts/components/node-details.js, client/app/scripts/components/node-details/node-details-image-status.js
=> Hide container image status for pseudo nodes

app/collector.go, extras/copyreport/Makefile, extras/copyreport/main.go, report/marshal.go
useful for codec and report structure experiments
=> add copyreport utility

report/map_helpers.go
=> encode empty ps.Maps as nil

client/package.json
=> bump package.json version to current scope version

prog/main.go, prog/main_test.go
=> Elide token-only credentials in cli arguments

backend/Dockerfile
=> Use Go 1.8

render/detailed/node.go
make `nodeSummaryGroupSpecs` only include what's needed
Fixes #2630.
=> correct `nodeSummaryGroupSpec`

probe/endpoint/connection_tracker.go, probe/endpoint/ebpf.go
=> correct polarity of initial connections

CHANGELOG.md, probe/endpoint/ebpf.go, probe/endpoint/procspy/spy_linux.go, site/installing.md
There is a merge conflict because the bugfixes where cherry-picked. I will have to merge locally.
=> Release 1.5.1

Makefile, client/README.md, client/package.json
=> Update README/Makefile/package.json to use yarn

client/app/scripts/selectors/graph-view/zoom.js
=> Make graph layout zoom limits constant

probe/awsecs/client.go
=> defend against nils

test_service-ui-kicker
This reverts commit a7035a4a3ef72496ffdfb1e36a882f250ec54e1b.
=> Revert "Test service-ui-kicker"

probe/kubernetes/pod.go, probe/kubernetes/reporter.go
=> Add pod restart count to details pane

bin/release
=> push release images to quay.io

service-ui-kicker-test
This reverts commit 05f6b3bd4882b19eb3b52382051fbd59054f232e.
=> Revert "service-ui-kicker-test"

client/app/scripts/components/time-travel-timeline.js
=> Fix timeline label vertical displacement on some Chromes

client/app/scripts/constants/animation.js
From Slack conversation (referring to animation speed changes in #2795):
```
matthias [11:52 PM] 
TBH, it's a bit too snappy for me now. 
...
matthias [11:54 PM] 
does it not defeat the purpose of the animations?
...
jordan
[11:55 PM] 
yeah might be a little fast
...
matthias [11:57 PM] 
I don't think animations need to be quite as lethargic as before. somewhere in between.
```
=> Make nodes graph animations a bit faster

scope
Doesn't work just yet since the curl commands get a connection refused since the App is not ready.
Fixes #1678
=> Make Scope's URL message more precise

render/detailed/links.go
=> scope/cortex: fix typo in query filter

client/app/scripts/components/cloud-link.js
=> Fix processes/hosts table not appearing

CHANGELOG.md, probe/kubernetes/cronjob.go, site/installing.md
We never merged the 1.6.2 changes. Not a big deal since it only contains build changes but we should have merged it to master when we released it.
=> Release 1.6.2

CHANGELOG.md, site/installing.md
Patch release without too many changes for non-WeaveCloud users
=> Release 1.6.3

CHANGELOG.md, site/installing.md
Re-release of 1.6.3 for which there were some problems publishing Docker images.
=> Release 1.6.4

client/app/styles/_base.scss
Resolves #2829.
Tested on FF and Chrome, both as a standalone and in WC.
~When merged, it will also trigger a Scope version bump with at least two other (non-trivial) PRs reaching dev.~
=> Fixed header elements responsiveness

circle.yml
=> Fix circle.yml syntax

client/app/scripts/charts/node.js, client/app/scripts/charts/nodes-grid.js, client/app/scripts/charts/nodes-layout.js, client/app/scripts/components/app.js, client/app/scripts/components/footer.js, client/app/scripts/components/metric-selector-item.js, client/app/scripts/components/node-details/node-details-health-link-item.js, client/app/scripts/components/node-details/node-details-relatives-link.js, client/app/scripts/components/node-details/node-details-table-node-link.js, client/app/scripts/components/node-details/node-details-table-node-metric-link.js, client/app/scripts/components/nodes-resources/node-resources-metric-box.js, client/app/scripts/components/search.js, client/app/scripts/components/time-control.js, client/app/scripts/components/time-travel-timeline.js, client/app/scripts/components/time-travel.js, client/app/scripts/components/topologies.js, client/app/scripts/components/topology-options.js, client/app/scripts/components/view-mode-selector.js, client/app/scripts/utils/tracking-utils.js
Align scope to the rest of the platform.
=> tracking: Use segment for tracking

CHANGELOG.md, site/installing.md
=> Release 1.6.5

client/app/scripts/components/zoomable-canvas.js
Fixes https://github.com/weaveworks/service-ui/issues/1205
=> Fixes "Save as svg" functionality.

prog/static.go
if block ends with a return statement, so drop this else and outdent its block
=> Fix golint if/else

client/app/scripts/components/terminal.js
=> terminal: Fix Caculated typo

docker/Dockerfile.cloud-agent, extras/example/app/Dockerfile, extras/example/client/Dockerfile, extras/example/echo/Dockerfile, extras/example/frontend-k8s/Dockerfile, extras/example/frontend/Dockerfile, extras/example/qotd/Dockerfile, extras/example/searchapp/Dockerfile, extras/example/shout/Dockerfile, extras/example/trace_app/Dockerfile, tools/socks/Dockerfile
https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
=> MAINTAINER is deprecated, now using LABEL

client/app/scripts/components/node-details/node-details-image-status.js
Fixes weaveworks/service-ui#1449
Handle cases where images can sometimes be null.
=> Fix undefined image bug

render/filters.go
Edges between the incoming and outgoing internet nodes are typically artifacts of imperfect connection tracking, e.g. when VIPs and NAT traversal are in use.
So lets filter them out.
Fixes #1110.
=> filter internet adjacencies

render/pod.go, report/report.go, report/report_test.go
This was previously done selectPodsWithDeployments.Render().
Fixes #2960.
=> report.Upgrade() add deployments to pods as parent

render/host.go, render/render.go
=> don't map image adjacencies to hosts

app/benchmark_internal_test.go
This is the last phase before result marshalling in the /api/topology/{name} handler.
There's bunch of tidying up of the benchmark code too.
=> benchmark report summarization

client/app/scripts/actions/app-actions.js, client/app/scripts/reducers/root.js
Please read the comment in the code as to why this PR is needed.
Related to https://github.com/weaveworks/service-ui/issues/1500.
=> Correctly handle Time Travel resuming in Monitor

render/theinternet.go
=> Add (cloud.)weave.works to the list of known services

client/app/scripts/charts/nodes-chart-elements.js, client/app/scripts/charts/nodes-grid.js, client/app/scripts/components/embedded-terminal.js, client/app/scripts/components/node-details.js, client/app/scripts/components/node-details/node-details-control-button.js, client/app/scripts/components/node-details/node-details-table-row.js, client/app/scripts/components/sidebar.js, client/app/scripts/components/time-travel-wrapper.js, client/app/scripts/components/topologies.js, client/app/scripts/components/view-mode-button.js, client/app/scripts/components/view-mode-selector.js, client/app/styles/_base.scss
Follow-up on https://github.com/weaveworks/service-ui/pull/2008 towards improving https://github.com/weaveworks/service-ui/issues/1861 anchors.
=> Add explicit tour-step-anchor classNames to Explore tour elements

probe/docker/container.go
Also the "none" network. This just makes probe reports slightly smaller because they won't have this:
```
"sets": {
"docker_container_ips": null,
"docker_container_ips_with_scopes": null,
"docker_container_networks": [
"none"
],
"docker_container_ports": null
},
```
This is quite typical for a container created by Kubernetes, which wires up networking via CNI so Docker doesn't know about it.
=> Exclude null entries for networks on container nodes in probe report

client/app/styles/_base.scss, client/package.json, client/yarn.lock
Resolves `scope` part of https://github.com/weaveworks/ui-components/issues/161 - these are only some minor changes (mostly renaming `weaveblue` -> `accent.blue`).
=> Switch to theme cyan colors

prog/main.go, report/table.go, report/table_test.go
=> do not truncate tables

probe/endpoint/ebpf.go, probe/endpoint/ebpf_test.go
Workaround for https://github.com/weaveworks/scope/issues/3131 until the issue is fixed upstream.
Ubuntu bug report: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1763454
=> Workaround Ubuntu kernel oops

CHANGELOG.md, site/installing.md
See CHANGELOG.md for contents
Replaces #3145
=> Release 1.9.0

client/app/styles/_base.scss, client/package.json, client/yarn.lock
Not to be merged before https://github.com/weaveworks/ui-components/pull/177.
=> Stop using dropped theme colors

report/node_set.go
I'm not sure what could cause this right now.
=> Add null check to fix querier panic

client/.sass-lint.yml, client/.stylelintrc, client/app/styles/_base.scss, client/package.json, client/webpack.local.config.js, client/webpack.production.config.js, client/yarn.lock
Scope part of https://github.com/weaveworks/ui-components/issues/162.
=> Use only z-index values from the theme

probe/kubernetes/reporter.go
=> Fix pause image detection for Kubernetes 1.10

examples/k8s/cluster-role-binding.yaml, examples/k8s/cluster-role.yaml, examples/k8s/deploy.yaml, examples/k8s/ds.yaml, examples/k8s/ns.yaml, examples/k8s/sa.yaml, examples/k8s/svc.yaml
- closes https://github.com/weaveworks/scope/issues/3153
=> examples: k8s: added manifest for scope deployment

client/app/scripts/components/terminal.js, client/app/styles/_base.scss
=> Adjusted terminal character width/height estimation

client/app/styles/_base.scss
=> Adjust font sizes

render/process.go
=> make process-by-name topology show something (again)

client/app/styles/_variables.scss
Goes with [service-ui/pull/2625](https://github.com/weaveworks/service-ui/pull/2625).
Now all backgrounds of Weave Cloud are `#fafafc`_whiteSmoke_.
=> Slightly lightening background to match the rest of WeaveCloud

examples/k8s/ds.yaml
Should match https://github.com/weaveworks/scope/blob/192f5cc6d221247eeecbbc5dab09e0252558663c/prog/main.go#L434
=> Pass node name via correct env var

client/app/styles/_base.scss, client/app/styles/_contrast-overrides.scss, client/app/styles/_variables.scss, client/package.json, client/yarn.lock
Scope part of https://github.com/weaveworks/ui-components/issues/260.
=> Use new theme gray colors

site/ami.md
They are updated to Weave Net 2.3.0 and Weave Scope 1.6.4
=> Update AWS AMI IDs

client/app/styles/_base.scss, client/app/styles/_contrast-overrides.scss, client/app/styles/_variables.scss, client/package.json, client/yarn.lock
Scope part of https://github.com/weaveworks/ui-components/issues/259.
Nothing noticable in the UI should have changed, only some CSS variable names are different.
Tested in Scope standalone.
=> Use new purple theme colors

client/app/styles/_base.scss, client/app/styles/_contrast-overrides.scss, client/app/styles/_variables.scss, client/package.json, client/yarn.lock
Scope part of https://github.com/weaveworks/ui-components/issues/273.
=> Update gray theme colors

CHANGELOG.md, site/installing.md
There's quite a bit stacked up, and I wanted to get a point release out before making a wire-protocol change in #3266
=> Release 1.9.1

client/app/scripts/charts/nodes-grid.js, client/app/scripts/components/nodes-resources/node-resources-metric-box.js, client/app/styles/_base.scss, client/package.json, client/yarn.lock
* Reduced border radius on a lot of elements (https://github.com/weaveworks/ui-components/pull/320)
* Fixed the top border radius of node details panel
* Add `react-router` dep for `ui-components` compatilibity
=> Bump ui-components version

client/package.json, client/yarn.lock
=> Bumps lodash dependency

integration/315_ebpf_restart_test.sh
=> Create bpf stop file differently, in integration test

client/app/scripts/components/app.js
=> Add onRouteChange hook to Scope app

site/ami.md
I needed to know this because of #3328 
@2opremio do you recall if there is automation to make all of them public?
=> Note how to make an EC2 AMI public

LICENSE
**Future Update : Writing test scripts to automatically update license dates!**
=> Updated license year from 2017 to 2018.

app/router.go
This means we pass cancellation, tracing, etc., down through the layers in the app.
=> Use the Context in the request

client/app/scripts/components/view-mode-selector.js
#2511 
replace share icon with sitemap (graph)
=> scripts: replace share icon with sitemap (graph)

README.md
Fixes #3404 
Add  LICENSE info to README.md
=> Add  LICENSE info to README.md

probe/kubernetes/reporter.go
=> Add EKS to paused container detection

CHANGELOG.md, examples/cri/deploy.yaml, examples/cri/ds.yaml, examples/docker/docker-compose-probe-v1.yml, examples/docker/docker-compose-probe-v2.yml, examples/k8s/deploy.yaml, examples/k8s/ds.yaml, examples/mesos/minimesos.json, site/installing.md
See changelog for contents of release.
=> Release 1.10

CHANGELOG.md, examples/cri/deploy.yaml, examples/cri/ds.yaml, examples/docker/docker-compose-probe-v1.yml, examples/docker/docker-compose-probe-v2.yml, examples/k8s/deploy.yaml, examples/k8s/ds.yaml, examples/mesos/minimesos.json, site/installing.md
This is a re-release of 1.10.0 to bring in #3439 to fix the UI build
=> Release 1.10.1

README.md, site/faq.md, site/how-it-works.md, site/installing.md
@fbarl and I talked about having a FAQ doc for Scope, where we can list tid-bits of information to work with Scope.
Started off the doc with a piece that was discussed in #3406.
=> Start off FAQ document

client/package.json, client/yarn.lock
- Keeps up w/ ui-cmp
Fixes #3449
=> Upgrades to styled-components 3

client/package.json, client/yarn.lock
Updates jquery to fix 2 medium impact vulnerabilities
https://nvd.nist.gov/vuln/detail/CVE-2015-9251
https://nvd.nist.gov/vuln/detail/CVE-2016-10707
=> fix: update materialize-css to update jquery

app/api_report.go, client/app/scripts/components/troubleshooting-menu.js, client/app/scripts/utils/web-api-utils.js, client/app/styles/_base.scss
=> Use Time Travel context when downloading raw reports

examples/k8s/cluster-role.yaml
Fixes #3594 by adding a minimal set of extra permissions.
cc @dholbach
=> Update examples/k8s RBAC permissions

client/app/scripts/actions/app-actions.js, client/app/scripts/components/footer.js, client/app/scripts/reducers/root.js
=> Fixed contrast mode in the URL

CONTRIBUTING.md
=> Add docs on how to contribute to frontend code

CONTRIBUTING.md, README.md
=> Update docs to encourage first time contributions

CHANGELOG.md, examples/cri/deploy.yaml, examples/cri/ds.yaml, examples/docker/docker-compose-probe-v1.yml, examples/docker/docker-compose-probe-v2.yml, examples/k8s/deploy.yaml, examples/k8s/ds.yaml, examples/k8s/probe-deploy.yaml, examples/mesos/minimesos.json, site/installing.md
This is just to get #3627 and #3633 out to end-users
=> Release 1.11.2

site/faq.md
Thanks @vaibhavjain882 for noticing!
Related to #3638.
=> Fix a typo in FAQ docs

bin/release
We're not using quay.io for images any more.
=> Remove quay.io from release script

CHANGELOG.md, examples/cri/deploy.yaml, examples/cri/ds.yaml, examples/docker/docker-compose-probe-v1.yml, examples/docker/docker-compose-probe-v2.yml, examples/k8s/deploy.yaml, examples/k8s/ds.yaml, examples/k8s/probe-deploy.yaml, examples/mesos/minimesos.json, site/installing.md
=> Release 1.11.5

client/package.json, client/yarn.lock
https://github.com/weaveworks/ui-components/compare/v0.20.0...v0.22.0
- We recently upgraded to sc4 in scope
- Also upgrade to a ui-components that officially supports sc4
=> Upgrades ui-components to version w/ styled-components 4

probe/docker/container.go
I guess these are left over from some other work.
=> Remove some unused string constants

.circleci/config.yml
Addresses the last bullet point in https://github.com/weaveworks/scope/pull/3685#issuecomment-533109681.
=> Update CircleCI scope-ui-build tag

MAINTAINERS
This will update email address to my current email.
=> Update email address in Maintainers file for Satyam

client/app/scripts/components/node-details/node-details-health-link-item.js, client/app/scripts/components/terminal.js, client/app/scripts/components/zoomable-canvas.js, client/app/scripts/selectors/zooming.js, client/app/scripts/utils/hash-utils.js, client/app/scripts/utils/storage-utils.js, client/app/scripts/utils/topology-utils.js, client/app/scripts/utils/web-api-utils.js
=> scripts: replace JSON.stringify with json-stable-stringify

client/webpack.local.config.js
=> Fix favicon.ico in UI dev mode

app/multitenant/billing_emitter.go
Follow-up to #3751 
Delta reports don't contain the string we are looking for, so remember it from the last full report.
=> Cache the last-known report interval per user

app/multitenant/billing_emitter.go
Billing takes an integer number of seconds, so keep track of the amount lost to rounding when the publish interval is not an integer.
=> enhancement(multitenant): Track rounding error in billing calculation

app/multitenant/billing_emitter.go
=> fix(multitenant): move use of rounding map inside lock

app/collector.go, app/multitenant/aws_collector.go, app/multitenant/billing_emitter.go, prog/app.go, prog/main.go
This means we store fewer, bigger, reports, which reduces cost of storage and time to render when data is viewed.
=> Multitenant: merge incoming reports in collector

app/multitenant/aws_collector.go, report/report.go
Also add a metric for topologies dopped because they are over limit.
=> Upgrade reports before merging in multitenant collector

CHANGELOG.md, examples/cri/deploy.yaml, examples/cri/ds.yaml, examples/docker/docker-compose-probe-v1.yml, examples/docker/docker-compose-probe-v2.yml, examples/k8s/deploy.yaml, examples/k8s/ds.yaml, examples/k8s/probe-deploy.yaml, examples/mesos/minimesos.json, site/installing.md
I'm making a point release to get the #3784 bugfix out.
Will merge the Go update #3785 after this release.
=> Release 1.13.1

client/package.json, client/yarn.lock, vendor/modules.txt
=> Update to most recent weaveworks/ui-components

.circleci/config.yml, probe/cri/registry_test.go
Incorporating changes from #3785 and #3819 and a small fixup to a test
=> Update build images

CHANGELOG.md, examples/cri/deploy.yaml, examples/cri/ds.yaml, examples/docker/docker-compose-probe-v1.yml, examples/docker/docker-compose-probe-v2.yml, examples/k8s/deploy.yaml, examples/k8s/ds.yaml, examples/k8s/probe-deploy.yaml, examples/mesos/minimesos.json, site/installing.md
=> Release 1.13.2

prog/main.go
it enables option to utilize docker swarm secret storage for password instead of env variables or app switches
=> allow to read password from file

app/collector.go
We call `UnsafeRemovePartMergedNodes()` which modifies the data, so all implementations of `Report()` must ensure they return a new object, not one which is cached or shared across goroutines.
Fixes #3855
=> fix: copy report before modifying

app/multitenant/billing_emitter.go
PR #3822 made the kubernetes probe send host nodes, so we need to exclude them from counting when billing.
=> multitenant: only count real hosts for billing

MAINTAINERS
I am moving on from Weaveworks, however I would like to remain a maintainer of Scope as a hobby project.
=> Update email address of Bryan Boreham as maintainer

CONTRIBUTING.md, README.md, site/building.md, site/features.md, site/installing.md
- Make markdownlint happier
- Fix some typos
- Make it clear that meetings are currently on hold
Signed-off-by: Daniel Holbach <daniel@weave.works>
=> Docs fixes

Makefile, backend/Dockerfile
This PR adds support for s390x architecture.
=> Add s390x support 

site/ami.md, site/faq.md, site/how-it-works.md, site/installing.md, site/introducing.md
Remove docs referring to sunset Weave Cloud product.
=> Docs: remove Weave Cloud
